import type { CreatePortBlockRequest, PortBlockKind, PortBlockPort, PortBlockVersionDocument } from '../topology/portBlockTypes';

export type NumberingScheme = 'SINGLE' | 'SEQUENTIAL' | 'ODD_EVEN' | 'EVEN_ODD';
export type VisualDirection = 'LTR' | 'RTL';
export interface PortBlockEditorState { name: string; rows: 1 | 2; portsPerRow: number; scheme: NumberingScheme; startingNumber: number; displayPrefix: string; direction: VisualDirection; kind: PortBlockKind; localIds: string[]; labelOverrides: Record<string, string>; }
export type PortBlockValidationError = 'nameRequired' | 'portsPerRow' | 'startingNumber' | 'displayPrefix' | 'localIds';
export interface GeneratedPortBlock { ports: PortBlockPort[]; validationErrors: PortBlockValidationError[]; }
export type IdFactory = () => string;
const defaultId: IdFactory = () => crypto.randomUUID();
const clean = (value: string) => value.trim();
export const requiredPortCount = (state: Pick<PortBlockEditorState, 'rows' | 'portsPerRow'>) => state.rows * state.portsPerRow;
export const ensureLocalIds = (localIds: string[], count: number, idFactory: IdFactory = defaultId) => [...localIds.slice(0, count), ...Array.from({ length: Math.max(0, count - localIds.length) }, () => `p-${idFactory()}`)];
export const newPortBlockEditorState = (idFactory: IdFactory = defaultId): PortBlockEditorState => ({ name: '', rows: 1, portsPerRow: 8, scheme: 'SINGLE', startingNumber: 1, displayPrefix: '', direction: 'LTR', kind: 'NETWORK_PORT', localIds: ensureLocalIds([], 8, idFactory), labelOverrides: {} });
export const hydratePortBlockEditorState = (version: PortBlockVersionDocument): PortBlockEditorState => { const ports = [...version.ports].sort((a, b) => a.layout_order - b.layout_order); const rows = ports.some((port) => port.row === 2) ? 2 : 1; const portsPerRow = Math.max(...ports.map((port) => port.column)); return { name: version.name, rows, portsPerRow, scheme: rows === 1 ? 'SINGLE' : 'SEQUENTIAL', startingNumber: 1, displayPrefix: '', direction: 'LTR', kind: ports[0].kind, localIds: ports.map((port) => port.local_id), labelOverrides: Object.fromEntries(ports.map((port) => [port.local_id, port.display_label])) }; };
const labelNumber = (state: PortBlockEditorState, row: number, index: number) => state.rows === 1 || state.scheme === 'SINGLE' ? state.startingNumber + index : state.scheme === 'SEQUENTIAL' ? state.startingNumber + (row - 1) * state.portsPerRow + index : state.scheme === 'ODD_EVEN' ? state.startingNumber + index * 2 + (row - 1) : state.startingNumber + index * 2 + (row === 1 ? 1 : 0);
export const generatePortBlock = (state: PortBlockEditorState): GeneratedPortBlock => { const validationErrors: PortBlockValidationError[] = []; if (!clean(state.name)) validationErrors.push('nameRequired'); if (!Number.isInteger(state.portsPerRow) || state.portsPerRow < 1) validationErrors.push('portsPerRow'); if (!Number.isInteger(state.startingNumber) || state.startingNumber < 0) validationErrors.push('startingNumber'); if (state.displayPrefix !== state.displayPrefix.trim()) validationErrors.push('displayPrefix'); const count = requiredPortCount(state); if (state.localIds.length !== count || new Set(state.localIds).size !== count || state.localIds.some((id) => !clean(id))) validationErrors.push('localIds'); const ports: PortBlockPort[] = []; for (let row = 1; row <= state.rows; row += 1) for (let index = 0; index < state.portsPerRow; index += 1) { const localId = state.localIds[(row - 1) * state.portsPerRow + index]; const generated = `${clean(state.displayPrefix)}${labelNumber(state, row, index)}`; ports.push({ local_id: localId, display_label: clean(state.labelOverrides[localId] ?? '') || generated, kind: state.kind, row: row as 1 | 2, column: state.direction === 'LTR' ? index + 1 : state.portsPerRow - index, layout_order: ports.length + 1 }); } return { ports, validationErrors }; };
export const createPortBlockRequest = (state: PortBlockEditorState): { request?: CreatePortBlockRequest; validationErrors: PortBlockValidationError[] } => { const generated = generatePortBlock(state); return generated.validationErrors.length ? { validationErrors: generated.validationErrors } : { request: { name: clean(state.name), ports: generated.ports }, validationErrors: [] }; };
