import { useRef, useState, type PointerEvent } from 'react';
import type { BlueprintFace, BlueprintInternalLink, BlueprintPortBlockPlacement } from '../topology/objectBlueprintTypes';
import { clampPlacement, fallbackPlacement, type BlueprintBlockInstance } from '../blueprints/editorModel';
import { compositionCanvas, placementRect, portCenter, screenToPlacementPoint } from '../blueprints/compositionGeometry';

interface Props { body: { width: number; height: number; fillColor: string }; face: BlueprintFace; instances: BlueprintBlockInstance[]; links: BlueprintInternalLink[]; selectedKey?: string; onSelect: (key: string) => void; onPlacement: (key: string, placement: BlueprintPortBlockPlacement) => void; }

export function BlueprintCompositionCanvas({ body, face, instances, links, selectedKey, onSelect, onPlacement }: Props) {
  const svg = useRef<SVGSVGElement>(null); const canvas = compositionCanvas(body);
  const [gesture, setGesture] = useState<{ key: string; mode: 'drag' | 'resize'; start: BlueprintPortBlockPlacement; pointer: { x: number; y: number } }>();
  const visible = instances.map((item, index) => ({ item, index })).filter(({ item }) => (item.face ?? 'FRONT') === face);
  const pointer = (event: PointerEvent<SVGElement>) => { const rect = svg.current!.getBoundingClientRect(); return screenToPlacementPoint(event.clientX, event.clientY, rect, canvas); };
  const update = (event: PointerEvent<SVGElement>) => { if (!gesture) return; const point = pointer(event); const dx = point.x - gesture.pointer.x; const dy = point.y - gesture.pointer.y; onPlacement(gesture.key, clampPlacement(gesture.mode === 'drag' ? { ...gesture.start, x: gesture.start.x + dx, y: gesture.start.y + dy } : { ...gesture.start, width: gesture.start.width + dx, height: gesture.start.height + dy })); };
  const points = new Map<string, { x: number; y: number }>();
  visible.forEach(({ item, index }) => { const placement = item.placement ?? fallbackPlacement(index); item.ports.forEach((port) => { const key = item.resolvedSlotKeys[port.local_id]; const point = portCenter(item, port.local_id, placement, canvas); if (key && point) points.set(key, point); }); });
  return <svg ref={svg} className="blueprint-composition-canvas" viewBox={`0 0 ${canvas.width} ${canvas.height}`} preserveAspectRatio="xMidYMid meet" role="img" aria-label={`Композиция: ${face === 'FRONT' ? 'передняя' : 'задняя'} панель`} onPointerMove={update} onPointerUp={() => setGesture(undefined)} onPointerCancel={() => setGesture(undefined)}>
    <rect className="blueprint-composition-canvas__body" width={canvas.width} height={canvas.height} fill={body.fillColor} />
    {links.map((link) => { const from = points.get(link.from_slot_key); const to = points.get(link.to_slot_key); return from && to ? <line key={`${link.from_slot_key}-${link.to_slot_key}`} className="blueprint-composition-canvas__link" x1={from.x} y1={from.y} x2={to.x} y2={to.y} /> : null; })}
    {visible.map(({ item, index }) => { const placement = item.placement ?? fallbackPlacement(index); const rect = placementRect(placement, canvas); const selected = item.instanceKey === selectedKey; const begin = (event: PointerEvent<SVGElement>, mode: 'drag' | 'resize') => { event.stopPropagation(); (event.currentTarget as SVGElement & { setPointerCapture?: (id: number) => void }).setPointerCapture?.(event.pointerId); onSelect(item.instanceKey); setGesture({ key: item.instanceKey, mode, start: placement, pointer: pointer(event) }); }; return <g key={item.instanceKey} data-instance-key={item.instanceKey} className={selected ? 'blueprint-composition-canvas__block is-selected' : 'blueprint-composition-canvas__block'} onPointerDown={(event) => begin(event, 'drag')}><rect x={rect.x} y={rect.y} width={rect.width} height={rect.height} rx="8" />{item.ports.map((port) => { const point = portCenter(item, port.local_id, placement, canvas)!; return <g key={port.local_id} className="blueprint-composition-canvas__port"><circle cx={point.x} cy={point.y} r="9" /><text x={point.x} y={point.y + 25}>{port.display_label}</text></g>; })}{selected && <rect data-resize-handle={item.instanceKey} className="blueprint-composition-canvas__resize" x={rect.x + rect.width - 13} y={rect.y + rect.height - 13} width="26" height="26" onPointerDown={(event) => begin(event, 'resize')} />}</g>; })}
  </svg>;
}
