import { useEffect, useState, type FormEvent } from 'react';
import type { CatalogInventoryDataSource, CatalogInventoryEquipmentItem } from '../topology/catalogInventoryTypes';
import type { PhysicalObjectL1TraceArtifact, PhysicalObjectL1TraceDataSource } from '../topology/physicalObjectL1TraceTypes';

interface TraceCommandBarProps { catalogInventoryDataSource?: CatalogInventoryDataSource; traceDataSource?: PhysicalObjectL1TraceDataSource; traceArtifact: PhysicalObjectL1TraceArtifact | null; selectedBranchId: string | null; onSelectedBranchId: (branchId: string | null) => void; onTraceArtifact: (artifact: PhysicalObjectL1TraceArtifact | null) => void; }
const warningText = (warning: Record<string, unknown>) => JSON.stringify(warning);
const sortedEquipment = (items: CatalogInventoryEquipmentItem[]) => [...items].sort((left, right) => left.label.localeCompare(right.label, undefined, { numeric: true, sensitivity: 'base' }));

export function TraceCommandBar({ catalogInventoryDataSource, traceDataSource, traceArtifact, selectedBranchId, onSelectedBranchId, onTraceArtifact }: TraceCommandBarProps) {
  const [equipment, setEquipment] = useState<CatalogInventoryEquipmentItem[] | null>(null);
  const [sourceId, setSourceId] = useState(''); const [destinationId, setDestinationId] = useState(''); const [message, setMessage] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { if (!catalogInventoryDataSource) return; let active = true; void Promise.resolve(catalogInventoryDataSource.loadCatalogInventory()).then((document) => active && document && setEquipment(sortedEquipment(document.equipment)), (reason) => active && setMessage(reason instanceof Error ? reason.message : 'Не удалось загрузить инвентарь оборудования.')); return () => { active = false; }; }, [catalogInventoryDataSource]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(null); if (!traceDataSource) { setMessage('L1 trace datasource пока недоступен.'); return; } if (!sourceId || !destinationId) { setMessage('Выберите PhysicalObject для «Откуда» и «Куда».'); return; } setLoading(true); onTraceArtifact(null); onSelectedBranchId(null); try { const artifact = await traceDataSource.tracePhysicalObjectsL1({ from_physical_object_id: sourceId, to_physical_object_id: destinationId }); onTraceArtifact(artifact); onSelectedBranchId(artifact.verdict === 'REACHABLE' ? artifact.branches[0]?.branch_id ?? null : null); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Не удалось выполнить L1 trace.'); } finally { setLoading(false); } };
  return <section className="trace-command" aria-label="L1 трассировка PhysicalObject"><form onSubmit={(event) => void submit(event)}><label>Откуда<select aria-label="Откуда" value={sourceId} onChange={(event) => setSourceId(event.target.value)} disabled={loading || !equipment}><option value="">Выберите PhysicalObject</option>{(equipment ?? []).map((item) => <option key={item.physical_object_ref.entity_id} value={item.physical_object_ref.entity_id}>{item.label}</option>)}</select></label><label>Куда<select aria-label="Куда" value={destinationId} onChange={(event) => setDestinationId(event.target.value)} disabled={loading || !equipment}><option value="">Выберите PhysicalObject</option>{(equipment ?? []).map((item) => <option key={item.physical_object_ref.entity_id} value={item.physical_object_ref.entity_id}>{item.label}</option>)}</select></label><span className="trace-command__level">Уровень: Physical / L1</span><button type="submit" disabled={loading || !equipment}>Трассировать</button></form>{message && <p className="trace-command__message" role="alert">{message}</p>}{traceArtifact && <div className={`trace-result trace-result--${traceArtifact.verdict.toLowerCase()}`} aria-label="Результат L1 trace"><strong>{traceArtifact.verdict === 'REACHABLE' ? 'Физический L1-путь доказан' : 'UNKNOWN: физический L1-путь не доказан'}</strong>{traceArtifact.verdict === 'REACHABLE' && <><span>Доказанных альтернатив: {traceArtifact.branches.length}</span>{traceArtifact.branches.length > 0 && <label>Показать альтернативу<select aria-label="Показать альтернативу" value={selectedBranchId ?? ''} onChange={(event) => onSelectedBranchId(event.target.value)}>{traceArtifact.branches.map((branch, index) => <option key={branch.branch_id} value={branch.branch_id}>Альтернатива {index + 1}</option>)}</select></label>}</>}{traceArtifact.cycles.length > 0 && <p>Обнаружены циклы: {traceArtifact.cycles.map((cycle) => cycle.cycle_id).join(', ')}</p>}{traceArtifact.gaps.length > 0 && <p>Gaps: {traceArtifact.gaps.map((gap) => gap.code).join(', ')}</p>}{traceArtifact.warnings.length > 0 && <p>Warnings: {traceArtifact.warnings.map(warningText).join('; ')}</p>}<button type="button" className="trace-result__clear" onClick={() => { onTraceArtifact(null); onSelectedBranchId(null); }}>Сбросить трассировку</button></div>}</section>;
}
