import { render, screen, waitFor } from '@testing-library/react';
import { useState } from 'react'; import userEvent from '@testing-library/user-event'; import { describe, expect, it, vi } from 'vitest';
import { TraceCommandBar } from './TraceCommandBar';
import type { PhysicalObjectL1TraceArtifact, PhysicalObjectL1TraceQuery } from '../topology/physicalObjectL1TraceTypes';
const one = '00000000-0000-0000-0000-000000000001'; const two = '00000000-0000-0000-0000-000000000002';
const inventory = { schema_version: '1.0' as const, equipment: [{ physical_object_ref: { ref_type: 'CANONICAL_FACT' as const, entity_type: 'PhysicalObject', entity_id: one }, label: 'PC1', map_memberships: [] }, { physical_object_ref: { ref_type: 'CANONICAL_FACT' as const, entity_type: 'PhysicalObject', entity_id: two }, label: 'PC2', map_memberships: [] }], cables: [], gaps: [], warnings: [] };
const artifact = (options: Partial<PhysicalObjectL1TraceArtifact> = {}): PhysicalObjectL1TraceArtifact => ({ schema_version: 1, query: { from_physical_object_id: one, to_physical_object_id: two }, verdict: 'REACHABLE', source_candidates: [], target_candidates: [], branches: [{ branch_id: 'a', source: { point_id: 'p1', member_index: 1 }, target: { point_id: 'p2', member_index: 1 }, edge_ids: [], evidence_refs: [] }, { branch_id: 'b', source: { point_id: 'p3', member_index: 1 }, target: { point_id: 'p4', member_index: 1 }, edge_ids: [], evidence_refs: [] }], cycles: [], nodes: [], edges: [], evidence_refs: [], gaps: [], warnings: [], ...options });
const Harness = ({ result, trace }: { result: PhysicalObjectL1TraceArtifact; trace: ReturnType<typeof vi.fn<(query: PhysicalObjectL1TraceQuery) => Promise<PhysicalObjectL1TraceArtifact>>> }) => { const [current, setCurrent] = useState<PhysicalObjectL1TraceArtifact | null>(null); const [selected, setSelected] = useState<string | null>(null); return <><output data-testid="selected">{selected}</output><TraceCommandBar catalogInventoryDataSource={{ loadCatalogInventory: vi.fn().mockResolvedValue(inventory) }} traceDataSource={{ tracePhysicalObjectsL1: trace.mockResolvedValue(result) }} traceArtifact={current} selectedBranchId={selected} onSelectedBranchId={setSelected} onTraceArtifact={setCurrent} /></>; };
const selectAndRun = async () => { await userEvent.selectOptions(await screen.findByLabelText('Откуда'), one); await userEvent.selectOptions(screen.getByLabelText('Куда'), two); await userEvent.click(screen.getByRole('button', { name: 'Трассировать' })); };
describe('TraceCommandBar', () => {
  it('posts PhysicalObject IDs from authoritative inventory without a NetworkInterface lookup', async () => { const trace = vi.fn<(query: PhysicalObjectL1TraceQuery) => Promise<PhysicalObjectL1TraceArtifact>>(); render(<Harness result={artifact()} trace={trace} />); await selectAndRun(); await waitFor(() => expect(trace).toHaveBeenCalledWith({ from_physical_object_id: one, to_physical_object_id: two })); expect(screen.queryByText(/интерфейс/i)).not.toBeInTheDocument(); });
  it('auto-selects the first reachable branch and keeps others as alternatives', async () => { const trace = vi.fn<(query: PhysicalObjectL1TraceQuery) => Promise<PhysicalObjectL1TraceArtifact>>(); render(<Harness result={artifact()} trace={trace} />); await selectAndRun(); expect(await screen.findByTestId('selected')).toHaveTextContent('a'); expect(screen.getByLabelText('Показать альтернативу')).toHaveTextContent('Альтернатива 1'); expect(screen.getByLabelText('Показать альтернативу')).toHaveTextContent('Альтернатива 2'); });
  it('changes the selected branch without another trace request', async () => { const trace = vi.fn<(query: PhysicalObjectL1TraceQuery) => Promise<PhysicalObjectL1TraceArtifact>>(); render(<Harness result={artifact()} trace={trace} />); await selectAndRun(); await userEvent.selectOptions(await screen.findByLabelText('Показать альтернативу'), 'b'); expect(screen.getByTestId('selected')).toHaveTextContent('b'); expect(trace).toHaveBeenCalledTimes(1); });
  it('presents UNKNOWN explicitly and shows cycles, gaps, and warnings', async () => { const trace = vi.fn<(query: PhysicalObjectL1TraceQuery) => Promise<PhysicalObjectL1TraceArtifact>>(); render(<Harness result={artifact({ verdict: 'UNKNOWN', branches: [], cycles: [{ cycle_id: 'cycle-1', state_node_ids: [], edge_ids: [], evidence_refs: [] }], gaps: [{ code: 'L1_TOPOLOGY_INCOMPLETE', evidence_refs: [] }], warnings: [{ code: 'STALE' }] })} trace={trace} />); await selectAndRun(); expect(await screen.findByText(/UNKNOWN:/)).toBeInTheDocument(); expect(screen.getByText('Обнаружены циклы: cycle-1')).toBeInTheDocument(); expect(screen.getByText('Gaps: L1_TOPOLOGY_INCOMPLETE')).toBeInTheDocument(); });
});
