import { useEffect, useState, type FormEvent } from 'react';
import type { CatalogInventoryDataSource, CatalogInventoryEquipmentItem } from '../topology/catalogInventoryTypes';
import type { ConnectionPointDetails, PhysicalObjectDetailsDataSource } from '../topology/physicalObjectDetailsTypes';
import type { PhysicalObjectL1TraceArtifact, PhysicalObjectL1TraceDataSource, PhysicalObjectL1TraceQuery } from '../topology/physicalObjectL1TraceTypes';

interface TraceCommandBarProps {
  catalogInventoryDataSource?: CatalogInventoryDataSource;
  physicalObjectDetailsDataSource?: PhysicalObjectDetailsDataSource;
  traceDataSource?: PhysicalObjectL1TraceDataSource;
  traceArtifact: PhysicalObjectL1TraceArtifact | null;
  selectedBranchId: string | null;
  onSelectedBranchId: (branchId: string | null) => void;
  onTraceArtifact: (artifact: PhysicalObjectL1TraceArtifact | null) => void;
}

interface EndpointPortState { objectId: string; ports: ConnectionPointDetails[]; error: string | null; }
const emptyPorts = (): EndpointPortState => ({ objectId: '', ports: [], error: null });
const warningText = (warning: Record<string, unknown>) => JSON.stringify(warning);
const sortedEquipment = (items: CatalogInventoryEquipmentItem[]) => [...items].sort((left, right) => left.label.localeCompare(right.label, undefined, { numeric: true, sensitivity: 'base' }));

function PortRefinement({ endpoint, objectId, state, selectedPortId, onSelect }: { endpoint: 'source' | 'destination'; objectId: string; state: EndpointPortState; selectedPortId: string; onSelect: (id: string) => void }) {
  const label = endpoint === 'source' ? 'Порт источника' : 'Порт назначения';
  return <label>{label}<select aria-label={label} value={selectedPortId} onChange={(event) => onSelect(event.target.value)} disabled={!objectId || state.objectId !== objectId}><option value="">Любой порт</option>{state.ports.map((port) => <option key={port.connection_point_ref.entity_id} value={port.connection_point_ref.entity_id}>{port.label}</option>)}</select>{state.error && <small className="trace-command__refinement-error">Не удалось загрузить порты: {state.error}. Можно трассировать с «Любой порт».</small>}</label>;
}

export function TraceCommandBar({ catalogInventoryDataSource, physicalObjectDetailsDataSource, traceDataSource, traceArtifact, selectedBranchId, onSelectedBranchId, onTraceArtifact }: TraceCommandBarProps) {
  const [equipment, setEquipment] = useState<CatalogInventoryEquipmentItem[] | null>(null);
  const [sourceId, setSourceId] = useState(''); const [destinationId, setDestinationId] = useState('');
  const [sourcePortId, setSourcePortId] = useState(''); const [destinationPortId, setDestinationPortId] = useState('');
  const [sourcePorts, setSourcePorts] = useState<EndpointPortState>(emptyPorts); const [destinationPorts, setDestinationPorts] = useState<EndpointPortState>(emptyPorts);
  const [message, setMessage] = useState<string | null>(null); const [loading, setLoading] = useState(false);

  useEffect(() => { if (!catalogInventoryDataSource) return; let active = true; void Promise.resolve(catalogInventoryDataSource.loadCatalogInventory()).then((document) => active && document && setEquipment(sortedEquipment(document.equipment)), (reason) => active && setMessage(reason instanceof Error ? reason.message : 'Не удалось загрузить инвентарь оборудования.')); return () => { active = false; }; }, [catalogInventoryDataSource]);
  useEffect(() => { if (!sourceId || !physicalObjectDetailsDataSource) { setSourcePorts(emptyPorts()); return; } let active = true; setSourcePorts({ objectId: sourceId, ports: [], error: null }); void physicalObjectDetailsDataSource.loadPhysicalObjectDetails(sourceId).then((document) => active && setSourcePorts({ objectId: sourceId, ports: document.connection_points, error: null }), (reason) => active && setSourcePorts({ objectId: sourceId, ports: [], error: reason instanceof Error ? reason.message : 'Ошибка загрузки' })); return () => { active = false; }; }, [physicalObjectDetailsDataSource, sourceId]);
  useEffect(() => { if (!destinationId || !physicalObjectDetailsDataSource) { setDestinationPorts(emptyPorts()); return; } let active = true; setDestinationPorts({ objectId: destinationId, ports: [], error: null }); void physicalObjectDetailsDataSource.loadPhysicalObjectDetails(destinationId).then((document) => active && setDestinationPorts({ objectId: destinationId, ports: document.connection_points, error: null }), (reason) => active && setDestinationPorts({ objectId: destinationId, ports: [], error: reason instanceof Error ? reason.message : 'Ошибка загрузки' })); return () => { active = false; }; }, [destinationId, physicalObjectDetailsDataSource]);
  const selectSource = (id: string) => { setSourceId(id); setSourcePortId(''); };
  const selectDestination = (id: string) => { setDestinationId(id); setDestinationPortId(''); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(null); if (!traceDataSource) { setMessage('L1 trace datasource пока недоступен.'); return; } if (!sourceId || !destinationId) { setMessage('Выберите PhysicalObject для «Откуда» и «Куда».'); return; } const query: PhysicalObjectL1TraceQuery = { from_physical_object_id: sourceId, to_physical_object_id: destinationId, ...(sourcePortId ? { from_connection_point_id: sourcePortId } : {}), ...(destinationPortId ? { to_connection_point_id: destinationPortId } : {}) }; setLoading(true); onTraceArtifact(null); onSelectedBranchId(null); try { const artifact = await traceDataSource.tracePhysicalObjectsL1(query); onTraceArtifact(artifact); onSelectedBranchId(artifact.verdict === 'REACHABLE' ? artifact.branches[0]?.branch_id ?? null : null); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Не удалось выполнить L1 trace.'); } finally { setLoading(false); } };
  return <section className="trace-command" aria-label="L1 трассировка PhysicalObject"><form onSubmit={(event) => void submit(event)}><label>Откуда<select aria-label="Откуда" value={sourceId} onChange={(event) => selectSource(event.target.value)} disabled={loading || !equipment}><option value="">Выберите PhysicalObject</option>{(equipment ?? []).map((item) => <option key={item.physical_object_ref.entity_id} value={item.physical_object_ref.entity_id}>{item.label}</option>)}</select></label><PortRefinement endpoint="source" objectId={sourceId} state={sourcePorts} selectedPortId={sourcePortId} onSelect={setSourcePortId} /><label>Куда<select aria-label="Куда" value={destinationId} onChange={(event) => selectDestination(event.target.value)} disabled={loading || !equipment}><option value="">Выберите PhysicalObject</option>{(equipment ?? []).map((item) => <option key={item.physical_object_ref.entity_id} value={item.physical_object_ref.entity_id}>{item.label}</option>)}</select></label><PortRefinement endpoint="destination" objectId={destinationId} state={destinationPorts} selectedPortId={destinationPortId} onSelect={setDestinationPortId} /><span className="trace-command__level">Уровень: Physical / L1</span><button type="submit" disabled={loading || !equipment}>Трассировать</button></form>{message && <p className="trace-command__message" role="alert">{message}</p>}{traceArtifact && <div className={`trace-result trace-result--${traceArtifact.verdict.toLowerCase()}`} aria-label="Результат L1 trace"><strong>{traceArtifact.verdict === 'REACHABLE' ? 'Физический L1-путь доказан' : 'UNKNOWN: физический L1-путь не доказан'}</strong>{traceArtifact.verdict === 'REACHABLE' && <><span>Доказанных альтернатив: {traceArtifact.branches.length}</span>{traceArtifact.branches.length > 0 && <label>Показать альтернативу<select aria-label="Показать альтернативу" value={selectedBranchId ?? ''} onChange={(event) => onSelectedBranchId(event.target.value)}>{traceArtifact.branches.map((branch, index) => <option key={branch.branch_id} value={branch.branch_id}>Альтернатива {index + 1}</option>)}</select></label>}</>}{traceArtifact.cycles.length > 0 && <p>Обнаружены циклы: {traceArtifact.cycles.map((cycle) => cycle.cycle_id).join(', ')}</p>}{traceArtifact.gaps.length > 0 && <p>Gaps: {traceArtifact.gaps.map((gap) => gap.code).join(', ')}</p>}{traceArtifact.warnings.length > 0 && <p>Warnings: {traceArtifact.warnings.map(warningText).join('; ')}</p>}<button type="button" className="trace-result__clear" onClick={() => { onTraceArtifact(null); onSelectedBranchId(null); }}>Сбросить трассировку</button></div>}</section>;
}
