"""current_schema_initialization

Revision ID: 0001
Revises:
Create Date: 2026-10-05 08:24:52.651826
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.CheckConstraint('char_length(btrim(name)) > 0', name=op.f('ck_base_templates_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_base_templates'))
    )
    op.create_table('cable_label_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('cable_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cable_label_history'))
    )
    op.create_index('ix_cable_label_history_cable_id', 'cable_label_history', ['cable_id'], unique=False)
    op.create_index('ix_cable_label_history_label', 'cable_label_history', ['label'], unique=False)
    op.create_table('cable_label_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_labels', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_cable_label_settings_cable_label_settings_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cable_label_settings'))
    )
    op.create_table('cable_label_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('start_at', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('char_length(btrim(name)) > 0', name=op.f('ck_cable_label_templates_cable_label_template_name_not_blank')),
    sa.CheckConstraint('char_length(btrim(pattern)) > 0', name=op.f('ck_cable_label_templates_cable_label_template_pattern_not_blank')),
    sa.CheckConstraint('start_at >= 0', name=op.f('ck_cable_label_templates_cable_label_template_start_at_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cable_label_templates'))
    )
    op.create_table('l2_forwarding_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_l2_forwarding_contexts'))
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('parent_location_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('char_length(btrim(name)) > 0', name=op.f('ck_locations_name_not_blank')),
    sa.CheckConstraint('parent_location_id IS NULL OR parent_location_id <> id', name=op.f('ck_locations_parent_not_self')),
    sa.CheckConstraint('type IS NULL OR char_length(btrim(type)) > 0', name=op.f('ck_locations_type_not_blank')),
    sa.ForeignKeyConstraint(['parent_location_id'], ['locations.id'], name=op.f('fk_locations_parent_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_index('ix_locations_parent_location_id', 'locations', ['parent_location_id'], unique=False)
    op.create_table('module_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.CheckConstraint('char_length(btrim(name)) > 0', name=op.f('ck_module_templates_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_templates'))
    )
    op.create_table('nat_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('default_transform', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('configured_completeness', sa.String(length=8), nullable=False),
    sa.CheckConstraint("configured_completeness IN ('COMPLETE', 'PARTIAL', 'UNKNOWN')", name=op.f('ck_nat_policies_configured_completeness_valid')),
    sa.CheckConstraint("jsonb_typeof(default_transform) = 'object'", name=op.f('ck_nat_policies_default_transform_object')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_policies'))
    )
    op.create_table('nat_pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('port_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("jsonb_typeof(address_ranges) = 'array'", name=op.f('ck_nat_pools_address_ranges_array')),
    sa.CheckConstraint("jsonb_typeof(port_ranges) = 'array'", name=op.f('ck_nat_pools_port_ranges_array')),
    sa.CheckConstraint('jsonb_array_length(address_ranges) + jsonb_array_length(port_ranges) > 0', name=op.f('ck_nat_pools_ranges_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_pools'))
    )
    op.create_table('network_interfaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_interfaces'))
    )
    op.create_table('packet_processing_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('configured_completeness', sa.String(length=8), nullable=False),
    sa.CheckConstraint("configured_completeness IN ('COMPLETE', 'PARTIAL', 'UNKNOWN')", name=op.f('ck_packet_processing_plans_configured_completeness_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packet_processing_plans'))
    )
    op.create_table('routing_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routing_contexts'))
    )
    op.create_table('routing_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('default_selection', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('configured_completeness', sa.String(length=8), nullable=False),
    sa.CheckConstraint("configured_completeness IN ('COMPLETE', 'PARTIAL', 'UNKNOWN')", name=op.f('ck_routing_policies_configured_completeness_valid')),
    sa.CheckConstraint("jsonb_typeof(default_selection) = 'object'", name=op.f('ck_routing_policies_default_selection_object')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routing_policies'))
    )
    op.create_table('saved_maps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(name)) > 0', name=op.f('ck_saved_maps_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_maps')),
    sa.UniqueConstraint('name', name='uq_saved_maps_name')
    )
    op.create_table('security_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('default_action', sa.String(length=6), nullable=False),
    sa.Column('configured_completeness', sa.String(length=8), nullable=False),
    sa.CheckConstraint("configured_completeness IN ('COMPLETE', 'PARTIAL', 'UNKNOWN')", name=op.f('ck_security_policies_configured_completeness_valid')),
    sa.CheckConstraint("default_action IN ('PERMIT', 'DROP', 'REJECT')", name=op.f('ck_security_policies_default_action_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_policies'))
    )
    op.create_table('base_template_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('default_physical_object_class', sa.String(length=255), nullable=True),
    sa.Column('body_kind', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('fill_color', sa.String(length=7), nullable=True),
    sa.CheckConstraint("body_kind = 'RECTANGLE'", name=op.f('ck_base_template_revisions_rectangle_only')),
    sa.CheckConstraint("fill_color IS NULL OR fill_color ~ '^#[0-9A-Fa-f]{6}$'", name=op.f('ck_base_template_revisions_fill_color_hex')),
    sa.CheckConstraint('height > 0', name=op.f('ck_base_template_revisions_height_positive')),
    sa.CheckConstraint('version_number >= 1', name=op.f('ck_base_template_revisions_version_number_positive')),
    sa.CheckConstraint('width > 0', name=op.f('ck_base_template_revisions_width_positive')),
    sa.ForeignKeyConstraint(['template_id'], ['base_templates.id'], name=op.f('fk_base_template_revisions_template_id_base_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_base_template_revisions')),
    sa.UniqueConstraint('template_id', 'version_number', name='uq_base_template_revisions_number')
    )
    op.create_table('l2_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interface_id', sa.UUID(), nullable=False),
    sa.Column('forwarding_context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['forwarding_context_id'], ['l2_forwarding_contexts.id'], name=op.f('fk_l2_bindings_forwarding_context_id_l2_forwarding_contexts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['interface_id'], ['network_interfaces.id'], name=op.f('fk_l2_bindings_interface_id_network_interfaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_l2_bindings')),
    sa.UniqueConstraint('interface_id', 'forwarding_context_id', name='uq_l2_bindings_interface_context')
    )
    op.create_index('ix_l2_bindings_context_id', 'l2_bindings', ['forwarding_context_id'], unique=False)
    op.create_index('ix_l2_bindings_interface_id', 'l2_bindings', ['interface_id'], unique=False)
    op.create_table('l3_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interface_id', sa.UUID(), nullable=False),
    sa.Column('routing_context_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['interface_id'], ['network_interfaces.id'], name=op.f('fk_l3_bindings_interface_id_network_interfaces'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['routing_context_id'], ['routing_contexts.id'], name=op.f('fk_l3_bindings_routing_context_id_routing_contexts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_l3_bindings')),
    sa.UniqueConstraint('interface_id', 'routing_context_id', name='uq_l3_bindings_interface_context')
    )
    op.create_index('ix_l3_bindings_context_id', 'l3_bindings', ['routing_context_id'], unique=False)
    op.create_index('ix_l3_bindings_interface_id', 'l3_bindings', ['interface_id'], unique=False)
    op.create_table('map_presentation_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.CheckConstraint('char_length(btrim(name)) > 0', name=op.f('ck_map_presentation_variants_name_not_blank')),
    sa.ForeignKeyConstraint(['map_id'], ['saved_maps.id'], name=op.f('fk_map_presentation_variants_map_id_saved_maps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_presentation_variants')),
    sa.UniqueConstraint('map_id', 'name', name='uq_map_presentation_variants_map_name')
    )
    op.create_table('map_text_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_color', sa.String(length=7), nullable=False),
    sa.Column('font_size', sa.Float(), nullable=False),
    sa.CheckConstraint("text_color ~ '^#[0-9A-Fa-f]{6}$'", name=op.f('ck_map_text_annotations_text_color_hex')),
    sa.CheckConstraint('char_length(btrim(text)) > 0', name=op.f('ck_map_text_annotations_text_not_blank')),
    sa.CheckConstraint('font_size > 0', name=op.f('ck_map_text_annotations_font_size_positive')),
    sa.ForeignKeyConstraint(['map_id'], ['saved_maps.id'], name=op.f('fk_map_text_annotations_map_id_saved_maps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_text_annotations'))
    )
    op.create_index('ix_map_text_annotations_map_id', 'map_text_annotations', ['map_id'], unique=False)
    op.create_table('module_template_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('compatibility', sa.String(length=255), nullable=False),
    sa.CheckConstraint('version_number > 0 AND char_length(btrim(compatibility)) > 0', name=op.f('ck_module_template_revisions_revision_valid')),
    sa.ForeignKeyConstraint(['template_id'], ['module_templates.id'], name=op.f('fk_module_template_revisions_template_id_module_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_template_revisions')),
    sa.UniqueConstraint('template_id', 'version_number', name=op.f('uq_module_template_revisions_template_id'))
    )
    op.create_table('nat_policy_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('local_stage_order', sa.Integer(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("jsonb_typeof(scope) = 'object'", name=op.f('ck_nat_policy_attachments_scope_object')),
    sa.ForeignKeyConstraint(['policy_id'], ['nat_policies.id'], name=op.f('fk_nat_policy_attachments_policy_id_nat_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_policy_attachments'))
    )
    op.create_index('ix_nat_policy_attachments_local_stage_order', 'nat_policy_attachments', ['local_stage_order'], unique=False)
    op.create_index('ix_nat_policy_attachments_policy_id', 'nat_policy_attachments', ['policy_id'], unique=False)
    op.create_table('nat_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('order_key', sa.Integer(), nullable=False),
    sa.Column('predicate', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transform', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("jsonb_typeof(predicate) = 'object'", name=op.f('ck_nat_rules_predicate_object')),
    sa.CheckConstraint("jsonb_typeof(transform) = 'object'", name=op.f('ck_nat_rules_transform_object')),
    sa.ForeignKeyConstraint(['policy_id'], ['nat_policies.id'], name=op.f('fk_nat_rules_policy_id_nat_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_rules')),
    sa.UniqueConstraint('policy_id', 'order_key', name='uq_nat_rules_policy_order')
    )
    op.create_index('ix_nat_rules_policy_id', 'nat_rules', ['policy_id'], unique=False)
    op.create_table('network_interface_realizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upper_interface_id', sa.UUID(), nullable=False),
    sa.Column('lower_interface_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('upper_interface_id <> lower_interface_id', name=op.f('ck_network_interface_realizations_distinct_interfaces')),
    sa.ForeignKeyConstraint(['lower_interface_id'], ['network_interfaces.id'], name=op.f('fk_network_interface_realizations_lower_interface_id_network_interfaces'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upper_interface_id'], ['network_interfaces.id'], name=op.f('fk_network_interface_realizations_upper_interface_id_network_interfaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_interface_realizations')),
    sa.UniqueConstraint('upper_interface_id', 'lower_interface_id', name='uq_interface_realization_upper_lower')
    )
    op.create_index('ix_interface_realizations_lower_id', 'network_interface_realizations', ['lower_interface_id'], unique=False)
    op.create_index('ix_interface_realizations_upper_id', 'network_interface_realizations', ['upper_interface_id'], unique=False)
    op.create_table('packet_processing_plan_attachment_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('routing_context_id', sa.UUID(), nullable=False),
    sa.Column('traffic_class', sa.String(length=12), nullable=False),
    sa.Column('configured_completeness', sa.String(length=8), nullable=False),
    sa.CheckConstraint("configured_completeness IN ('COMPLETE', 'PARTIAL', 'UNKNOWN')", name=op.f('ck_packet_processing_plan_attachment_sets_configured_completeness_valid')),
    sa.CheckConstraint("traffic_class IN ('TRANSIT', 'LOCAL_INPUT', 'LOCAL_OUTPUT')", name=op.f('ck_packet_processing_plan_attachment_sets_traffic_class_valid')),
    sa.ForeignKeyConstraint(['routing_context_id'], ['routing_contexts.id'], name=op.f('fk_packet_processing_plan_attachment_sets_routing_context_id_routing_contexts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packet_processing_plan_attachment_sets')),
    sa.UniqueConstraint('routing_context_id', 'traffic_class', name='uq_plan_attachment_sets_context_traffic_class')
    )
    op.create_index('ix_plan_attachment_sets_routing_context_id', 'packet_processing_plan_attachment_sets', ['routing_context_id'], unique=False)
    op.create_table('physical_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_physical_objects_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_physical_objects'))
    )
    op.create_index('ix_physical_objects_location_id', 'physical_objects', ['location_id'], unique=False)
    op.create_table('processing_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("jsonb_typeof(payload) = 'object'", name=op.f('ck_processing_stages_payload_object')),
    sa.ForeignKeyConstraint(['plan_id'], ['packet_processing_plans.id'], name=op.f('fk_processing_stages_plan_id_packet_processing_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_stages'))
    )
    op.create_index('ix_processing_stages_plan_id', 'processing_stages', ['plan_id'], unique=False)
    op.create_table('routing_policy_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('order_key', sa.Integer(), nullable=False),
    sa.Column('predicate', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("jsonb_typeof(action) = 'object'", name=op.f('ck_routing_policy_rules_action_object')),
    sa.CheckConstraint("jsonb_typeof(predicate) = 'object'", name=op.f('ck_routing_policy_rules_predicate_object')),
    sa.ForeignKeyConstraint(['policy_id'], ['routing_policies.id'], name=op.f('fk_routing_policy_rules_policy_id_routing_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routing_policy_rules')),
    sa.UniqueConstraint('policy_id', 'order_key', name='uq_routing_policy_rules_policy_order')
    )
    op.create_index('ix_routing_policy_rules_policy_id', 'routing_policy_rules', ['policy_id'], unique=False)
    op.create_table('routing_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('routing_context_id', sa.UUID(), nullable=False),
    sa.Column('address_family', sa.String(length=4), nullable=False),
    sa.Column('configured_completeness', sa.String(length=8), nullable=False),
    sa.CheckConstraint("address_family IN ('IPv4', 'IPv6')", name=op.f('ck_routing_tables_address_family_valid')),
    sa.CheckConstraint("configured_completeness IN ('COMPLETE', 'PARTIAL', 'UNKNOWN')", name=op.f('ck_routing_tables_configured_completeness_valid')),
    sa.ForeignKeyConstraint(['routing_context_id'], ['routing_contexts.id'], name=op.f('fk_routing_tables_routing_context_id_routing_contexts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routing_tables'))
    )
    op.create_index('ix_routing_tables_context_family', 'routing_tables', ['routing_context_id', 'address_family'], unique=False)
    op.create_index('ix_routing_tables_context_id', 'routing_tables', ['routing_context_id'], unique=False)
    op.create_table('security_policy_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("jsonb_typeof(scope) = 'object'", name=op.f('ck_security_policy_attachments_scope_object')),
    sa.ForeignKeyConstraint(['policy_id'], ['security_policies.id'], name=op.f('fk_security_policy_attachments_policy_id_security_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_policy_attachments'))
    )
    op.create_index('ix_security_policy_attachments_policy_id', 'security_policy_attachments', ['policy_id'], unique=False)
    op.create_index('ix_security_policy_attachments_stage_order', 'security_policy_attachments', ['stage_order'], unique=False)
    op.create_table('security_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('order_key', sa.Integer(), nullable=False),
    sa.Column('predicate', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', sa.String(length=6), nullable=False),
    sa.CheckConstraint("action IN ('PERMIT', 'DROP', 'REJECT')", name=op.f('ck_security_rules_action_valid')),
    sa.CheckConstraint("jsonb_typeof(predicate) = 'object'", name=op.f('ck_security_rules_predicate_object')),
    sa.ForeignKeyConstraint(['policy_id'], ['security_policies.id'], name=op.f('fk_security_rules_policy_id_security_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_rules')),
    sa.UniqueConstraint('policy_id', 'order_key', name='uq_security_rules_policy_order')
    )
    op.create_index('ix_security_rules_policy_id', 'security_rules', ['policy_id'], unique=False)
    op.create_table('connection_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('physical_object_id', sa.UUID(), nullable=False),
    sa.Column('cardinality', sa.Integer(), nullable=False),
    sa.CheckConstraint('cardinality >= 1', name=op.f('ck_connection_points_cardinality_positive')),
    sa.ForeignKeyConstraint(['physical_object_id'], ['physical_objects.id'], name=op.f('fk_connection_points_physical_object_id_physical_objects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection_points'))
    )
    op.create_index('ix_connection_points_physical_object_id', 'connection_points', ['physical_object_id'], unique=False)
    op.create_table('interface_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('l3_binding_id', sa.UUID(), nullable=False),
    sa.Column('address', postgresql.INET(), nullable=False),
    sa.Column('prefix_length', sa.Integer(), nullable=False),
    sa.CheckConstraint('(family(address) = 4 AND prefix_length BETWEEN 0 AND 32) OR (family(address) = 6 AND prefix_length BETWEEN 0 AND 128)', name=op.f('ck_interface_addresses_prefix_length_matches_family')),
    sa.ForeignKeyConstraint(['l3_binding_id'], ['l3_bindings.id'], name=op.f('fk_interface_addresses_l3_binding_id_l3_bindings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interface_addresses'))
    )
    op.create_index('ix_interface_addresses_address', 'interface_addresses', ['address'], unique=False)
    op.create_index('ix_interface_addresses_l3_binding_id', 'interface_addresses', ['l3_binding_id'], unique=False)
    op.create_table('l2_egress_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('binding_id', sa.UUID(), nullable=False),
    sa.Column('emit_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("jsonb_typeof(emit_stack) = 'array'", name=op.f('ck_l2_egress_rules_emit_stack_array')),
    sa.ForeignKeyConstraint(['binding_id'], ['l2_bindings.id'], name=op.f('fk_l2_egress_rules_binding_id_l2_bindings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_l2_egress_rules')),
    sa.UniqueConstraint('binding_id', name='uq_l2_egress_rules_binding')
    )
    op.create_table('l2_ingress_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('binding_id', sa.UUID(), nullable=False),
    sa.Column('exact_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("jsonb_typeof(exact_stack) = 'array'", name=op.f('ck_l2_ingress_rules_exact_stack_array')),
    sa.ForeignKeyConstraint(['binding_id'], ['l2_bindings.id'], name=op.f('fk_l2_ingress_rules_binding_id_l2_bindings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_l2_ingress_rules'))
    )
    op.create_index('ix_l2_ingress_rules_binding_id', 'l2_ingress_rules', ['binding_id'], unique=False)
    op.create_index('ix_l2_ingress_rules_exact_stack', 'l2_ingress_rules', ['exact_stack'], unique=False, postgresql_using='hash')
    op.create_table('map_location_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('collapsed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('visible_direct_elements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_map_location_states_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['map_presentation_variants.id'], name=op.f('fk_map_location_states_variant_id_map_presentation_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_location_states')),
    sa.UniqueConstraint('variant_id', 'location_id', name='uq_map_location_states_variant_location')
    )
    op.create_table('map_placements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('physical_object_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['saved_maps.id'], name=op.f('fk_map_placements_map_id_saved_maps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['physical_object_id'], ['physical_objects.id'], name=op.f('fk_map_placements_physical_object_id_physical_objects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_placements')),
    sa.UniqueConstraint('map_id', 'physical_object_id', name='uq_map_placements_map_object')
    )
    op.create_index('ix_map_placements_physical_object_id', 'map_placements', ['physical_object_id'], unique=False)
    op.create_table('module_endpoint_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_revision_id', sa.UUID(), nullable=False),
    sa.Column('definition_key', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.CheckConstraint("order_index >= 0 AND kind IN ('CONNECTION_POINT', 'NETWORK_PORT')", name=op.f('ck_module_endpoint_definitions_endpoint_valid')),
    sa.CheckConstraint('char_length(btrim(definition_key)) > 0 AND char_length(btrim(display_name)) > 0', name=op.f('ck_module_endpoint_definitions_endpoint_strings_not_blank')),
    sa.ForeignKeyConstraint(['module_revision_id'], ['module_template_revisions.id'], name=op.f('fk_module_endpoint_definitions_module_revision_id_module_template_revisions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_endpoint_definitions')),
    sa.UniqueConstraint('module_revision_id', 'definition_key', name='uq_module_endpoint_definition_key'),
    sa.UniqueConstraint('module_revision_id', 'order_index', name='uq_module_endpoint_definition_order')
    )
    op.create_table('network_interface_physical_owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interface_id', sa.UUID(), nullable=False),
    sa.Column('physical_object_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['interface_id'], ['network_interfaces.id'], name=op.f('fk_network_interface_physical_owners_interface_id_network_interfaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['physical_object_id'], ['physical_objects.id'], name=op.f('fk_network_interface_physical_owners_physical_object_id_physical_objects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_interface_physical_owners')),
    sa.UniqueConstraint('interface_id', name='uq_network_interface_physical_owners_interface')
    )
    op.create_index('ix_network_interface_physical_owners_physical_object_id', 'network_interface_physical_owners', ['physical_object_id'], unique=False)
    op.create_table('object_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_revision_id', sa.UUID(), nullable=False),
    sa.Column('physical_object_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['base_revision_id'], ['base_template_revisions.id'], name=op.f('fk_object_configurations_base_revision_id_base_template_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['physical_object_id'], ['physical_objects.id'], name=op.f('fk_object_configurations_physical_object_id_physical_objects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_object_configurations')),
    sa.UniqueConstraint('physical_object_id', name='uq_object_configurations_physical_object')
    )
    op.create_table('packet_processing_plan_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attachment_set_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("jsonb_typeof(scope) = 'object'", name=op.f('ck_packet_processing_plan_attachments_scope_object')),
    sa.ForeignKeyConstraint(['attachment_set_id'], ['packet_processing_plan_attachment_sets.id'], name=op.f('fk_packet_processing_plan_attachments_attachment_set_id_packet_processing_plan_attachment_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['packet_processing_plans.id'], name=op.f('fk_packet_processing_plan_attachments_plan_id_packet_processing_plans'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packet_processing_plan_attachments'))
    )
    op.create_index('ix_plan_attachments_attachment_set_id', 'packet_processing_plan_attachments', ['attachment_set_id'], unique=False)
    op.create_index('ix_plan_attachments_plan_id', 'packet_processing_plan_attachments', ['plan_id'], unique=False)
    op.create_table('presentation_panels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_revision_id', sa.UUID(), nullable=False),
    sa.Column('panel_key', sa.String(length=255), nullable=False),
    sa.Column('panel_number', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.CheckConstraint('char_length(btrim(panel_key)) > 0', name=op.f('ck_presentation_panels_panel_key_not_blank')),
    sa.CheckConstraint('panel_number > 0', name=op.f('ck_presentation_panels_panel_number_positive')),
    sa.CheckConstraint('width > 0 AND height > 0', name=op.f('ck_presentation_panels_size_positive')),
    sa.ForeignKeyConstraint(['base_revision_id'], ['base_template_revisions.id'], name=op.f('fk_presentation_panels_base_revision_id_base_template_revisions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_presentation_panels')),
    sa.UniqueConstraint('base_revision_id', 'panel_key', name='uq_presentation_panels_version_key'),
    sa.UniqueConstraint('base_revision_id', 'panel_number', name='uq_presentation_panels_version_number')
    )
    op.create_table('processing_entry_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('traffic_class', sa.String(length=12), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['packet_processing_plans.id'], name=op.f('fk_processing_entry_points_plan_id_packet_processing_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['processing_stages.id'], name=op.f('fk_processing_entry_points_stage_id_processing_stages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_entry_points')),
    sa.UniqueConstraint('plan_id', 'traffic_class', name='uq_processing_entry_points_plan_traffic_class')
    )
    op.create_index('ix_processing_entry_points_plan_id', 'processing_entry_points', ['plan_id'], unique=False)
    op.create_index('ix_processing_entry_points_stage_id', 'processing_entry_points', ['stage_id'], unique=False)
    op.create_table('processing_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('from_stage_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('to_stage_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['from_stage_id'], ['processing_stages.id'], name=op.f('fk_processing_transitions_from_stage_id_processing_stages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['packet_processing_plans.id'], name=op.f('fk_processing_transitions_plan_id_packet_processing_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_stage_id'], ['processing_stages.id'], name=op.f('fk_processing_transitions_to_stage_id_processing_stages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_transitions')),
    sa.UniqueConstraint('from_stage_id', 'outcome', name='uq_processing_transitions_stage_outcome')
    )
    op.create_index('ix_processing_transitions_from_stage_id', 'processing_transitions', ['from_stage_id'], unique=False)
    op.create_index('ix_processing_transitions_plan_id', 'processing_transitions', ['plan_id'], unique=False)
    op.create_index('ix_processing_transitions_to_stage_id', 'processing_transitions', ['to_stage_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('routing_table_id', sa.UUID(), nullable=False),
    sa.Column('destination_prefix', postgresql.CIDR(), nullable=False),
    sa.Column('disposition', sa.String(length=7), nullable=False),
    sa.CheckConstraint("disposition IN ('FORWARD', 'LOCAL', 'DISCARD')", name=op.f('ck_routes_disposition_valid')),
    sa.ForeignKeyConstraint(['routing_table_id'], ['routing_tables.id'], name=op.f('fk_routes_routing_table_id_routing_tables'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.create_index('ix_routes_destination_prefix', 'routes', ['destination_prefix'], unique=False)
    op.create_index('ix_routes_table_id', 'routes', ['routing_table_id'], unique=False)
    op.create_table('built_in_endpoint_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_revision_id', sa.UUID(), nullable=False),
    sa.Column('slot_key', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('panel_key', sa.String(length=255), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.CheckConstraint("kind IN ('CONNECTION_POINT', 'NETWORK_PORT')", name=op.f('ck_built_in_endpoint_definitions_kind_supported')),
    sa.CheckConstraint('char_length(btrim(display_name)) > 0', name=op.f('ck_built_in_endpoint_definitions_display_name_not_blank')),
    sa.CheckConstraint('char_length(btrim(slot_key)) > 0', name=op.f('ck_built_in_endpoint_definitions_slot_key_not_blank')),
    sa.CheckConstraint('position_x >= 0 AND position_x <= 1 AND position_y >= 0 AND position_y <= 1', name=op.f('ck_built_in_endpoint_definitions_position_bounds')),
    sa.ForeignKeyConstraint(['base_revision_id', 'panel_key'], ['presentation_panels.base_revision_id', 'presentation_panels.panel_key'], name='fk_built_in_endpoint_definitions_panel_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['base_revision_id'], ['base_template_revisions.id'], name=op.f('fk_built_in_endpoint_definitions_base_revision_id_base_template_revisions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_built_in_endpoint_definitions')),
    sa.UniqueConstraint('base_revision_id', 'slot_key', name='uq_built_in_endpoint_definitions_key')
    )
    op.create_table('connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('point_a_id', sa.UUID(), nullable=False),
    sa.Column('point_b_id', sa.UUID(), nullable=False),
    sa.Column('cardinality', sa.Integer(), nullable=False),
    sa.CheckConstraint('cardinality >= 1', name=op.f('ck_connections_cardinality_positive')),
    sa.CheckConstraint('point_a_id <> point_b_id', name=op.f('ck_connections_distinct_points')),
    sa.ForeignKeyConstraint(['point_a_id'], ['connection_points.id'], name=op.f('fk_connections_point_a_id_connection_points'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['point_b_id'], ['connection_points.id'], name=op.f('fk_connections_point_b_id_connection_points'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connections'))
    )
    op.create_index('ix_connections_point_a_id', 'connections', ['point_a_id'], unique=False)
    op.create_index('ix_connections_point_b_id', 'connections', ['point_b_id'], unique=False)
    op.create_table('entity_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('physical_object_id', sa.UUID(), nullable=True),
    sa.Column('network_interface_id', sa.UUID(), nullable=True),
    sa.Column('connection_point_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.CheckConstraint("key = 'alias.display' OR (key = 'class' AND physical_object_id IS NOT NULL)", name=op.f('ck_entity_metadata_supported_key_target')),
    sa.CheckConstraint('char_length(btrim(value)) > 0', name=op.f('ck_entity_metadata_value_not_blank')),
    sa.CheckConstraint('num_nonnulls(physical_object_id, network_interface_id, connection_point_id) = 1', name=op.f('ck_entity_metadata_exactly_one_entity')),
    sa.ForeignKeyConstraint(['connection_point_id'], ['connection_points.id'], name=op.f('fk_entity_metadata_connection_point_id_connection_points'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['network_interface_id'], ['network_interfaces.id'], name=op.f('fk_entity_metadata_network_interface_id_network_interfaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['physical_object_id'], ['physical_objects.id'], name=op.f('fk_entity_metadata_physical_object_id_physical_objects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_metadata')),
    sa.UniqueConstraint('connection_point_id', 'key', name='uq_entity_metadata_connection_point_key'),
    sa.UniqueConstraint('network_interface_id', 'key', name='uq_entity_metadata_network_interface_key'),
    sa.UniqueConstraint('physical_object_id', 'key', name='uq_entity_metadata_physical_object_key')
    )
    op.create_table('interface_physical_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interface_id', sa.UUID(), nullable=False),
    sa.Column('point_id', sa.UUID(), nullable=False),
    sa.Column('point_member', sa.Integer(), nullable=False),
    sa.CheckConstraint('point_member >= 1', name=op.f('ck_interface_physical_bindings_point_member_positive')),
    sa.ForeignKeyConstraint(['interface_id'], ['network_interfaces.id'], name=op.f('fk_interface_physical_bindings_interface_id_network_interfaces'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['point_id'], ['connection_points.id'], name=op.f('fk_interface_physical_bindings_point_id_connection_points'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interface_physical_bindings')),
    sa.UniqueConstraint('point_id', 'point_member', name='uq_physical_binding_point_member')
    )
    op.create_index('ix_physical_bindings_interface_id', 'interface_physical_bindings', ['interface_id'], unique=False)
    op.create_table('map_view_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('placement_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('view_key', sa.String(length=32), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_width', sa.Float(), nullable=True),
    sa.CheckConstraint("display_width IS NULL OR (view_key = 'L1/PHYSICAL_OBJECT' AND display_width > 0)", name=op.f('ck_map_view_positions_map_view_positions_display_width_physical_positive')),
    sa.CheckConstraint("view_key IN ('L1/PHYSICAL_OBJECT', 'L2/DEVICE')", name=op.f('ck_map_view_positions_map_view_positions_view_key_valid')),
    sa.ForeignKeyConstraint(['placement_id'], ['map_placements.id'], name=op.f('fk_map_view_positions_placement_id_map_placements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['map_presentation_variants.id'], name=op.f('fk_map_view_positions_variant_id_map_presentation_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_view_positions')),
    sa.UniqueConstraint('placement_id', 'variant_id', 'view_key', name='uq_map_view_positions_placement_variant_view')
    )
    op.create_table('module_bays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_revision_id', sa.UUID(), nullable=False),
    sa.Column('bay_key', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('compatibility', sa.String(length=255), nullable=False),
    sa.Column('panel_key', sa.String(length=255), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.CheckConstraint('char_length(btrim(bay_key)) > 0 AND char_length(btrim(display_name)) > 0 AND char_length(btrim(compatibility)) > 0', name=op.f('ck_module_bays_bay_strings_not_blank')),
    sa.CheckConstraint('x >= 0 AND y >= 0 AND width > 0 AND height > 0 AND x + width <= 1 AND y + height <= 1', name=op.f('ck_module_bays_rectangle_inside_panel')),
    sa.ForeignKeyConstraint(['base_revision_id', 'panel_key'], ['presentation_panels.base_revision_id', 'presentation_panels.panel_key'], name=op.f('fk_module_bays_base_revision_id_presentation_panels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['base_revision_id'], ['base_template_revisions.id'], name=op.f('fk_module_bays_base_revision_id_base_template_revisions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_bays')),
    sa.UniqueConstraint('base_revision_id', 'bay_key', name=op.f('uq_module_bays_base_revision_id'))
    )
    op.create_table('module_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('configuration_id', sa.UUID(), nullable=False),
    sa.Column('module_revision_id', sa.UUID(), nullable=False),
    sa.Column('bay_key', sa.String(length=255), nullable=False),
    sa.Column('orientation', sa.String(length=16), nullable=False),
    sa.CheckConstraint("orientation IN ('HORIZONTAL', 'VERTICAL')", name=op.f('ck_module_installations_orientation_valid')),
    sa.ForeignKeyConstraint(['configuration_id'], ['object_configurations.id'], name=op.f('fk_module_installations_configuration_id_object_configurations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['module_revision_id'], ['module_template_revisions.id'], name=op.f('fk_module_installations_module_revision_id_module_template_revisions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_installations')),
    sa.UniqueConstraint('configuration_id', 'bay_key', name=op.f('uq_module_installations_configuration_id'))
    )
    op.create_table('route_next_hops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('gateway_address', postgresql.INET(), nullable=True),
    sa.Column('egress_l3_binding_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('gateway_address IS NOT NULL OR egress_l3_binding_id IS NOT NULL', name=op.f('ck_route_next_hops_gateway_or_egress_required')),
    sa.ForeignKeyConstraint(['egress_l3_binding_id'], ['l3_bindings.id'], name=op.f('fk_route_next_hops_egress_l3_binding_id_l3_bindings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_next_hops_route_id_routes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_next_hops'))
    )
    op.create_index('ix_route_next_hops_egress_binding_id', 'route_next_hops', ['egress_l3_binding_id'], unique=False)
    op.create_index('ix_route_next_hops_route_id', 'route_next_hops', ['route_id'], unique=False)
    op.create_table('base_internal_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_revision_id', sa.UUID(), nullable=False),
    sa.Column('slot_a_id', sa.UUID(), nullable=False),
    sa.Column('slot_b_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('slot_a_id <> slot_b_id', name=op.f('ck_base_internal_links_distinct_slots')),
    sa.ForeignKeyConstraint(['base_revision_id'], ['base_template_revisions.id'], name=op.f('fk_base_internal_links_base_revision_id_base_template_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_a_id'], ['built_in_endpoint_definitions.id'], name=op.f('fk_base_internal_links_slot_a_id_built_in_endpoint_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_b_id'], ['built_in_endpoint_definitions.id'], name=op.f('fk_base_internal_links_slot_b_id_built_in_endpoint_definitions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_base_internal_links')),
    sa.UniqueConstraint('base_revision_id', 'slot_a_id', 'slot_b_id', name='uq_base_internal_links_unordered')
    )
    op.create_table('built_in_endpoint_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('configuration_id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('connection_point_id', sa.UUID(), nullable=False),
    sa.Column('network_interface_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['object_configurations.id'], name=op.f('fk_built_in_endpoint_mappings_configuration_id_object_configurations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['connection_point_id'], ['connection_points.id'], name=op.f('fk_built_in_endpoint_mappings_connection_point_id_connection_points'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['definition_id'], ['built_in_endpoint_definitions.id'], name=op.f('fk_built_in_endpoint_mappings_definition_id_built_in_endpoint_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['network_interface_id'], ['network_interfaces.id'], name=op.f('fk_built_in_endpoint_mappings_network_interface_id_network_interfaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_built_in_endpoint_mappings')),
    sa.UniqueConstraint('configuration_id', 'definition_id', name='uq_built_in_endpoint_mappings_slot'),
    sa.UniqueConstraint('connection_point_id', name='uq_built_in_endpoint_mappings_connection_point'),
    sa.UniqueConstraint('network_interface_id', name='uq_built_in_endpoint_mappings_network_interface')
    )
    op.create_table('cables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_cables_connection_id_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cables')),
    sa.UniqueConstraint('connection_id', name='uq_cables_connection')
    )
    op.create_index('ix_cables_connection_id', 'cables', ['connection_id'], unique=False)
    op.create_table('connection_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('point_a_member', sa.Integer(), nullable=False),
    sa.Column('point_b_member', sa.Integer(), nullable=False),
    sa.CheckConstraint('index >= 1', name=op.f('ck_connection_members_index_positive')),
    sa.CheckConstraint('point_a_member >= 1', name=op.f('ck_connection_members_a_positive')),
    sa.CheckConstraint('point_b_member >= 1', name=op.f('ck_connection_members_b_positive')),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_connection_members_connection_id_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection_members')),
    sa.UniqueConstraint('connection_id', 'index', name='uq_connection_members_index'),
    sa.UniqueConstraint('connection_id', 'point_a_member', name='uq_connection_members_a'),
    sa.UniqueConstraint('connection_id', 'point_b_member', name='uq_connection_members_b')
    )
    op.create_index('ix_connection_members_a_member', 'connection_members', ['point_a_member'], unique=False)
    op.create_index('ix_connection_members_b_member', 'connection_members', ['point_b_member'], unique=False)
    op.create_index('ix_connection_members_connection_id', 'connection_members', ['connection_id'], unique=False)
    op.create_table('module_endpoint_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('connection_point_id', sa.UUID(), nullable=False),
    sa.Column('network_interface_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['connection_point_id'], ['connection_points.id'], name=op.f('fk_module_endpoint_mappings_connection_point_id_connection_points'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['definition_id'], ['module_endpoint_definitions.id'], name=op.f('fk_module_endpoint_mappings_definition_id_module_endpoint_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['installation_id'], ['module_installations.id'], name=op.f('fk_module_endpoint_mappings_installation_id_module_installations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['network_interface_id'], ['network_interfaces.id'], name=op.f('fk_module_endpoint_mappings_network_interface_id_network_interfaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_endpoint_mappings')),
    sa.UniqueConstraint('connection_point_id', name=op.f('uq_module_endpoint_mappings_connection_point_id')),
    sa.UniqueConstraint('installation_id', 'definition_id', name=op.f('uq_module_endpoint_mappings_installation_id')),
    sa.UniqueConstraint('network_interface_id', name=op.f('uq_module_endpoint_mappings_network_interface_id'))
    )
    op.create_table('map_cable_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('cable_id', sa.UUID(), nullable=False),
    sa.Column('view_key', sa.String(length=32), nullable=False),
    sa.Column('waypoints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("view_key = 'L1/PHYSICAL_OBJECT'", name=op.f('ck_map_cable_routes_map_cable_routes_view_key_physical_only')),
    sa.ForeignKeyConstraint(['cable_id'], ['cables.id'], name=op.f('fk_map_cable_routes_cable_id_cables'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['saved_maps.id'], name=op.f('fk_map_cable_routes_map_id_saved_maps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['map_presentation_variants.id'], name=op.f('fk_map_cable_routes_variant_id_map_presentation_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_cable_routes')),
    sa.UniqueConstraint('variant_id', 'cable_id', 'view_key', name='uq_map_cable_routes_variant_cable_view')
    )
    op.create_index('ix_map_cable_routes_cable_id', 'map_cable_routes', ['cable_id'], unique=False)
    op.execute("INSERT INTO cable_label_settings (id, unique_labels) VALUES (1, false)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_map_cable_routes_cable_id', table_name='map_cable_routes')
    op.drop_table('map_cable_routes')
    op.drop_table('module_endpoint_mappings')
    op.drop_index('ix_connection_members_connection_id', table_name='connection_members')
    op.drop_index('ix_connection_members_b_member', table_name='connection_members')
    op.drop_index('ix_connection_members_a_member', table_name='connection_members')
    op.drop_table('connection_members')
    op.drop_index('ix_cables_connection_id', table_name='cables')
    op.drop_table('cables')
    op.drop_table('built_in_endpoint_mappings')
    op.drop_table('base_internal_links')
    op.drop_index('ix_route_next_hops_route_id', table_name='route_next_hops')
    op.drop_index('ix_route_next_hops_egress_binding_id', table_name='route_next_hops')
    op.drop_table('route_next_hops')
    op.drop_table('module_installations')
    op.drop_table('module_bays')
    op.drop_table('map_view_positions')
    op.drop_index('ix_physical_bindings_interface_id', table_name='interface_physical_bindings')
    op.drop_table('interface_physical_bindings')
    op.drop_table('entity_metadata')
    op.drop_index('ix_connections_point_b_id', table_name='connections')
    op.drop_index('ix_connections_point_a_id', table_name='connections')
    op.drop_table('connections')
    op.drop_table('built_in_endpoint_definitions')
    op.drop_index('ix_routes_table_id', table_name='routes')
    op.drop_index('ix_routes_destination_prefix', table_name='routes')
    op.drop_table('routes')
    op.drop_index('ix_processing_transitions_to_stage_id', table_name='processing_transitions')
    op.drop_index('ix_processing_transitions_plan_id', table_name='processing_transitions')
    op.drop_index('ix_processing_transitions_from_stage_id', table_name='processing_transitions')
    op.drop_table('processing_transitions')
    op.drop_index('ix_processing_entry_points_stage_id', table_name='processing_entry_points')
    op.drop_index('ix_processing_entry_points_plan_id', table_name='processing_entry_points')
    op.drop_table('processing_entry_points')
    op.drop_table('presentation_panels')
    op.drop_index('ix_plan_attachments_plan_id', table_name='packet_processing_plan_attachments')
    op.drop_index('ix_plan_attachments_attachment_set_id', table_name='packet_processing_plan_attachments')
    op.drop_table('packet_processing_plan_attachments')
    op.drop_table('object_configurations')
    op.drop_index('ix_network_interface_physical_owners_physical_object_id', table_name='network_interface_physical_owners')
    op.drop_table('network_interface_physical_owners')
    op.drop_table('module_endpoint_definitions')
    op.drop_index('ix_map_placements_physical_object_id', table_name='map_placements')
    op.drop_table('map_placements')
    op.drop_table('map_location_states')
    op.drop_index('ix_l2_ingress_rules_exact_stack', table_name='l2_ingress_rules', postgresql_using='hash')
    op.drop_index('ix_l2_ingress_rules_binding_id', table_name='l2_ingress_rules')
    op.drop_table('l2_ingress_rules')
    op.drop_table('l2_egress_rules')
    op.drop_index('ix_interface_addresses_l3_binding_id', table_name='interface_addresses')
    op.drop_index('ix_interface_addresses_address', table_name='interface_addresses')
    op.drop_table('interface_addresses')
    op.drop_index('ix_connection_points_physical_object_id', table_name='connection_points')
    op.drop_table('connection_points')
    op.drop_index('ix_security_rules_policy_id', table_name='security_rules')
    op.drop_table('security_rules')
    op.drop_index('ix_security_policy_attachments_stage_order', table_name='security_policy_attachments')
    op.drop_index('ix_security_policy_attachments_policy_id', table_name='security_policy_attachments')
    op.drop_table('security_policy_attachments')
    op.drop_index('ix_routing_tables_context_id', table_name='routing_tables')
    op.drop_index('ix_routing_tables_context_family', table_name='routing_tables')
    op.drop_table('routing_tables')
    op.drop_index('ix_routing_policy_rules_policy_id', table_name='routing_policy_rules')
    op.drop_table('routing_policy_rules')
    op.drop_index('ix_processing_stages_plan_id', table_name='processing_stages')
    op.drop_table('processing_stages')
    op.drop_index('ix_physical_objects_location_id', table_name='physical_objects')
    op.drop_table('physical_objects')
    op.drop_index('ix_plan_attachment_sets_routing_context_id', table_name='packet_processing_plan_attachment_sets')
    op.drop_table('packet_processing_plan_attachment_sets')
    op.drop_index('ix_interface_realizations_upper_id', table_name='network_interface_realizations')
    op.drop_index('ix_interface_realizations_lower_id', table_name='network_interface_realizations')
    op.drop_table('network_interface_realizations')
    op.drop_index('ix_nat_rules_policy_id', table_name='nat_rules')
    op.drop_table('nat_rules')
    op.drop_index('ix_nat_policy_attachments_policy_id', table_name='nat_policy_attachments')
    op.drop_index('ix_nat_policy_attachments_local_stage_order', table_name='nat_policy_attachments')
    op.drop_table('nat_policy_attachments')
    op.drop_table('module_template_revisions')
    op.drop_index('ix_map_text_annotations_map_id', table_name='map_text_annotations')
    op.drop_table('map_text_annotations')
    op.drop_table('map_presentation_variants')
    op.drop_index('ix_l3_bindings_interface_id', table_name='l3_bindings')
    op.drop_index('ix_l3_bindings_context_id', table_name='l3_bindings')
    op.drop_table('l3_bindings')
    op.drop_index('ix_l2_bindings_interface_id', table_name='l2_bindings')
    op.drop_index('ix_l2_bindings_context_id', table_name='l2_bindings')
    op.drop_table('l2_bindings')
    op.drop_table('base_template_revisions')
    op.drop_table('security_policies')
    op.drop_table('saved_maps')
    op.drop_table('routing_policies')
    op.drop_table('routing_contexts')
    op.drop_table('packet_processing_plans')
    op.drop_table('network_interfaces')
    op.drop_table('nat_pools')
    op.drop_table('nat_policies')
    op.drop_table('module_templates')
    op.drop_index('ix_locations_parent_location_id', table_name='locations')
    op.drop_table('locations')
    op.drop_table('l2_forwarding_contexts')
    op.drop_table('cable_label_templates')
    op.drop_table('cable_label_settings')
    op.drop_index('ix_cable_label_history_label', table_name='cable_label_history')
    op.drop_index('ix_cable_label_history_cable_id', table_name='cable_label_history')
    op.drop_table('cable_label_history')
    op.drop_table('base_templates')
    # ### end Alembic commands ###
