import type { CableLabelDataSource, CableLabelSettings, CableLabelTemplate, CableLabelTemplateListDocument, CableLabelTemplateWrite } from './cableLabelTypes';
import { historicalCableLabelError } from './historicalCableLabelReuse';

const root = '/api/v1';
const object = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const fail = (message: string): never => { throw new Error(`Malformed Cable label response: ${message}`); };
const template = (value: unknown): CableLabelTemplate => { const item = object(value) ? value : fail('invalid template.'); if (typeof item.id !== 'string' || typeof item.name !== 'string' || typeof item.pattern !== 'string' || !Number.isInteger(item.start_at) || (item.description !== undefined && item.description !== null && typeof item.description !== 'string')) fail('invalid template.'); return { id: item.id as string, name: item.name as string, description: item.description as string | null | undefined, pattern: item.pattern as string, start_at: item.start_at as number }; };
const error = async (response: Response): Promise<Error> => { try { return historicalCableLabelError(await response.json()); } catch { return new Error(`HTTP ${response.status}`); } };

export class ApiCableLabelDataSource implements CableLabelDataSource {
  async setCableLabel(cableId: string, label: string | null, confirmedHistoricalLabel?: string | null): Promise<void> { const response = await fetch(`${root}/cables/${encodeURIComponent(cableId)}/label`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ label, confirmed_historical_label: confirmedHistoricalLabel ?? null }) }); if (!response.ok) throw await error(response); }
  async generateCableLabel(cableId: string, templateId: string, confirmedHistoricalLabel?: string | null): Promise<void> { const response = await fetch(`${root}/cables/${encodeURIComponent(cableId)}/generated-label`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ template_id: templateId, confirmed_historical_label: confirmedHistoricalLabel ?? null }) }); if (!response.ok) throw await error(response); }
  async loadCableLabelSettings(): Promise<CableLabelSettings> { const response = await fetch(`${root}/cable-label-settings`); if (!response.ok) throw await error(response); const body: unknown = await response.json(); const item = object(body) ? body : fail('invalid settings.'); if (typeof item.unique_labels !== 'boolean') fail('invalid settings.'); return { unique_labels: item.unique_labels as boolean }; }
  async setCableLabelSettings(settings: CableLabelSettings): Promise<CableLabelSettings> { const response = await fetch(`${root}/cable-label-settings`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(settings) }); if (!response.ok) throw await error(response); const body: unknown = await response.json(); const item = object(body) ? body : fail('invalid settings.'); if (typeof item.unique_labels !== 'boolean') fail('invalid settings.'); return { unique_labels: item.unique_labels as boolean }; }
  async loadCableLabelTemplates(): Promise<CableLabelTemplateListDocument> { const response = await fetch(`${root}/cable-label-templates`); if (!response.ok) throw await error(response); const body: unknown = await response.json(); const item = object(body) ? body : fail('invalid list.'); if (item.schema_version !== '1.0' || !Array.isArray(item.templates)) fail('invalid list.'); return { schema_version: '1.0', templates: (item.templates as unknown[]).map(template) }; }
  async createCableLabelTemplate(value: CableLabelTemplateWrite): Promise<CableLabelTemplate> { return this.write(`${root}/cable-label-templates`, 'POST', value); }
  async updateCableLabelTemplate(id: string, value: CableLabelTemplateWrite): Promise<CableLabelTemplate> { return this.write(`${root}/cable-label-templates/${encodeURIComponent(id)}`, 'PUT', value); }
  async deleteCableLabelTemplate(id: string): Promise<void> { const response = await fetch(`${root}/cable-label-templates/${encodeURIComponent(id)}`, { method: 'DELETE' }); if (!response.ok) throw await error(response); }
  private async write(url: string, method: string, value: CableLabelTemplateWrite): Promise<CableLabelTemplate> { const response = await fetch(url, { method, headers: { 'content-type': 'application/json' }, body: JSON.stringify(value) }); if (!response.ok) throw await error(response); return template(await response.json()); }
}
