import type { CreatePortBlockRequest, CreatePortBlockVersionRequest, PortBlockCreationDocument, PortBlockDataSource, PortBlockKind, PortBlockListDocument, PortBlockPort, PortBlockRef, PortBlockVersionDocument, PortBlockVersionListDocument, PortBlockVersionRef } from './portBlockTypes';

const DEFAULT_ENDPOINT = '/api/v1/library/port-blocks';
const isObject = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const malformed = (message: string): never => { throw new Error(`Malformed port block response: ${message}`); };
const object = (value: unknown, path: string) => isObject(value) ? value : malformed(`${path} must be an object.`);
const string = (value: unknown, path: string) => typeof value === 'string' && value ? value : malformed(`${path} must be a non-empty string.`);
const positive = (value: unknown, path: string) => typeof value === 'number' && Number.isInteger(value) && value >= 1 ? value : malformed(`${path} must be a positive integer.`);
const ref = <T extends 'PortBlock' | 'PortBlockVersion'>(value: unknown, path: string, entityType: T): T extends 'PortBlock' ? PortBlockRef : PortBlockVersionRef => { const item = object(value, path); if (item.ref_type !== 'LIBRARY_RECORD' || item.entity_type !== entityType) malformed(`${path} is not a ${entityType} library ref.`); return { ref_type: 'LIBRARY_RECORD', entity_type: entityType, entity_id: string(item.entity_id, `${path}.entity_id`) } as T extends 'PortBlock' ? PortBlockRef : PortBlockVersionRef; };
const port = (value: unknown, path: string): PortBlockPort => { const item = object(value, path); if (item.kind !== 'CONNECTION_POINT' && item.kind !== 'NETWORK_PORT') malformed(`${path}.kind is unsupported.`); const row = positive(item.row, `${path}.row`); if (row > 2) malformed(`${path}.row is unsupported.`); return { local_id: string(item.local_id, `${path}.local_id`), display_label: string(item.display_label, `${path}.display_label`), kind: item.kind as PortBlockKind, row: row as 1 | 2, column: positive(item.column, `${path}.column`), layout_order: positive(item.layout_order, `${path}.layout_order`) }; };
const creation = (value: unknown): PortBlockCreationDocument => { const item = object(value, 'document'); if (item.schema_version !== '1.0') malformed('document.schema_version must be 1.0.'); return { schema_version: '1.0', port_block_ref: ref(item.port_block_ref, 'document.port_block_ref', 'PortBlock'), version_ref: ref(item.version_ref, 'document.version_ref', 'PortBlockVersion') }; };
const error = async (response: Response): Promise<Error> => { try { const body: unknown = await response.json(); if (isObject(body) && isObject(body.error) && typeof body.error.message === 'string') return new Error(body.error.message); } catch { /* fall through */ } return new Error(`HTTP ${response.status} while loading port blocks.`); };

export class PortBlockDeletionConflictError extends Error {
  constructor() {
    super('PortBlock is used by an ObjectBlueprint.');
    this.name = 'PortBlockDeletionConflictError';
  }
}

export class ApiPortBlockDataSource implements PortBlockDataSource {
  constructor(private readonly endpoint = DEFAULT_ENDPOINT) {}
  async loadPortBlocks(): Promise<PortBlockListDocument> { const response = await fetch(this.endpoint); if (!response.ok) throw await error(response); const document: unknown = await response.json(); const item = object(document, 'document'); if (item.schema_version !== '1.0' || !Array.isArray(item.port_blocks)) malformed('document must contain port_blocks.'); const entries = item.port_blocks as unknown[]; return { schema_version: '1.0', port_blocks: entries.map((entry, index) => { const value = object(entry, `port_blocks[${index}]`); return { port_block_ref: ref(value.port_block_ref, `port_blocks[${index}].port_block_ref`, 'PortBlock'), name: string(value.name, `port_blocks[${index}].name`), version_ref: ref(value.version_ref, `port_blocks[${index}].version_ref`, 'PortBlockVersion'), version_number: positive(value.version_number, `port_blocks[${index}].version_number`), port_count: positive(value.port_count, `port_blocks[${index}].port_count`), version_count: positive(value.version_count, `port_blocks[${index}].version_count`) }; }) }; }
  async loadPortBlockVersions(portBlockId: string): Promise<PortBlockVersionListDocument> { const response=await fetch(`${this.endpoint}/${encodeURIComponent(portBlockId)}/versions`); if(!response.ok) throw await error(response); const item=object(await response.json(),'document'); if(item.schema_version!=='1.0'||!Array.isArray(item.versions)) malformed('document must contain versions.'); return {schema_version:'1.0',versions:(item.versions as unknown[]).map((entry,index)=>{const value=object(entry,`versions[${index}]`);return {port_block_ref:ref(value.port_block_ref,`versions[${index}].port_block_ref`,'PortBlock'),version_ref:ref(value.version_ref,`versions[${index}].version_ref`,'PortBlockVersion'),version_number:positive(value.version_number,`versions[${index}].version_number`),port_count:positive(value.port_count,`versions[${index}].port_count`)};})}; }
  async loadPortBlockVersion(portBlockId: string, versionId: string): Promise<PortBlockVersionDocument> { const response = await fetch(`${this.endpoint}/${encodeURIComponent(portBlockId)}/versions/${encodeURIComponent(versionId)}`); if (!response.ok) throw await error(response); const document: unknown = await response.json(); const item = object(document, 'document'); if (item.schema_version !== '1.0' || !Array.isArray(item.ports)) malformed('version document must contain ports.'); const entries = item.ports as unknown[]; return { schema_version: '1.0', port_block_ref: ref(item.port_block_ref, 'port_block_ref', 'PortBlock'), name: string(item.name, 'name'), version_ref: ref(item.version_ref, 'version_ref', 'PortBlockVersion'), version_number: positive(item.version_number, 'version_number'), ports: entries.map((entry, index) => port(entry, `ports[${index}]`)) }; }
  async createPortBlock(request: CreatePortBlockRequest): Promise<PortBlockCreationDocument> { return this.write(this.endpoint, request); }
  async createPortBlockVersion(portBlockId: string, request: CreatePortBlockVersionRequest): Promise<PortBlockCreationDocument> { return this.write(`${this.endpoint}/${encodeURIComponent(portBlockId)}/versions`, request); }
  async deletePortBlock(portBlockId: string): Promise<void> { const response = await fetch(`${this.endpoint}/${encodeURIComponent(portBlockId)}`, { method: 'DELETE' }); if (response.ok) return; try { const body: unknown = await response.json(); const envelope = isObject(body) && isObject(body.error) ? body.error : null; if (envelope && isObject(envelope.details) && envelope.details.reason === 'PORT_BLOCK_IN_USE_BY_OBJECT_BLUEPRINT') throw new PortBlockDeletionConflictError(); if (envelope && typeof envelope.message === 'string') throw new Error(envelope.message); } catch (reason) { if (reason instanceof PortBlockDeletionConflictError || reason instanceof Error) throw reason; } throw new Error(`HTTP ${response.status} while deleting port blocks.`); }
  private async write(url: string, body: unknown): Promise<PortBlockCreationDocument> { const response = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw await error(response); return creation(await response.json()); }
}
