import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { ApiSavedMapDataSource } from './apiSavedMapDataSource';

const mapId = '00000000-0000-4000-8000-000000000001';
const objectId = '00000000-0000-4000-8000-000000000002';
const body = { map_ref: { entity_type: 'SavedMap', entity_id: mapId }, name: 'First', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z', placements: [{ physical_object_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: objectId }, positions: { 'L1/PHYSICAL_OBJECT': { x: 12, y: 34, locked: false } } }], cable_routes: [] };
const response = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status, headers: { 'Content-Type': 'application/json' } });

describe('ApiSavedMapDataSource', () => {
  const fetchMock = vi.fn();
  beforeEach(() => { fetchMock.mockReset(); vi.stubGlobal('fetch', fetchMock); }); afterEach(() => vi.unstubAllGlobals());
  it('parses list, create and detail responses strictly', async () => { fetchMock.mockResolvedValueOnce(response({ maps: [body] })).mockResolvedValueOnce(response(body)).mockResolvedValueOnce(response(body)); const source = new ApiSavedMapDataSource(); await expect(source.listMaps()).resolves.toHaveLength(1); await expect(source.createMap('First')).resolves.toMatchObject({ name: 'First' }); await expect(source.loadMap(mapId)).resolves.toMatchObject({ placements: [{ positions: { 'L1/PHYSICAL_OBJECT': { x: 12, y: 34, locked: false } } }] }); });
  it('deletes an exact canonical SavedMap UUID', async () => { fetchMock.mockResolvedValue(response({})); await new ApiSavedMapDataSource().deleteMap(mapId); expect(fetchMock).toHaveBeenCalledWith(`/api/v1/maps/${mapId}`, { method: 'DELETE' }); await expect(new ApiSavedMapDataSource().deleteMap('not-a-uuid')).rejects.toThrow('mapId must be a UUID'); });
  it('uses public placement, per-view position and lock paths and bodies', async () => { fetchMock.mockResolvedValue(response({})); const source = new ApiSavedMapDataSource(); await source.addPlacement(mapId, objectId, 1, 2, 96); await source.movePosition(mapId, objectId, 'physical', 3, 4); await source.movePosition(mapId, objectId, 'logical', 5, 6); await source.setPositionLock(mapId, objectId, 'physical', true); await source.removePlacement(mapId, objectId); expect(fetchMock.mock.calls.map(([url, init]) => [url, init ? [(init as RequestInit).method, (init as RequestInit).body] : ['DELETE', undefined]])).toEqual([[`/api/v1/maps/${mapId}/placements`, ['POST', JSON.stringify({ physical_object_id: objectId, x: 1, y: 2, display_width: 96 })]], [`/api/v1/maps/${mapId}/placements/${objectId}/positions/physical`, ['PUT', JSON.stringify({ x: 3, y: 4 })]], [`/api/v1/maps/${mapId}/placements/${objectId}/positions/logical`, ['PUT', JSON.stringify({ x: 5, y: 6 })]], [`/api/v1/maps/${mapId}/placements/${objectId}/locks/physical`, ['PUT', JSON.stringify({ locked: true })]], [`/api/v1/maps/${mapId}/placements/${objectId}`, ['DELETE', undefined]]]); });
  it('round-trips optional physical display width and rejects malformed widths', async () => { fetchMock.mockResolvedValue(response({ ...body, placements: [{ ...body.placements[0], positions: { 'L1/PHYSICAL_OBJECT': { x: 12, y: 34, locked: false, display_width: 320 } } }] })); const source = new ApiSavedMapDataSource(); await expect(source.loadMap(mapId)).resolves.toMatchObject({ placements: [{ positions: { 'L1/PHYSICAL_OBJECT': { display_width: 320 } } }] }); await source.movePosition(mapId, objectId, 'physical', 3, 4, 320); expect(fetchMock.mock.calls[1][1].body).toBe(JSON.stringify({ x: 3, y: 4, display_width: 320 })); fetchMock.mockResolvedValue(response({ ...body, placements: [{ ...body.placements[0], positions: { 'L1/PHYSICAL_OBJECT': { x: 12, y: 34, locked: false, display_width: 0 } } }] })); await expect(source.loadMap(mapId)).rejects.toThrow('display_width'); });
  it('parses authoritative reads, preserves a zero-waypoint route, and treats a successful route PUT as acknowledgement only', async () => { const routed = { ...body, cable_routes: [{ cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: objectId }, view: 'L1/PHYSICAL_OBJECT', waypoints: [{ x: 20, y: 10 }, { x: -4, y: 8 }, { x: 0, y: 0 }] }, { cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: '00000000-0000-4000-8000-000000000003' }, view: 'L1/PHYSICAL_OBJECT', waypoints: [] }] }; fetchMock.mockResolvedValueOnce(response(routed)).mockResolvedValueOnce(new Response('not a SavedMap document', { status: 200 })).mockResolvedValueOnce(response({})); const source = new ApiSavedMapDataSource(); await expect(source.loadMap(mapId)).resolves.toMatchObject({ cable_routes: routed.cable_routes }); await expect(source.setCableRoute(mapId, objectId, [])).resolves.toBeUndefined(); await source.deleteCableRoute(mapId, objectId); expect(fetchMock.mock.calls.slice(1).map(([url, init]) => [url, (init as RequestInit).method, (init as RequestInit).body])).toEqual([[`/api/v1/maps/${mapId}/cable-routes/${objectId}`, 'PUT', JSON.stringify({ view: 'physical', waypoints: [] })], [`/api/v1/maps/${mapId}/cable-routes/${objectId}`, 'DELETE', undefined]]); });
  it.each([{ ...body, map_ref: { entity_type: 'SavedMap', entity_id: 'bad' } }, { ...body, placements: [{ ...body.placements[0], physical_object_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Connection', entity_id: objectId } }] }, { ...body, placements: [{ ...body.placements[0], positions: { 'L1/PHYSICAL_OBJECT': { x: Infinity, y: 1 } } }] }, { ...body, placements: [{ ...body.placements[0], positions: { unknown: { x: 1, y: 2 } } }] }, { ...body, placements: {} }, { ...body, cable_routes: [{ cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Connection', entity_id: objectId }, view: 'L1/PHYSICAL_OBJECT', waypoints: [] }] }, { ...body, cable_routes: [{ cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: objectId }, view: 'L2/DEVICE', waypoints: [] }] }, { ...body, cable_routes: [{ cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: objectId }, view: 'L1/PHYSICAL_OBJECT', waypoints: {} }] }, { ...body, cable_routes: [{ cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: objectId }, view: 'L1/PHYSICAL_OBJECT', waypoints: [{ x: Infinity, y: 1 }] }] }])('rejects malformed response', async (invalid) => { fetchMock.mockResolvedValue(response(invalid)); await expect(new ApiSavedMapDataSource().loadMap(mapId)).rejects.toThrow('Malformed SavedMap'); });
  it('exposes API errors', async () => { fetchMock.mockResolvedValue(response({ error: { code: 'MODEL_ERROR', message: 'Conflict' } }, 409)); await expect(new ApiSavedMapDataSource().listMaps()).rejects.toThrow('MODEL_ERROR: Conflict'); });
});
