import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { ApiSavedMapDataSource } from './apiSavedMapDataSource';

const mapId = '00000000-0000-4000-8000-000000000001';
const objectId = '00000000-0000-4000-8000-000000000002';
const regionWrite = { label: 'Zone', points: [{ x: 0, y: 0 }, { x: 20, y: 0 }, { x: 0, y: 20 }], label_position: { x: 3, y: 4 }, style: { fill_color: '#123456', fill_opacity: 0.3, stroke_color: '#abcdef', stroke_width: 2, stroke_style: 'dashed' as const, label_color: '#fedcba' }, z_order: 4 };
const region = { region_ref: { entity_type: 'MapRegion' as const, entity_id: '00000000-0000-4000-8000-000000000003' }, ...regionWrite };
const annotationWrite = { text: 'Line one\nLine two', position: { x: 3, y: 4 }, text_color: '#123456', font_size: 18 };
const annotation = { annotation_ref: { entity_type: 'MapTextAnnotation' as const, entity_id: '00000000-0000-4000-8000-000000000004' }, ...annotationWrite };
const variantId = '00000000-0000-4000-8000-000000000005';
const body = { map_ref: { entity_type: 'SavedMap', entity_id: mapId }, name: 'First', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z', active_variant_ref: { entity_type: 'MapPresentationVariant', entity_id: variantId }, variants: [{ variant_ref: { entity_type: 'MapPresentationVariant', entity_id: variantId }, name: 'Основной' }], placements: [{ physical_object_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: objectId }, positions: { 'L1/PHYSICAL_OBJECT': { x: 12, y: 34, locked: false } } }], cable_routes: [], composites: [], regions: [region], text_annotations: [annotation] };
const response = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status, headers: { 'Content-Type': 'application/json' } });

describe('ApiSavedMapDataSource', () => {
  const fetchMock = vi.fn();
  beforeEach(() => { fetchMock.mockReset(); vi.stubGlobal('fetch', fetchMock); }); afterEach(() => vi.unstubAllGlobals());
  it('parses list, create and detail responses strictly', async () => { fetchMock.mockResolvedValueOnce(response({ maps: [body] })).mockResolvedValueOnce(response(body)).mockResolvedValueOnce(response(body)); const source = new ApiSavedMapDataSource(); await expect(source.listMaps()).resolves.toHaveLength(1); await expect(source.createMap('First')).resolves.toMatchObject({ name: 'First' }); await expect(source.loadMap(mapId)).resolves.toMatchObject({ placements: [{ positions: { 'L1/PHYSICAL_OBJECT': { x: 12, y: 34, locked: false } } }] }); });
  it('deletes an exact canonical SavedMap UUID', async () => { fetchMock.mockResolvedValue(response({})); await new ApiSavedMapDataSource().deleteMap(mapId); expect(fetchMock).toHaveBeenCalledWith(`/api/v1/maps/${mapId}`, { method: 'DELETE' }); await expect(new ApiSavedMapDataSource().deleteMap('not-a-uuid')).rejects.toThrow('mapId must be a UUID'); });
  it('deletes an exact presentation variant UUID on its SavedMap', async () => { fetchMock.mockResolvedValue(response({})); const source = new ApiSavedMapDataSource(); await source.deletePresentationVariant(mapId, variantId); expect(fetchMock).toHaveBeenCalledWith(`/api/v1/maps/${mapId}/presentation-variants/${variantId}`, { method: 'DELETE' }); await expect(source.deletePresentationVariant('not-a-uuid', variantId)).rejects.toThrow('mapId must be a UUID'); await expect(source.deletePresentationVariant(mapId, 'not-a-uuid')).rejects.toThrow('variantId must be a UUID'); });
  it('parses bounded creation documents for layout copies and composites', async () => { const compositeId = '00000000-0000-4000-8000-000000000006'; const composite = { composite_ref: { entity_type: 'MapComposite', entity_id: compositeId }, name: 'Pair', physical_object_refs: [{ ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: objectId }], presentation: { variant_ref: { entity_type: 'MapPresentationVariant', entity_id: variantId }, collapsed: false, x: 0, y: 0, width: 280, height: 180 } }; fetchMock.mockResolvedValueOnce(response({ variant_ref: { entity_type: 'MapPresentationVariant', entity_id: variantId }, name: 'Copy' })).mockResolvedValueOnce(response(composite)); const source = new ApiSavedMapDataSource(); await expect(source.createPresentationVariant(mapId, 'Copy', variantId)).resolves.toMatchObject({ name: 'Copy' }); await expect(source.createComposite(mapId, 'Pair', [objectId], variantId)).resolves.toMatchObject({ composite_ref: { entity_id: compositeId } }); expect(fetchMock).toHaveBeenNthCalledWith(1, `/api/v1/maps/${mapId}/presentation-variants`, expect.objectContaining({ method: 'POST', body: JSON.stringify({ name: 'Copy', source_variant_id: variantId }) })); });
  it.each([{ name: 'Copy' }, { variant_ref: { entity_type: 'MapPresentationVariant', entity_id: variantId }, name: '' }, { composite_ref: { entity_type: 'MapComposite', entity_id: objectId }, name: 'Pair', physical_object_refs: [], presentation: { variant_ref: { entity_type: 'MapPresentationVariant', entity_id: variantId }, collapsed: 'false', x: 0, y: 0, width: 280, height: 180 } }])('rejects malformed bounded creation response', async (invalid) => { fetchMock.mockResolvedValue(response(invalid)); const source = new ApiSavedMapDataSource(); if ('composite_ref' in invalid) await expect(source.createComposite(mapId, 'Pair', [objectId], variantId)).rejects.toThrow('Malformed SavedMap'); else await expect(source.createPresentationVariant(mapId, 'Copy', variantId)).rejects.toThrow('Malformed SavedMap'); });
  it('uses public placement, per-view position and lock paths and bodies', async () => { fetchMock.mockResolvedValue(response({})); const source = new ApiSavedMapDataSource(); await source.addPlacement(mapId, objectId, 1, 2, 96); await source.movePosition(mapId, objectId, 'physical', 3, 4); await source.movePosition(mapId, objectId, 'logical', 5, 6); await source.setPositionLock(mapId, objectId, 'physical', true); await source.removePlacement(mapId, objectId); expect(fetchMock.mock.calls.map(([url, init]) => [url, init ? [(init as RequestInit).method, (init as RequestInit).body] : ['DELETE', undefined]])).toEqual([[`/api/v1/maps/${mapId}/placements`, ['POST', JSON.stringify({ physical_object_id: objectId, x: 1, y: 2, display_width: 96 })]], [`/api/v1/maps/${mapId}/placements/${objectId}/positions/physical`, ['PUT', JSON.stringify({ x: 3, y: 4 })]], [`/api/v1/maps/${mapId}/placements/${objectId}/positions/logical`, ['PUT', JSON.stringify({ x: 5, y: 6 })]], [`/api/v1/maps/${mapId}/placements/${objectId}/locks/physical`, ['PUT', JSON.stringify({ locked: true })]], [`/api/v1/maps/${mapId}/placements/${objectId}`, ['DELETE', undefined]]]); });
  it('round-trips optional physical display width and rejects malformed widths', async () => { fetchMock.mockResolvedValue(response({ ...body, placements: [{ ...body.placements[0], positions: { 'L1/PHYSICAL_OBJECT': { x: 12, y: 34, locked: false, display_width: 320 } } }] })); const source = new ApiSavedMapDataSource(); await expect(source.loadMap(mapId)).resolves.toMatchObject({ placements: [{ positions: { 'L1/PHYSICAL_OBJECT': { display_width: 320 } } }] }); await source.movePosition(mapId, objectId, 'physical', 3, 4, 320); expect(fetchMock.mock.calls[1][1].body).toBe(JSON.stringify({ x: 3, y: 4, display_width: 320 })); fetchMock.mockResolvedValue(response({ ...body, placements: [{ ...body.placements[0], positions: { 'L1/PHYSICAL_OBJECT': { x: 12, y: 34, locked: false, display_width: 0 } } }] })); await expect(source.loadMap(mapId)).rejects.toThrow('display_width'); });
  it('parses authoritative reads, preserves a zero-waypoint route, and treats a successful route PUT as acknowledgement only', async () => { const routed = { ...body, cable_routes: [{ cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: objectId }, view: 'L1/PHYSICAL_OBJECT', waypoints: [{ x: 20, y: 10 }, { x: -4, y: 8 }, { x: 0, y: 0 }] }, { cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: '00000000-0000-4000-8000-000000000003' }, view: 'L1/PHYSICAL_OBJECT', waypoints: [] }] }; fetchMock.mockResolvedValueOnce(response(routed)).mockResolvedValueOnce(new Response('not a SavedMap document', { status: 200 })).mockResolvedValueOnce(response({})); const source = new ApiSavedMapDataSource(); await expect(source.loadMap(mapId)).resolves.toMatchObject({ cable_routes: routed.cable_routes, regions: [region] }); await expect(source.setCableRoute(mapId, objectId, [])).resolves.toBeUndefined(); await source.deleteCableRoute(mapId, objectId); expect(fetchMock.mock.calls.slice(1).map(([url, init]) => [url, (init as RequestInit).method, (init as RequestInit).body])).toEqual([[`/api/v1/maps/${mapId}/cable-routes/${objectId}`, 'PUT', JSON.stringify({ view: 'physical', waypoints: [] })], [`/api/v1/maps/${mapId}/cable-routes/${objectId}`, 'DELETE', undefined]]); });
  it('transports region writes as acknowledgements and reloads regions only through SavedMap reads', async () => { fetchMock.mockResolvedValue(response({})); const source = new ApiSavedMapDataSource(); const replacement = { ...regionWrite, label: 'Other', label_position: null }; await source.createRegion(mapId, regionWrite); await source.replaceRegion(mapId, region.region_ref.entity_id, replacement); await source.deleteRegion(mapId, region.region_ref.entity_id); expect(fetchMock.mock.calls.map(([url, init]) => [url, (init as RequestInit).method, (init as RequestInit).body])).toEqual([[`/api/v1/maps/${mapId}/regions`, 'POST', JSON.stringify(regionWrite)], [`/api/v1/maps/${mapId}/regions/${region.region_ref.entity_id}`, 'PUT', JSON.stringify(replacement)], [`/api/v1/maps/${mapId}/regions/${region.region_ref.entity_id}`, 'DELETE', undefined]]); });
  it('parses and transports text annotation presentation only through SavedMap reads', async () => { fetchMock.mockResolvedValue(response({})); const source = new ApiSavedMapDataSource(); const replacement = { ...annotationWrite, text: 'Other', position: { x: 8, y: 9 } }; await source.createTextAnnotation(mapId, annotationWrite); await source.replaceTextAnnotation(mapId, annotation.annotation_ref.entity_id, replacement); await source.deleteTextAnnotation(mapId, annotation.annotation_ref.entity_id); expect(fetchMock.mock.calls.map(([url, init]) => [url, (init as RequestInit).method, (init as RequestInit).body])).toEqual([[`/api/v1/maps/${mapId}/text-annotations`, 'POST', JSON.stringify(annotationWrite)], [`/api/v1/maps/${mapId}/text-annotations/${annotation.annotation_ref.entity_id}`, 'PUT', JSON.stringify(replacement)], [`/api/v1/maps/${mapId}/text-annotations/${annotation.annotation_ref.entity_id}`, 'DELETE', undefined]]); });
  it.each([{ ...body, map_ref: { entity_type: 'SavedMap', entity_id: 'bad' } }, { ...body, placements: [{ ...body.placements[0], physical_object_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Connection', entity_id: objectId } }] }, { ...body, placements: [{ ...body.placements[0], positions: { 'L1/PHYSICAL_OBJECT': { x: Infinity, y: 1 } } }] }, { ...body, placements: [{ ...body.placements[0], positions: { unknown: { x: 1, y: 2 } } }] }, { ...body, placements: {} }, { ...body, cable_routes: [{ cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Connection', entity_id: objectId }, view: 'L1/PHYSICAL_OBJECT', waypoints: [] }] }, { ...body, cable_routes: [{ cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: objectId }, view: 'L2/DEVICE', waypoints: [] }] }, { ...body, cable_routes: [{ cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: objectId }, view: 'L1/PHYSICAL_OBJECT', waypoints: {} }] }, { ...body, cable_routes: [{ cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: objectId }, view: 'L1/PHYSICAL_OBJECT', waypoints: [{ x: Infinity, y: 1 }] }] }, { ...body, regions: [{ ...region, region_ref: { entity_type: 'SavedMap', entity_id: region.region_ref.entity_id } }] }, { ...body, regions: [{ ...region, points: [{ x: 0, y: 0 }] }] }, { ...body, regions: [{ ...region, style: { ...region.style, stroke_style: 'double' } }] }])('rejects malformed response', async (invalid) => { fetchMock.mockResolvedValue(response(invalid)); await expect(new ApiSavedMapDataSource().loadMap(mapId)).rejects.toThrow('Malformed SavedMap'); });
  it('exposes API errors', async () => { fetchMock.mockResolvedValue(response({ error: { code: 'MODEL_ERROR', message: 'Conflict' } }, 409)); await expect(new ApiSavedMapDataSource().listMaps()).rejects.toThrow('MODEL_ERROR: Conflict'); });
});
