import type { MapCableRoute, MapCableRouteWaypoint, MapPlacement, MapRegion, MapRegionPoint, MapRegionRef, MapRegionStyle, MapRegionWrite, MapTextAnnotation, MapTextAnnotationRef, MapTextAnnotationWrite, MapViewPosition, SavedMap, SavedMapDataSource, SavedMapRef, SavedMapSummary, SavedMapView, SavedMapViewKey } from './savedMapTypes';
import type { ProjectionSourceRef } from './types';

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const malformed = (message: string): never => { throw new Error(`Malformed SavedMap response: ${message}`); };
const object = (value: unknown, path: string): Record<string, unknown> => { if (!value || typeof value !== 'object' || Array.isArray(value)) malformed(`${path} must be an object.`); return value as Record<string, unknown>; };
const uuid = (value: unknown, path: string): string => { if (typeof value !== 'string' || !UUID.test(value)) malformed(`${path} must be a UUID.`); return value as string; };
const string = (value: unknown, path: string): string => { if (typeof value !== 'string' || !value.trim()) malformed(`${path} must be a non-empty string.`); return value as string; };
const number = (value: unknown, path: string): number => { if (!Number.isFinite(value)) malformed(`${path} must be finite.`); return value as number; };
const mapRef = (value: unknown, path: string): SavedMapRef => { const ref = object(value, path); if (ref.entity_type !== 'SavedMap') malformed(`${path}.entity_type must be SavedMap.`); return { entity_type: 'SavedMap', entity_id: uuid(ref.entity_id, `${path}.entity_id`) }; };
const physicalRef = (value: unknown, path: string): ProjectionSourceRef => { const ref = object(value, path); if (ref.ref_type !== 'CANONICAL_FACT' || ref.entity_type !== 'PhysicalObject') malformed(`${path} must be a canonical PhysicalObject ref.`); return { ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: uuid(ref.entity_id, `${path}.entity_id`) }; };
const locationRef = (value: unknown, path: string) => { const ref = object(value, path); if (ref.ref_type !== 'CANONICAL_FACT' || ref.entity_type !== 'Location') malformed(`${path} must be a canonical Location ref.`); return { ref_type: 'CANONICAL_FACT' as const, entity_type: 'Location' as const, entity_id: uuid(ref.entity_id, `${path}.entity_id`) }; };
const cableRef = (value: unknown, path: string): ProjectionSourceRef => { const ref = object(value, path); if (ref.ref_type !== 'CANONICAL_FACT' || ref.entity_type !== 'Cable') malformed(`${path} must be a canonical Cable ref.`); return { ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: uuid(ref.entity_id, `${path}.entity_id`) }; };
const viewKeys: ReadonlySet<string> = new Set(['L1/PHYSICAL_OBJECT', 'L2/DEVICE']);
const position = (value: unknown, path: string): MapViewPosition => { const item = object(value, path); if (!Number.isFinite(item.x) || !Number.isFinite(item.y)) malformed(`${path}.x/y must be finite.`); if (typeof item.locked !== 'boolean') malformed(`${path}.locked must be a boolean.`); if (item.display_width !== undefined && (!Number.isFinite(item.display_width) || (item.display_width as number) <= 0)) malformed(`${path}.display_width must be a positive finite number.`); return { x: item.x as number, y: item.y as number, locked: item.locked as boolean, ...(item.display_width === undefined ? {} : { display_width: item.display_width as number }) }; };
const placement = (value: unknown, path: string): MapPlacement => { const item = object(value, path); const positions = object(item.positions, `${path}.positions`); const parsed = Object.fromEntries(Object.entries(positions).map(([key, entry]) => { if (!viewKeys.has(key)) malformed(`${path}.positions contains an unsupported view key.`); return [key, position(entry, `${path}.positions.${key}`)]; })) as Partial<Record<SavedMapViewKey, MapViewPosition>>; const location = item.location_ref; if (location !== undefined && location !== null) locationRef(location, `${path}.location_ref`); return { physical_object_ref: physicalRef(item.physical_object_ref, `${path}.physical_object_ref`), ...(location === undefined ? {} : { location_ref: location === null ? null : locationRef(location, `${path}.location_ref`) }), positions: parsed }; };
const waypoint = (value: unknown, path: string): MapCableRouteWaypoint => { const item = object(value, path); if (!Number.isFinite(item.x) || !Number.isFinite(item.y)) malformed(`${path}.x/y must be finite.`); return { x: item.x as number, y: item.y as number }; };
const cableRoute = (value: unknown, path: string): MapCableRoute => { const item = object(value, path); if (item.view !== 'L1/PHYSICAL_OBJECT') malformed(`${path}.view must be L1/PHYSICAL_OBJECT.`); if (!Array.isArray(item.waypoints)) malformed(`${path}.waypoints must be an array.`); return { cable_ref: cableRef(item.cable_ref, `${path}.cable_ref`), view: 'L1/PHYSICAL_OBJECT', waypoints: (item.waypoints as unknown[]).map((entry, index) => waypoint(entry, `${path}.waypoints[${index}]`)) }; };
const regionRef = (value: unknown, path: string): MapRegionRef => { const ref = object(value, path); if (ref.entity_type !== 'MapRegion') malformed(`${path}.entity_type must be MapRegion.`); return { entity_type: 'MapRegion', entity_id: uuid(ref.entity_id, `${path}.entity_id`) }; };
const regionPoint = (value: unknown, path: string): MapRegionPoint => { const point = object(value, path); if (!Number.isFinite(point.x) || !Number.isFinite(point.y)) malformed(`${path}.x/y must be finite.`); return { x: point.x as number, y: point.y as number }; };
const color = (value: unknown, path: string): string => { if (typeof value !== 'string' || !/^#[0-9A-Fa-f]{6}$/.test(value)) malformed(`${path} must be #RRGGBB.`); return value as string; };
const regionStyle = (value: unknown, path: string): MapRegionStyle => { const style = object(value, path); if (!Number.isFinite(style.fill_opacity) || (style.fill_opacity as number) < 0 || (style.fill_opacity as number) > 1) malformed(`${path}.fill_opacity must be between 0 and 1.`); if (!Number.isFinite(style.stroke_width) || (style.stroke_width as number) < 0) malformed(`${path}.stroke_width must be a non-negative finite number.`); if (style.stroke_style !== 'solid' && style.stroke_style !== 'dashed' && style.stroke_style !== 'dotted') malformed(`${path}.stroke_style is invalid.`); if (style.label_color !== undefined && style.label_color !== null) color(style.label_color, `${path}.label_color`); return { fill_color: color(style.fill_color, `${path}.fill_color`), fill_opacity: style.fill_opacity as number, stroke_color: color(style.stroke_color, `${path}.stroke_color`), stroke_width: style.stroke_width as number, stroke_style: style.stroke_style as MapRegionStyle['stroke_style'], ...(style.label_color === undefined ? {} : { label_color: style.label_color as string | null }) }; };
const region = (value: unknown, path: string): MapRegion => { const item = object(value, path); if (!Array.isArray(item.points) || item.points.length < 3) malformed(`${path}.points must contain at least three points.`); if (!Number.isInteger(item.z_order)) malformed(`${path}.z_order must be an integer.`); if (item.label_position !== undefined && item.label_position !== null) regionPoint(item.label_position, `${path}.label_position`); const location = item.location_ref; if (location !== undefined && location !== null) locationRef(location, `${path}.location_ref`); return { region_ref: regionRef(item.region_ref, `${path}.region_ref`), ...(location === undefined ? {} : { location_ref: location === null ? null : locationRef(location, `${path}.location_ref`) }), label: string(item.label, `${path}.label`), points: (item.points as unknown[]).map((entry, index) => regionPoint(entry, `${path}.points[${index}]`)), ...(item.label_position === undefined ? {} : { label_position: item.label_position === null ? null : regionPoint(item.label_position, `${path}.label_position`) }), style: regionStyle(item.style, `${path}.style`), z_order: item.z_order as number }; };
const annotationRef = (value: unknown, path: string): MapTextAnnotationRef => { const ref = object(value, path); if (ref.entity_type !== 'MapTextAnnotation') malformed(`${path}.entity_type must be MapTextAnnotation.`); return { entity_type: 'MapTextAnnotation', entity_id: uuid(ref.entity_id, `${path}.entity_id`) }; };
const annotation = (value: unknown, path: string): MapTextAnnotation => { const item = object(value, path); if (!Number.isFinite(item.font_size) || (item.font_size as number) <= 0) malformed(`${path}.font_size must be a positive finite number.`); return { annotation_ref: annotationRef(item.annotation_ref, `${path}.annotation_ref`), text: string(item.text, `${path}.text`), position: regionPoint(item.position, `${path}.position`), text_color: color(item.text_color, `${path}.text_color`), font_size: item.font_size as number }; };
const summary = (value: unknown, path: string): SavedMapSummary => { const item = object(value, path); return { map_ref: mapRef(item.map_ref, `${path}.map_ref`), name: string(item.name, `${path}.name`), created_at: string(item.created_at, `${path}.created_at`), updated_at: string(item.updated_at, `${path}.updated_at`) }; };
const parseMap = (value: unknown): SavedMap => { const item = object(value, 'map'); const base = summary(item, 'map'); if (!Array.isArray(item.placements) || !Array.isArray(item.cable_routes) || !Array.isArray(item.regions) || !Array.isArray(item.text_annotations) || !Array.isArray(item.variants) || !Array.isArray(item.composites)) malformed('map presentation arrays are required.'); const variantRef = (value: unknown) => { const ref = object(value, 'variant_ref'); if (ref.entity_type !== 'MapPresentationVariant') malformed('variant_ref.entity_type must be MapPresentationVariant.'); return { entity_type: 'MapPresentationVariant' as const, entity_id: uuid(ref.entity_id, 'variant_ref.entity_id') }; }; const active = variantRef(item.active_variant_ref); return { ...base, active_variant_ref: active, variants: (item.variants as unknown[]).map((entry) => { const value = object(entry, 'variant'); return { variant_ref: variantRef(value.variant_ref), name: string(value.name, 'variant.name') }; }), placements: (item.placements as unknown[]).map((entry, index) => placement(entry, `map.placements[${index}]`)), cable_routes: (item.cable_routes as unknown[]).map((entry, index) => cableRoute(entry, `map.cable_routes[${index}]`)), composites: (item.composites as unknown[]).map((entry) => { const value = object(entry, 'composite'); const presentation = object(value.presentation, 'composite.presentation'); return { composite_ref: { entity_type: 'MapComposite' as const, entity_id: uuid(object(value.composite_ref, 'composite_ref').entity_id, 'composite_ref.entity_id') }, name: string(value.name, 'composite.name'), physical_object_refs: value.physical_object_refs as any[], presentation: { variant_ref: variantRef(presentation.variant_ref), collapsed: presentation.collapsed === true, x: number(presentation.x, 'presentation.x'), y: number(presentation.y, 'presentation.y'), width: number(presentation.width, 'presentation.width'), height: number(presentation.height, 'presentation.height') } }; }), regions: (item.regions as unknown[]).map((entry, index) => region(entry, `map.regions[${index}]`)), text_annotations: (item.text_annotations as unknown[]).map((entry, index) => annotation(entry, `map.text_annotations[${index}]`)) }; };
const error = async (response: Response): Promise<Error> => { try { const body = object(await response.json(), 'error'); const item = object(body.error, 'error'); if (typeof item.code === 'string' && typeof item.message === 'string') return new Error(`${item.code}: ${item.message}`); } catch { /* generic below */ } return new Error(`HTTP ${response.status} while using SavedMap API.`); };

export class ApiSavedMapDataSource implements SavedMapDataSource {
  constructor(private readonly endpoint = '/api/v1/maps') {}
  async listMaps(): Promise<SavedMapSummary[]> { const response = await fetch(this.endpoint); if (!response.ok) throw await error(response); const body = object(await response.json(), 'list'); if (!Array.isArray(body.maps)) malformed('list.maps must be an array.'); return (body.maps as unknown[]).map((item, index) => summary(item, `list.maps[${index}]`)); }
  async createMap(name: string): Promise<SavedMap> { const response = await fetch(this.endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name }) }); if (!response.ok) throw await error(response); return parseMap(await response.json()); }
  async deleteMap(mapId: string): Promise<void> { uuid(mapId, 'mapId'); const response = await fetch(`${this.endpoint}/${encodeURIComponent(mapId)}`, { method: 'DELETE' }); if (!response.ok) throw await error(response); }
  async loadMap(mapId: string, variantId?: string): Promise<SavedMap> { uuid(mapId, 'mapId'); const response = await fetch(`${this.endpoint}/${encodeURIComponent(mapId)}${variantId ? `?variant_id=${encodeURIComponent(variantId)}` : ''}`); if (!response.ok) throw await error(response); return parseMap(await response.json()); }
  async createPresentationVariant(mapId: string, name: string, sourceVariantId: string): Promise<SavedMap> { const response = await fetch(`${this.endpoint}/${encodeURIComponent(mapId)}/presentation-variants`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, source_variant_id: sourceVariantId }) }); if (!response.ok) throw await error(response); return parseMap(await response.json()); }
  async createComposite(mapId: string, name: string, physicalObjectIds: string[], variantId?: string): Promise<SavedMap> { const response = await fetch(`${this.endpoint}/${encodeURIComponent(mapId)}/composites${variantId ? `?variant_id=${encodeURIComponent(variantId)}` : ''}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, physical_object_ids: physicalObjectIds }) }); if (!response.ok) throw await error(response); return parseMap(await response.json()); }
  async addPlacement(mapId: string, physicalObjectId: string, x: number, y: number, displayWidth?: number, variantId?: string): Promise<void> { await this.mutate(`${mapId}/placements${variantId ? `?variant_id=${variantId}` : ''}`, 'POST', { physical_object_id: physicalObjectId, x, y, ...(displayWidth === undefined ? {} : { display_width: displayWidth }) }); }
  async movePosition(mapId: string, physicalObjectId: string, view: SavedMapView, x: number, y: number, displayWidth?: number, variantId?: string): Promise<void> { await this.mutate(`${mapId}/placements/${encodeURIComponent(physicalObjectId)}/positions/${view}${variantId ? `?variant_id=${variantId}` : ''}`, 'PUT', { x, y, ...(displayWidth === undefined ? {} : { display_width: displayWidth }) }); }
  async setPositionLock(mapId: string, physicalObjectId: string, view: SavedMapView, locked: boolean, variantId?: string): Promise<void> { await this.mutate(`${mapId}/placements/${encodeURIComponent(physicalObjectId)}/locks/${view}${variantId ? `?variant_id=${variantId}` : ''}`, 'PUT', { locked }); }
  async removePlacement(mapId: string, physicalObjectId: string): Promise<void> { await this.mutate(`${mapId}/placements/${encodeURIComponent(physicalObjectId)}`, 'DELETE'); }
  async setCableRoute(mapId: string, cableId: string, waypoints: MapCableRouteWaypoint[], variantId?: string): Promise<void> { uuid(mapId, 'mapId'); uuid(cableId, 'cableId'); const response = await fetch(`${this.endpoint}/${mapId}/cable-routes/${encodeURIComponent(cableId)}${variantId ? `?variant_id=${variantId}` : ''}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ view: 'physical', waypoints }) }); if (!response.ok) throw await error(response); }
  async deleteCableRoute(mapId: string, cableId: string, variantId?: string): Promise<void> { await this.mutate(`${mapId}/cable-routes/${encodeURIComponent(cableId)}${variantId ? `?variant_id=${variantId}` : ''}`, 'DELETE'); }
  async createRegion(mapId: string, region: MapRegionWrite): Promise<void> { await this.mutate(`${mapId}/regions`, 'POST', region); }
  async replaceRegion(mapId: string, regionId: string, region: MapRegionWrite): Promise<void> { await this.mutate(`${mapId}/regions/${encodeURIComponent(regionId)}`, 'PUT', region); }
  async deleteRegion(mapId: string, regionId: string): Promise<void> { await this.mutate(`${mapId}/regions/${encodeURIComponent(regionId)}`, 'DELETE'); }
  async createTextAnnotation(mapId: string, annotation: MapTextAnnotationWrite): Promise<void> { await this.mutate(`${mapId}/text-annotations`, 'POST', annotation); }
  async replaceTextAnnotation(mapId: string, annotationId: string, annotation: MapTextAnnotationWrite): Promise<void> { await this.mutate(`${mapId}/text-annotations/${encodeURIComponent(annotationId)}`, 'PUT', annotation); }
  async deleteTextAnnotation(mapId: string, annotationId: string): Promise<void> { await this.mutate(`${mapId}/text-annotations/${encodeURIComponent(annotationId)}`, 'DELETE'); }
  private async mutate(path: string, method: string, body?: object): Promise<void> { const response = await fetch(`${this.endpoint}/${path}`, { method, headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined }); if (!response.ok) throw await error(response); }
}
