import type { PhysicalEndpointPair, TopologyProjectionDocument, TopologyProjectionEdge, TopologyProjectionNode } from './types';
export interface CollapsedCable { cable: TopologyProjectionNode; source: string; target: string; endpointPair: PhysicalEndpointPair; supportingEdgeIds: [string, string]; }
export interface PhysicalCablePresentation { nodes: TopologyProjectionNode[]; edges: TopologyProjectionEdge[]; cables: CollapsedCable[]; }
const cpIds = (node: TopologyProjectionNode) => new Set(node.source_refs.filter((ref) => ref.entity_type === 'ConnectionPoint').map((ref) => ref.entity_id));
export const physicalCablePresentation = (document: TopologyProjectionDocument): PhysicalCablePresentation => {
 if (document.layer !== 'L1' || document.detail_level !== 'PHYSICAL_OBJECT') return { nodes: [...document.nodes], edges: [...document.edges], cables: [] };
 const byId=new Map(document.nodes.map(n=>[n.id,n])), cables:CollapsedCable[]=[]; const hidden=new Set<string>(), consumed=new Set<string>();
 for(const cable of document.nodes){ if(cable.attributes.class!=='cable'||cable.attributes.connection_point_count!==2)continue; const cps=cpIds(cable), incident=document.edges.filter(e=>e.from_node_id===cable.id||e.to_node_id===cable.id); if(incident.length!==2||incident.some(e=>(e.attributes.endpoint_pairs?.length??0)!==1))continue; const d=incident.map(edge=>{const p=edge.attributes.endpoint_pairs![0], from=edge.from_node_id===cable.id;return{edge,neighbor:from?edge.to_node_id:edge.from_node_id,cablePoint:from?p.from_connection_point_id:p.to_connection_point_id,neighborPoint:from?p.to_connection_point_id:p.from_connection_point_id};}); if(d[0].neighbor===d[1].neighbor||!d.every(x=>cps.has(x.cablePoint)&&byId.has(x.neighbor))||d[0].cablePoint===d[1].cablePoint)continue; const pair={...incident[0].attributes.endpoint_pairs![0],from_connection_point_id:d[0].neighborPoint,to_connection_point_id:d[1].neighborPoint}; cables.push({cable,source:d[0].neighbor,target:d[1].neighbor,endpointPair:pair,supportingEdgeIds:[d[0].edge.id,d[1].edge.id]});hidden.add(cable.id);consumed.add(d[0].edge.id);consumed.add(d[1].edge.id); }
 return{nodes:document.nodes.filter(n=>!hidden.has(n.id)),edges:document.edges.filter(e=>!consumed.has(e.id)),cables};
};
