import { useEffect, useState } from 'react';
import { useI18n } from '../i18n';
import type { CableLabelDataSource, CableLabelTemplate, CableLabelTemplateWrite } from '../topology/cableLabelTypes';

const blank = (): CableLabelTemplateWrite => ({ name: '', description: '', pattern: '', start_at: 0 });
export function CableLabelTemplatesPage({ dataSource }: { dataSource: CableLabelDataSource }) {
  const { t } = useI18n(); const [templates, setTemplates] = useState<CableLabelTemplate[]>([]); const [settings, setSettings] = useState(false); const [form, setForm] = useState<CableLabelTemplateWrite | null>(null); const [editing, setEditing] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = async () => { try { const [list, policy] = await Promise.all([dataSource.loadCableLabelTemplates(), dataSource.loadCableLabelSettings()]); setTemplates(list.templates); setSettings(policy.unique_labels); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Error'); } };
  useEffect(() => { void load(); }, [dataSource]);
  const save = async () => { if (!form) return; try { if (editing) await dataSource.updateCableLabelTemplate(editing, form); else await dataSource.createCableLabelTemplate(form); setForm(null); setEditing(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Error'); } };
  return <main className="catalog-page"><header className="catalog-page__header"><div><h1>{t('cableTemplates.title')}</h1><p>{t('cableTemplates.description')}</p><p>{t('cableNaming.hint')}</p></div><button className="primary-action" onClick={() => { setForm(blank()); setEditing(null); }}>{t('cableTemplates.create')}</button></header><label><input type="checkbox" checked={settings} onChange={async (event) => { try { const next = await dataSource.setCableLabelSettings({ unique_labels: event.target.checked }); setSettings(next.unique_labels); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Error'); } }} /> {t('cableTemplates.uniqueLabels')}</label>{error && <p role="alert">{error}</p>}{form && <section className="catalog-dialog__surface"><label>{t('cableTemplates.name')}<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>{t('cableTemplates.descriptionField')}<input value={form.description ?? ''} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label>{t('cableTemplates.pattern')}<input value={form.pattern} onChange={(e) => setForm({ ...form, pattern: e.target.value })} /></label><label>{t('cableTemplates.startAt')}<input type="number" min="0" value={form.start_at} onChange={(e) => setForm({ ...form, start_at: Number(e.target.value) })} /></label><button onClick={() => void save()}>{t('cableTemplates.save')}</button><button onClick={() => { setForm(null); setEditing(null); }}>{t('cableTemplates.cancel')}</button></section>}<section className="catalog-surface">{templates.length === 0 ? <p>{t('cableTemplates.empty')}</p> : <table className="catalog-table"><thead><tr><th>{t('cableTemplates.name')}</th><th>{t('cableTemplates.descriptionField')}</th><th>{t('cableTemplates.pattern')}</th><th>{t('cableTemplates.startAt')}</th><th /></tr></thead><tbody>{templates.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.description}</td><td>{item.pattern}</td><td>{item.start_at}</td><td><button onClick={() => { setEditing(item.id); setForm({ name: item.name, description: item.description, pattern: item.pattern, start_at: item.start_at }); }}>{t('cableTemplates.edit')}</button><button onClick={() => { if (window.confirm(t('cableTemplates.deleteConfirm', { name: item.name }))) void dataSource.deleteCableLabelTemplate(item.id).then(load, (reason) => setError(reason instanceof Error ? reason.message : 'Error')); }}>{t('cableTemplates.delete')}</button></td></tr>)}</tbody></table>}</section></main>;
}
