import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { describe, expect, it, vi } from 'vitest';
import { InfrastructureObjectsPage } from './InfrastructureObjectsPage';
import type { CatalogInventoryDocument } from '../topology/catalogInventoryTypes';

const ref = (entity_type: string, entity_id: string) => ({ ref_type: 'CANONICAL_FACT', entity_type, entity_id });
const document = (): CatalogInventoryDocument => ({ schema_version: '1.0', equipment: [
  { physical_object_ref: ref('PhysicalObject', 'sw17'), label: 'SW17', class: 'switch', occupancy: { total_ports: 52, connected_ports: 17, free_ports: 35 }, map_memberships: [{ map_ref: { entity_type: 'SavedMap', entity_id: 'map-a' }, name: 'Альфа' }] },
  { physical_object_ref: ref('PhysicalObject', 'unknown'), label: 'Аппарат', class: 'firewall_x', map_memberships: [] },
  { physical_object_ref: ref('PhysicalObject', 'untyped'), label: 'Безымянный', map_memberships: [{ map_ref: { entity_type: 'SavedMap', entity_id: 'map-b' }, name: 'Бета' }] },
  { physical_object_ref: ref('PhysicalObject', 'busy'), label: 'Z2', class: 'outlet', occupancy: { total_ports: 2, connected_ports: 2, free_ports: 0 }, map_memberships: [] },
  { physical_object_ref: ref('PhysicalObject', 'natural'), label: 'Z10', class: 'outlet', occupancy: { total_ports: 2, connected_ports: 0, free_ports: 2 }, map_memberships: [] },
], cables: [
  { cable_ref: ref('PhysicalObject', 'cable'), label: 'C10', resolution: 'SIMPLE_CABLE', endpoint_a: { remote_physical_object_ref: ref('PhysicalObject', 'sw17'), remote_physical_object_label: 'SW17', remote_connection_point_ref: ref('ConnectionPoint', 'a17'), remote_connection_point_label: 'A17', evidence_refs: [] }, endpoint_b: { remote_physical_object_ref: ref('PhysicalObject', 'pp'), remote_physical_object_label: 'PP1', remote_connection_point_ref: ref('ConnectionPoint', 'b17'), remote_connection_point_label: 'B17', evidence_refs: [] }, gaps: [], warnings: [] },
  { cable_ref: ref('PhysicalObject', 'broken'), label: 'C2', resolution: 'UNRESOLVED', gaps: [], warnings: [] },
], gaps: [], warnings: [] });
const renderPage = (source = { loadCatalogInventory: vi.fn().mockResolvedValue(document()) }, deletion?: (id: string) => Promise<void>) => { render(<MemoryRouter><InfrastructureObjectsPage catalogInventoryDataSource={source} physicalObjectDeleteDataSource={deletion ? { deletePhysicalObject: deletion } : undefined} /></MemoryRouter>); return source; };

describe('InfrastructureObjectsPage inventory catalog', () => {
  it('uses one inventory load and renders occupancy, classes, map and detail links', async () => {
    const source = renderPage(); await screen.findByText('SW17');
    expect(source.loadCatalogInventory).toHaveBeenCalledTimes(1); expect(screen.getByText('17 / 52')).toBeInTheDocument(); expect(screen.getAllByText('Состояние не определено')).toHaveLength(2); expect(screen.getAllByText('firewall_x')).toHaveLength(2); expect(screen.getAllByText('Без типа')).toHaveLength(2);
    expect(screen.getByRole('link', { name: 'SW17' })).toHaveAttribute('href', '/infrastructure/objects/sw17'); expect(screen.getByRole('link', { name: 'Альфа' })).toHaveAttribute('href', '/map?map=map-a&view=physical&focus=sw17');
  });
  it('separates cables, preserves returned endpoint order, and never guesses unresolved ends', async () => { renderPage(); await userEvent.click(await screen.findByRole('tab', { name: /Кабели/ })); expect(screen.getByText('SW17')).toBeInTheDocument(); expect(screen.getByRole('link', { name: 'C10' }).closest('tr')).toHaveTextContent('SW17 / A17'); expect(screen.getByText('Неоднозначно')).toBeInTheDocument(); expect(screen.getAllByText('—')).toHaveLength(2); });
  it('searches the current tab and combines type, map, and port filters with AND', async () => { renderPage(); await screen.findByText('SW17'); expect(screen.getAllByRole('row').slice(1).map((row) => row.querySelector('td a')?.textContent)).toEqual(['Аппарат', 'Безымянный', 'SW17', 'Z2', 'Z10']); await userEvent.selectOptions(screen.getByLabelText('Тип'), 'switch'); await userEvent.selectOptions(screen.getByLabelText('Карта'), 'map-a'); await userEvent.selectOptions(screen.getByLabelText('Порты'), 'connected'); expect(screen.getByText('SW17')).toBeInTheDocument(); expect(screen.queryByText('Z2')).not.toBeInTheDocument(); await userEvent.type(screen.getByLabelText('Поиск'), 'альфа'); expect(screen.getByText('SW17')).toBeInTheDocument(); });
  it('searches cable endpoints and filters cable resolution', async () => { renderPage(); await userEvent.click(await screen.findByRole('tab', { name: /Кабели/ })); await userEvent.type(screen.getByLabelText('Поиск'), 'pp1'); expect(screen.getByText('C10')).toBeInTheDocument(); expect(screen.queryByText('C2')).not.toBeInTheDocument(); await userEvent.clear(screen.getByLabelText('Поиск')); await userEvent.selectOptions(screen.getByLabelText('Состояние кабеля'), 'UNRESOLVED'); expect(screen.getByText('C2')).toBeInTheDocument(); expect(screen.queryByText('C10')).not.toBeInTheDocument(); });
  it('keeps cable confirmation and removes an equipment row only after authoritative reload', async () => { const loadCatalogInventory = vi.fn().mockResolvedValueOnce(document()).mockResolvedValueOnce({ ...document(), equipment: document().equipment.filter((item) => item.label !== 'SW17') }); const deleted = vi.fn().mockResolvedValue(undefined); vi.spyOn(window, 'confirm').mockReturnValue(true); renderPage({ loadCatalogInventory }, deleted); await userEvent.click(await screen.findByRole('button', { name: 'Удалить SW17' })); await waitFor(() => expect(loadCatalogInventory).toHaveBeenCalledTimes(2)); expect(deleted).toHaveBeenCalledWith('sw17'); await waitFor(() => expect(screen.queryByRole('link', { name: 'SW17' })).not.toBeInTheDocument()); await userEvent.click(screen.getByRole('tab', { name: /Кабели/ })); await userEvent.click(screen.getByRole('button', { name: 'Удалить C10' })); expect(window.confirm).toHaveBeenCalledWith('Удалить кабель «C10» и разорвать соединение?'); });
  it('uses catalog-specific loading/error wording and retries failed loads', async () => { const loadCatalogInventory = vi.fn().mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce(document()); const pending = { loadCatalogInventory: vi.fn(() => new Promise<CatalogInventoryDocument>(() => undefined)) }; const loadingView = render(<MemoryRouter><InfrastructureObjectsPage catalogInventoryDataSource={pending} /></MemoryRouter>); expect(screen.getByText('Загружаем каталог')).toBeInTheDocument(); expect(screen.queryByText(/topology projection/i)).not.toBeInTheDocument(); loadingView.unmount(); renderPage({ loadCatalogInventory }); expect(await screen.findByText('Не удалось загрузить каталог')).toBeInTheDocument(); expect(screen.getByText('offline')).toBeInTheDocument(); expect(screen.queryByText(/Не удалось загрузить схему/)).not.toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Повторить' })); expect(await screen.findByText('SW17')).toBeInTheDocument(); expect(loadCatalogInventory).toHaveBeenCalledTimes(2); });
  it('leaves a row visible when deletion fails', async () => { const failedDelete = vi.fn().mockRejectedValue(new Error('blocked')); vi.spyOn(window, 'confirm').mockReturnValue(true); renderPage(undefined, failedDelete); await userEvent.click(await screen.findByRole('button', { name: 'Удалить SW17' })); expect(await screen.findByText('blocked')).toBeInTheDocument(); expect(screen.getAllByText('SW17').length).toBeGreaterThan(0); });
  it('shows loading and ignores a stale response after a newer datasource load', async () => { let resolveFirst!: (value: CatalogInventoryDocument) => void; const first = { loadCatalogInventory: vi.fn(() => new Promise<CatalogInventoryDocument>((resolve) => { resolveFirst = resolve; })) }; const second = { loadCatalogInventory: vi.fn().mockResolvedValue({ ...document(), equipment: [] }) }; const view = render(<MemoryRouter><InfrastructureObjectsPage catalogInventoryDataSource={first} /></MemoryRouter>); expect(screen.getByText('Загружаем каталог')).toBeInTheDocument(); view.rerender(<MemoryRouter><InfrastructureObjectsPage catalogInventoryDataSource={second} /></MemoryRouter>); await screen.findByText('Оборудование пока не создано.'); resolveFirst(document()); await waitFor(() => expect(screen.queryByText('SW17')).not.toBeInTheDocument()); });
});
