import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter, useLocation } from 'react-router-dom';
import { describe, expect, it, vi } from 'vitest';
import { MapPage } from './MapPage';
import type { SavedMapDataSource } from '../topology/savedMapTypes';
import type { TopologyDataSource, TopologyProjectionDocument } from '../topology/types';

vi.mock('../components/TopologyCanvas', () => ({ TopologyCanvas: (props: any) => <div data-testid="canvas" data-layer={props.document.layer} data-scene={props.sceneKey} data-position={JSON.stringify(props.positionOverrides)}>{props.document.nodes.map((node: any) => <button key={node.id} onClick={() => props.onSelectionChange({ type: 'node', item: node })}>{node.label}</button>)}<button onClick={() => props.onPhysicalNodeDragStop?.(PP, { x: 77, y: 88 })}>drag</button></div> }));
vi.mock('../components/TraceCommandBar', () => ({ TraceCommandBar: (props: any) => <div data-testid="trace-logical">{props.logicalDocument?.nodes.map((node: any) => node.label).join(',')}<button onClick={() => props.onTraceArtifact({ verdict: 'REACHABLE', nodes: [], edges: [], branches: [] })}>reachable</button></div> }));
vi.mock('../components/QuickInspector', () => ({ QuickInspector: (props: any) => props.selection ? <div data-testid="inspector"><button onClick={() => props.onRemoveFromMap?.(PP)}>remove</button><button onClick={() => props.onDeletePhysicalObject?.(PP)}>delete</button></div> : null }));

const PP = '00000000-0000-4000-8000-000000000001'; const SW = '00000000-0000-4000-8000-000000000002'; const PC = '00000000-0000-4000-8000-000000000003'; const A = '00000000-0000-4000-8000-000000000010'; const B = '00000000-0000-4000-8000-000000000011';
const node = (id: string, label: string) => ({ id: `node-${id}`, kind: 'PHYSICAL_OBJECT', label, source_refs: [{ ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: id }], attributes: {} });
const physical = (...ids: string[]): TopologyProjectionDocument => ({ schema_version: '1.0', layer: 'L1', detail_level: 'PHYSICAL_OBJECT', nodes: ids.map((id) => node(id, id === PP ? 'PP1' : id === SW ? 'SW1' : 'PC1')), edges: [], gaps: [], warnings: [] });
const logical: TopologyProjectionDocument = { schema_version: '1.0', layer: 'L2', detail_level: 'DEVICE', nodes: [node(PP, 'PP1'), node(PC, 'PC1')], edges: [], gaps: [], warnings: [] };
const saved = (id: string, placements: Array<[string, number, number, number?, number?]>) => ({ map_ref: { entity_type: 'SavedMap' as const, entity_id: id }, name: id === A ? 'A' : 'B', created_at: 'x', updated_at: 'x', placements: placements.map(([objectId, x, y, logicalX, logicalY]) => ({ physical_object_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: objectId }, positions: { 'L1/PHYSICAL_OBJECT': { x, y }, ...(logicalX === undefined || logicalY === undefined ? {} : { 'L2/DEVICE': { x: logicalX, y: logicalY } }) } })) });
const Location = () => <output data-testid="location">{useLocation().search}</output>;
const renderPage = (source: TopologyDataSource, maps: SavedMapDataSource, entry = `/map?map=${A}&view=physical`) => render(<MemoryRouter initialEntries={[entry]}><MapPage dataSource={source} deviceDetailsDataSource={{ loadDeviceDetails: vi.fn() }} savedMapDataSource={maps} physicalObjectDeleteDataSource={{ deletePhysicalObject: vi.fn() }} /><Location /></MemoryRouter>);

describe('MapPage SavedMap scope', () => {
  it('does not request topology when there are no maps or an empty map', async () => { const loadProjection = vi.fn(); const maps = { listMaps: vi.fn().mockResolvedValue([]), loadMap: vi.fn(), createMap: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), removePlacement: vi.fn() }; renderPage({ loadProjection }, maps, '/map'); expect(await screen.findByText('Создайте первую карту')).toBeInTheDocument(); expect(loadProjection).not.toHaveBeenCalled(); });
  it('uses exact placement scope for both visible views, expands only physical interstitial cables, and keeps full logical trace scope', async () => { const loadProjection = vi.fn((request) => Promise.resolve(request.layer === 'L2' ? logical : physical(PP, SW))); const maps: any = { listMaps: vi.fn().mockResolvedValue([saved(A, [])]), loadMap: vi.fn().mockResolvedValue(saved(A, [[PP, 100, 200], [SW, 300, 400]])), createMap: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), removePlacement: vi.fn() }; renderPage({ loadProjection }, maps); await screen.findByText('PP1'); await waitFor(() => expect(loadProjection.mock.calls.some(([request]) => request.layer === 'L2' && request.scope.include_entities.length === 0)).toBe(true)); expect(loadProjection.mock.calls.some(([request]) => request.layer === 'L1' && request.include_interstitial_cables === true && request.scope.include_entities.map((ref: any) => ref.entity_id).join(',') === `${PP},${SW}`)).toBe(true); fireEvent.click(screen.getByRole('button', { name: 'Логическая' })); await waitFor(() => expect(loadProjection.mock.calls.some(([request]) => request.layer === 'L2' && request.include_interstitial_cables === undefined && request.scope.include_entities.map((ref: any) => ref.entity_id).join(',') === `${PP},${SW}`)).toBe(true)); });
  it('acknowledges a physical drag locally without reloading map or projection', async () => { const loadProjection = vi.fn((request) => Promise.resolve(request.layer === 'L2' ? logical : physical(PP))); const maps: any = { listMaps: vi.fn().mockResolvedValue([saved(A, [])]), loadMap: vi.fn().mockResolvedValue(saved(A, [[PP, 100, 200, 300, 400]])), createMap: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn().mockResolvedValue(undefined), removePlacement: vi.fn() }; renderPage({ loadProjection }, maps); await screen.findByText('PP1'); const mapLoads = maps.loadMap.mock.calls.length; const projectionLoads = loadProjection.mock.calls.length; expect(screen.getByTestId('canvas')).toHaveAttribute('data-position', expect.stringContaining('100')); fireEvent.click(screen.getByText('drag')); await waitFor(() => expect(maps.movePosition).toHaveBeenCalledWith(A, PP, 'physical', 77, 88)); expect(maps.loadMap).toHaveBeenCalledTimes(mapLoads); expect(loadProjection).toHaveBeenCalledTimes(projectionLoads); expect(screen.getByTestId('canvas')).toHaveAttribute('data-position', expect.stringContaining('77')); fireEvent.click(screen.getByRole('button', { name: 'Логическая' })); await waitFor(() => expect(screen.getByTestId('canvas')).toHaveAttribute('data-position', expect.stringContaining('300'))); });
  it('rolls a failed physical drag back from the authoritative map without reloading projection', async () => { const loadProjection = vi.fn((request) => Promise.resolve(request.layer === 'L2' ? logical : physical(PP))); const maps: any = { listMaps: vi.fn().mockResolvedValue([saved(A, [])]), loadMap: vi.fn().mockResolvedValue(saved(A, [[PP, 100, 200]])), createMap: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn().mockRejectedValue(new Error('failed')), removePlacement: vi.fn() }; renderPage({ loadProjection }, maps); await screen.findByText('PP1'); const projectionLoads = loadProjection.mock.calls.length; fireEvent.click(screen.getByText('drag')); await waitFor(() => expect(maps.loadMap).toHaveBeenCalledTimes(2)); expect(loadProjection).toHaveBeenCalledTimes(projectionLoads); expect(screen.getByTestId('canvas')).toHaveAttribute('data-position', expect.stringContaining('100')); });
  it('uses independent per-view coordinates and initializes missing logical positions with ELK', async () => { const loadProjection = vi.fn((request) => Promise.resolve(request.layer === 'L2' ? logical : physical(PP))); const maps: any = { listMaps: vi.fn().mockResolvedValue([saved(A, [])]), loadMap: vi.fn().mockResolvedValue(saved(A, [[PP, 100, 200]])), createMap: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn().mockResolvedValue(undefined), removePlacement: vi.fn() }; renderPage({ loadProjection }, maps); await screen.findByText('PP1'); expect(screen.getByTestId('canvas')).toHaveAttribute('data-position', expect.stringContaining('100')); fireEvent.click(screen.getByRole('button', { name: 'Логическая' })); await waitFor(() => expect(screen.getByTestId('canvas')).toHaveAttribute('data-scene', `${A}/logical`)); expect(screen.getByTestId('canvas')).toHaveAttribute('data-position', '{}'); fireEvent.click(screen.getByText('drag')); await waitFor(() => expect(maps.movePosition).toHaveBeenCalledWith(A, PP, 'logical', 77, 88)); expect(screen.getByTestId('canvas')).toHaveAttribute('data-position', expect.stringContaining('77')); fireEvent.click(screen.getByRole('button', { name: 'Физическая' })); await waitFor(() => expect(screen.getByTestId('canvas')).toHaveAttribute('data-position', expect.stringContaining('100'))); });
  it('does not render a new view scene with the previous projection or its fallback positions', async () => { let resolveLogical!: (value: TopologyProjectionDocument) => void; const logicalProjection = new Promise<TopologyProjectionDocument>((resolve) => { resolveLogical = resolve; }); const loadProjection = vi.fn((request) => request.layer === 'L2' ? logicalProjection : Promise.resolve(physical(PP))); const maps: any = { listMaps: vi.fn().mockResolvedValue([saved(A, [])]), loadMap: vi.fn().mockResolvedValue(saved(A, [[PP, 100, 200, 300, 400]])), createMap: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), removePlacement: vi.fn() }; renderPage({ loadProjection }, maps); await screen.findByText('PP1'); fireEvent.click(screen.getByRole('button', { name: 'Логическая' })); expect(screen.queryByTestId('canvas')).not.toBeInTheDocument(); await act(async () => { resolveLogical(logical); }); await waitFor(() => expect(screen.getByTestId('canvas')).toHaveAttribute('data-scene', `${A}/logical`)); expect(screen.getByTestId('canvas')).toHaveAttribute('data-position', expect.stringContaining('300')); });
  it('waits for the selected map projection before restoring that map positions', async () => { let resolveB!: (value: ReturnType<typeof saved>) => void; const mapB = new Promise<ReturnType<typeof saved>>((resolve) => { resolveB = resolve; }); const loadProjection = vi.fn((request) => Promise.resolve(request.layer === 'L2' ? logical : physical(...request.scope.include_entities.map((ref: any) => ref.entity_id)))); const maps: any = { listMaps: vi.fn().mockResolvedValue([saved(A, []), saved(B, [])]), loadMap: vi.fn((id) => id === A ? Promise.resolve(saved(A, [[PP, 10, 20]])) : mapB), createMap: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), removePlacement: vi.fn() }; renderPage({ loadProjection }, maps); await screen.findByText('PP1'); expect(screen.getByTestId('canvas')).toHaveAttribute('data-position', expect.stringContaining('10')); fireEvent.change(screen.getByLabelText('Карты'), { target: { value: B } }); expect(screen.queryByTestId('canvas')).not.toBeInTheDocument(); await act(async () => { resolveB(saved(B, [[PP, 70, 80]])); }); await waitFor(() => expect(screen.getByTestId('canvas')).toHaveAttribute('data-scene', `${B}/physical`)); expect(screen.getByTestId('canvas')).toHaveAttribute('data-position', expect.stringContaining('70')); fireEvent.change(screen.getByLabelText('Карты'), { target: { value: A } }); await waitFor(() => expect(screen.getByTestId('canvas')).toHaveAttribute('data-scene', `${A}/physical`)); expect(screen.getByTestId('canvas')).toHaveAttribute('data-position', expect.stringContaining('10')); });
  it('clears stale selection on map switch and keeps remove separate from canonical delete', async () => { const loadProjection = vi.fn((request) => Promise.resolve(request.layer === 'L2' ? logical : physical(PP))); const removePlacement = vi.fn().mockResolvedValue(undefined); const deletePhysicalObject = vi.fn(); const maps: any = { listMaps: vi.fn().mockResolvedValue([saved(A, []), saved(B, [])]), loadMap: vi.fn((id) => Promise.resolve(id === A ? saved(A, [[PP, 1, 2]]) : saved(B, []))), createMap: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), removePlacement }; render(<MemoryRouter initialEntries={[`/map?map=${A}&view=physical`]}><MapPage dataSource={{ loadProjection }} deviceDetailsDataSource={{ loadDeviceDetails: vi.fn() }} savedMapDataSource={maps} physicalObjectDeleteDataSource={{ deletePhysicalObject }} /><Location /></MemoryRouter>); await screen.findByText('PP1'); fireEvent.click(screen.getByText('PP1')); expect(await screen.findByTestId('inspector')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Карты'), { target: { value: B } }); await waitFor(() => expect(screen.queryByTestId('inspector')).not.toBeInTheDocument()); });
});
