import { describe, expect, it, vi } from 'vitest';
import { fireEvent, screen, waitFor } from '@testing-library/react';
import { MapPage } from './MapPage';
import { createMapPageHarness } from './MapPage.testHarness';

vi.mock('../components/TopologyCanvas', () => ({ TopologyCanvas: (p: any) => <><button onClick={() => { p.onViewportCenterReady?.(() => ({ x: 12, y: 34 })); p.onSelectionChange({ type: 'node', item: p.document.cableNode ?? p.document.nodes[0] }); }}>select</button><button onClick={() => { p.onViewportCenterReady?.(() => ({ x: 12, y: 34 })); p.onSelectionChange({ type: 'continuation', item: p.document.l1_off_map_continuations?.[0] }); }}>continuation</button><button onClick={() => p.onNodeCollisionRejected?.()}>collision</button><button onClick={() => p.cableRouteDraft?.onWaypointInsert(0, { x: 70, y: 80 })}>route segment</button><button onClick={() => p.cableRouteDraft?.onWaypointSelect(0)}>route handle</button></> }));
const renderMapPage = createMapPageHarness(MapPage);
const A = 'map-a'; const O = 'object';
const node = { id: 'node', kind: 'PHYSICAL_OBJECT', label: 'SW1', attributes: { class: 'switch' }, source_refs: [{ ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: O }] };
const remoteBlueprintPresentation = { blueprint_presentation: { body: { kind: 'RECTANGLE', width: 100, height: 100 }, slots: [{ face: 'FRONT', rendered_position: { x: .5, y: .5 } }] } };
const cableNode = { id: 'cable-node', kind: 'CABLE', label: 'C1', attributes: {}, source_refs: [{ ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: 'cable' }] };
const continuation = { id: 'c', local_node_id: 'node', local_physical_object_ref: node.source_refs[0], local_connection_point_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'ConnectionPoint', entity_id: 'p' }, local_connection_point_display_name: 'A01', cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'Cable', entity_id: 'cable' }, cable_display_name: 'C1', remote_physical_object_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: 'remote' }, remote_display_name: 'PP1', remote_connection_point_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'ConnectionPoint', entity_id: 'rp' }, remote_connection_point_display_name: 'B01', source_refs: [] };
const doc: any = { schema_version: '1.0', layer: 'L1', detail_level: 'PHYSICAL_OBJECT', nodes: [node], edges: [], gaps: [], warnings: [], l1_off_map_continuations: [continuation] };
const map = { map_ref: { entity_type: 'SavedMap', entity_id: A }, name: 'A', placements: [{ physical_object_ref: node.source_refs[0], positions: { 'L1/PHYSICAL_OBJECT': { x: 1, y: 2 } } }] };
const collapsedCableDocument: any = { ...doc, cableNode, nodes: [node, { ...node, id: 'right', source_refs: [{ ...node.source_refs[0], entity_id: 'right' }] }], edges: [{ id: 'cable-link', from_node_id: 'node', to_node_id: 'right', kind: 'L1_PHYSICAL_LINK', aggregate: true, source_refs: [], attributes: { endpoint_pairs: [{ from_connection_point_id: 'left-cp', from_member_index: 1, to_connection_point_id: 'right-cp', to_member_index: 1, connection_id: 'connection', connection_member_id: 'member', cable_ref: cableNode.source_refs[0] }] } }] };
const renderPage = (maps: any, remove = vi.fn(), document = doc) => renderMapPage({ dataSource: { loadProjection: vi.fn((request) => Promise.resolve(request.scope.include_entities[0]?.entity_id === 'remote' ? { ...document, nodes: [{ ...node, id: 'remote-node', label: 'PP1', attributes: { ...node.attributes, ...remoteBlueprintPresentation }, source_refs: [{ ...node.source_refs[0], entity_id: 'remote' }] }] } : document)) }, deviceDetailsDataSource: { loadDeviceDetails: vi.fn() }, savedMapDataSource: maps, physicalObjectDeleteDataSource: { deletePhysicalObject: remove }, cableDeleteDataSource: { deleteCable: remove } }, `/map?map=${A}&view=physical`);

describe('MapPage mutation lifecycles', () => {
  it('distinguishes a persisted explicit straight route from absent route in the inspector', async () => { const cableMap: any = { ...map, cable_routes: [{ cable_ref: cableNode.source_refs[0], view: 'L1/PHYSICAL_OBJECT', waypoints: [] }] }; const maps: any = { listMaps: vi.fn().mockResolvedValue([cableMap]), loadMap: vi.fn().mockResolvedValue(cableMap), createMap: vi.fn() }; renderPage(maps, vi.fn(), collapsedCableDocument); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); expect(await screen.findByText('Точек: 0')).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Сбросить трассу' })).toBeInTheDocument(); });
  it('cancels a moved or inserted draft with zero route writes', async () => { const cableMap: any = { ...map, cable_routes: [] }; const maps: any = { listMaps: vi.fn().mockResolvedValue([cableMap]), loadMap: vi.fn().mockResolvedValue(cableMap), createMap: vi.fn(), setCableRoute: vi.fn(), deleteCableRoute: vi.fn() }; renderPage(maps, vi.fn(), collapsedCableDocument); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(await screen.findByRole('button', { name: 'Редактировать трассу' })); fireEvent.click(screen.getByText('route segment')); fireEvent.click(screen.getByRole('button', { name: 'Отменить' })); expect(maps.setCableRoute).not.toHaveBeenCalled(); expect(maps.deleteCableRoute).not.toHaveBeenCalled(); });
  it('closes a Physical draft on Logical switch without writes', async () => { const cableMap: any = { ...map, cable_routes: [] }; const maps: any = { listMaps: vi.fn().mockResolvedValue([cableMap]), loadMap: vi.fn().mockResolvedValue(cableMap), createMap: vi.fn(), setCableRoute: vi.fn(), deleteCableRoute: vi.fn() }; renderPage(maps, vi.fn(), collapsedCableDocument); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(await screen.findByRole('button', { name: 'Редактировать трассу' })); fireEvent.click(screen.getByRole('button', { name: 'Логическая' })); await waitFor(() => expect(screen.queryByRole('button', { name: 'Сохранить трассу' })).not.toBeInTheDocument()); expect(maps.setCableRoute).not.toHaveBeenCalled(); expect(maps.deleteCableRoute).not.toHaveBeenCalled(); });
  it('deletes the last draft waypoint with PUT [] and never route DELETE', async () => { const cableMap: any = { ...map, cable_routes: [{ cable_ref: cableNode.source_refs[0], view: 'L1/PHYSICAL_OBJECT', waypoints: [{ x: 1, y: 2 }] }] }; const saved: any = { ...cableMap, cable_routes: [{ ...cableMap.cable_routes[0], waypoints: [] }] }; const maps: any = { listMaps: vi.fn().mockResolvedValue([cableMap]), loadMap: vi.fn().mockResolvedValue(cableMap), createMap: vi.fn(), setCableRoute: vi.fn().mockResolvedValue(saved), deleteCableRoute: vi.fn() }; renderPage(maps, vi.fn(), collapsedCableDocument); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(await screen.findByRole('button', { name: 'Редактировать трассу' })); fireEvent.click(screen.getByText('route handle')); fireEvent.click(screen.getByRole('button', { name: 'Удалить выбранную точку' })); fireEvent.click(screen.getByRole('button', { name: 'Сохранить трассу' })); await waitFor(() => expect(maps.setCableRoute).toHaveBeenCalledWith(A, 'cable', [])); expect(maps.deleteCableRoute).not.toHaveBeenCalled(); });
  it('keeps the draft editable after save failure without exposing raw diagnostics', async () => { const cableMap: any = { ...map, cable_routes: [] }; const maps: any = { listMaps: vi.fn().mockResolvedValue([cableMap]), loadMap: vi.fn().mockResolvedValue(cableMap), createMap: vi.fn(), setCableRoute: vi.fn().mockRejectedValue(new Error('Malformed SavedMap response: save failed')), deleteCableRoute: vi.fn() }; renderPage(maps, vi.fn(), collapsedCableDocument); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(await screen.findByRole('button', { name: 'Редактировать трассу' })); fireEvent.click(screen.getByText('route segment')); fireEvent.click(screen.getByRole('button', { name: 'Сохранить трассу' })); expect(await screen.findByRole('alert')).toHaveTextContent('Не удалось сохранить трассу кабеля.'); expect(screen.queryByText(/Malformed SavedMap response/)).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Сохранить трассу' })).toBeInTheDocument(); });
  it('retries only map refresh after a successful route reset DELETE', async () => { const cableMap: any = { ...map, cable_routes: [{ cable_ref: cableNode.source_refs[0], view: 'L1/PHYSICAL_OBJECT', waypoints: [] }] }; const maps: any = { listMaps: vi.fn().mockResolvedValue([cableMap]), loadMap: vi.fn().mockResolvedValue(cableMap), createMap: vi.fn(), deleteCableRoute: vi.fn().mockResolvedValue(undefined), setCableRoute: vi.fn() }; renderPage(maps, vi.fn(), collapsedCableDocument); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); await screen.findByRole('button', { name: 'Сбросить трассу' }); maps.loadMap.mockRejectedValueOnce(new Error('refresh failed')).mockResolvedValueOnce({ ...cableMap, cable_routes: [] }); fireEvent.click(screen.getByRole('button', { name: 'Сбросить трассу' })); await screen.findByRole('button', { name: 'Повторить обновление' }); expect(maps.deleteCableRoute).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByRole('button', { name: 'Повторить обновление' })); await waitFor(() => expect(maps.deleteCableRoute).toHaveBeenCalledTimes(1)); });
  it('edits a cable draft locally and saves one ordered full-route PUT', async () => { const cableMap: any = { ...map, cable_routes: [] }; const saved: any = { ...cableMap, cable_routes: [{ cable_ref: cableNode.source_refs[0], view: 'L1/PHYSICAL_OBJECT', waypoints: [{ x: 70, y: 80 }] }] }; const setCableRoute = vi.fn().mockResolvedValue(saved); const maps: any = { listMaps: vi.fn().mockResolvedValue([cableMap]), loadMap: vi.fn().mockResolvedValue(cableMap), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn(), setCableRoute, deleteCableRoute: vi.fn() }; renderPage(maps, vi.fn(), collapsedCableDocument); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); expect(await screen.findByText('Пользовательская трасса не задана')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Редактировать трассу' })); fireEvent.click(screen.getByText('route segment')); fireEvent.click(screen.getByRole('button', { name: 'Сохранить трассу' })); await waitFor(() => expect(setCableRoute).toHaveBeenCalledWith(A, 'cable', [{ x: 70, y: 80 }])); expect(setCableRoute).toHaveBeenCalledTimes(1); });
  it('reopens the authoritative route for a second edit and save', async () => { const cableMap: any = { ...map, cable_routes: [] }; const first: any = { ...cableMap, cable_routes: [{ cable_ref: cableNode.source_refs[0], view: 'L1/PHYSICAL_OBJECT', waypoints: [{ x: 70, y: 80 }] }] }; const second: any = { ...first, cable_routes: [{ ...first.cable_routes[0], waypoints: [{ x: 70, y: 80 }, { x: 70, y: 80 }] }] }; const setCableRoute = vi.fn().mockResolvedValue(undefined); const maps: any = { listMaps: vi.fn().mockResolvedValue([cableMap]), loadMap: vi.fn().mockResolvedValue(cableMap), createMap: vi.fn(), setCableRoute, deleteCableRoute: vi.fn() }; renderPage(maps, vi.fn(), collapsedCableDocument); await screen.findByText('select'); maps.loadMap.mockResolvedValueOnce(first).mockResolvedValueOnce(second); fireEvent.click(screen.getByText('select')); fireEvent.click(await screen.findByRole('button', { name: 'Редактировать трассу' })); fireEvent.click(screen.getByText('route segment')); fireEvent.click(screen.getByRole('button', { name: 'Сохранить трассу' })); await screen.findByText('Точек: 1'); fireEvent.click(screen.getByRole('button', { name: 'Редактировать трассу' })); fireEvent.click(screen.getByText('route segment')); fireEvent.click(screen.getByRole('button', { name: 'Сохранить трассу' })); await waitFor(() => expect(setCableRoute).toHaveBeenCalledTimes(2)); expect(setCableRoute).toHaveBeenLastCalledWith(A, 'cable', [{ x: 70, y: 80 }, { x: 70, y: 80 }]); });
  it('retries only authoritative route refresh after an acknowledged edit write failure', async () => { const cableMap: any = { ...map, cable_routes: [] }; const saved: any = { ...cableMap, cable_routes: [{ cable_ref: cableNode.source_refs[0], view: 'L1/PHYSICAL_OBJECT', waypoints: [{ x: 70, y: 80 }] }] }; const setCableRoute = vi.fn().mockResolvedValue(undefined); const maps: any = { listMaps: vi.fn().mockResolvedValue([cableMap]), loadMap: vi.fn().mockResolvedValue(cableMap), createMap: vi.fn(), setCableRoute, deleteCableRoute: vi.fn() }; renderPage(maps, vi.fn(), collapsedCableDocument); await screen.findByText('select'); maps.loadMap.mockRejectedValueOnce(new Error('Malformed SavedMap response: route')).mockResolvedValueOnce(saved); fireEvent.click(screen.getByText('select')); fireEvent.click(await screen.findByRole('button', { name: 'Редактировать трассу' })); fireEvent.click(screen.getByText('route segment')); fireEvent.click(screen.getByRole('button', { name: 'Сохранить трассу' })); expect(await screen.findByRole('alert')).toHaveTextContent('Трасса сохранена, но карту не удалось обновить.'); expect(screen.queryByText(/Malformed SavedMap response/)).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Повторить обновление' })); await screen.findByText('Точек: 1'); expect(setCableRoute).toHaveBeenCalledTimes(1); });
  it('shows local collision feedback without starting a position write', async () => { const movePosition = vi.fn(); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition, setPositionLock: vi.fn(), createMap: vi.fn() }; renderPage(maps); await screen.findByText('collision'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByText('collision')); expect(await screen.findByRole('alert')).toHaveTextContent('Объекты нельзя размещать друг на друге.'); expect(movePosition).not.toHaveBeenCalled(); expect(screen.getByRole('heading', { name: 'SW1' })).toBeInTheDocument(); });
  it('keeps selection and reports remove write failure', async () => { const removePlacement = vi.fn().mockRejectedValue(new Error('remove failed')); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement, addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() }; renderPage(maps); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByRole('button', { name: 'Убрать с карты' })); expect(await screen.findByRole('alert')).toHaveTextContent('remove failed'); expect(screen.getByRole('heading', { name: 'SW1' })).toBeInTheDocument(); });
  it('allows a continuation write retry after an add failure', async () => { const addPlacement = vi.fn().mockRejectedValue(new Error('add failed')); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement: vi.fn(), addPlacement, movePosition: vi.fn(), createMap: vi.fn() }; renderPage(maps); await screen.findByText('continuation'); fireEvent.click(screen.getByText('continuation')); const add = screen.getByRole('button', { name: 'Добавить на карту' }); fireEvent.click(add); expect(await screen.findByRole('alert')).toHaveTextContent('add failed'); expect(add).not.toBeDisabled(); fireEvent.click(add); await waitFor(() => expect(addPlacement).toHaveBeenCalledWith(A, 'remote', expect.any(Number), expect.any(Number), 96)); expect(addPlacement).toHaveBeenCalledTimes(2); });
  it('keeps inspector on delete write failure', async () => { const remove = vi.fn().mockRejectedValue(new Error('delete failed')); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() }; vi.spyOn(window, 'confirm').mockReturnValue(true); renderMapPage({ dataSource: { loadProjection: vi.fn().mockResolvedValue(doc) }, deviceDetailsDataSource: { loadDeviceDetails: vi.fn() }, savedMapDataSource: maps, physicalObjectDeleteDataSource: { deletePhysicalObject: remove } }, `/map?map=${A}&view=physical`); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByRole('button', { name: 'Удалить объект из NetMap' })); expect(await screen.findByRole('alert')).toHaveTextContent('delete failed'); });
  it('refreshes the authoritative projection after deleting a routed cable even when map membership is unchanged', async () => {
    const routedMap: any = { ...map, cable_routes: [{ cable_ref: cableNode.source_refs[0], view: 'L1/PHYSICAL_OBJECT', waypoints: [{ x: 1, y: 2 }] }] };
    const loadProjection = vi.fn().mockResolvedValueOnce(collapsedCableDocument).mockResolvedValue({ ...collapsedCableDocument, nodes: [node], edges: [] });
    const maps: any = { listMaps: vi.fn().mockResolvedValue([routedMap]), loadMap: vi.fn().mockResolvedValueOnce(routedMap).mockResolvedValueOnce(routedMap).mockResolvedValueOnce({ ...routedMap, cable_routes: [] }), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() };
    vi.spyOn(window, 'confirm').mockReturnValue(true);
    renderMapPage({ dataSource: { loadProjection }, deviceDetailsDataSource: { loadDeviceDetails: vi.fn() }, savedMapDataSource: maps, physicalObjectDeleteDataSource: { deletePhysicalObject: vi.fn().mockResolvedValue(undefined) }, cableDeleteDataSource: { deleteCable: vi.fn().mockResolvedValue(undefined) } }, `/map?map=${A}&view=physical`);
    await screen.findByText('select');
    fireEvent.click(screen.getByText('select'));
    await screen.findByText('Точек: 1');
    const initialProjectionLoads = loadProjection.mock.calls.length;
    fireEvent.click(screen.getByText('Дополнительные действия'));
    fireEvent.click(screen.getByRole('button', { name: 'Удалить кабель и разорвать физическое соединение' }));
    await waitFor(() => expect(loadProjection.mock.calls.length).toBeGreaterThan(initialProjectionLoads));
    expect(maps.loadMap).toHaveBeenCalledTimes(3);
  });
  it('does not repeat a successful remove when its authoritative refresh fails', async () => { const removePlacement = vi.fn().mockResolvedValue(undefined); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValueOnce(map).mockResolvedValueOnce(map).mockRejectedValueOnce(new Error('refresh failed')).mockResolvedValueOnce({ ...map, placements: [] }), removePlacement, addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() }; renderPage(maps); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByRole('button', { name: 'Убрать с карты' })); await screen.findByText('Объект убран с карты, но карту не удалось обновить.'); expect(removePlacement).toHaveBeenCalledTimes(1); expect(screen.getByRole('heading', { name: 'SW1' })).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Убрать с карты' })).toBeDisabled(); fireEvent.click(screen.getByText('Дополнительные действия')); expect(screen.getByRole('button', { name: 'Удалить объект из NetMap' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: 'Повторить обновление' })); await screen.findByText('Карта «A» пока пуста'); expect(maps.loadMap).toHaveBeenCalledTimes(4); expect(removePlacement).toHaveBeenCalledTimes(1); });
  it('does not repeat a successful continuation add when its authoritative refresh fails', async () => { const addPlacement = vi.fn().mockResolvedValue(undefined); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValueOnce(map).mockResolvedValueOnce(map).mockRejectedValueOnce(new Error('refresh failed')).mockResolvedValueOnce(map), removePlacement: vi.fn(), addPlacement, movePosition: vi.fn(), createMap: vi.fn() }; renderPage(maps); await screen.findByText('continuation'); fireEvent.click(screen.getByText('continuation')); fireEvent.click(screen.getByRole('button', { name: 'Добавить на карту' })); await screen.findByText('Объект добавлен, но карту не удалось обновить.'); expect(addPlacement).toHaveBeenCalledTimes(1); expect(screen.getByRole('button', { name: 'Добавить на карту' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: 'Повторить обновление' })); await waitFor(() => expect(screen.queryByLabelText('Быстрый инспектор')).not.toBeInTheDocument()); expect(maps.loadMap).toHaveBeenCalledTimes(4); expect(addPlacement).toHaveBeenCalledTimes(1); });
  it('does not repeat a successful equipment delete when its authoritative refresh fails', async () => { const destroy = vi.fn().mockResolvedValue(undefined); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValueOnce(map).mockResolvedValueOnce(map).mockRejectedValueOnce(new Error('refresh failed')).mockResolvedValueOnce({ ...map, placements: [] }), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() }; vi.spyOn(window, 'confirm').mockReturnValue(true); renderPage(maps, destroy); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByText('Дополнительные действия')); fireEvent.click(screen.getByRole('button', { name: 'Удалить объект из NetMap' })); await screen.findByText('Объект удалён, но карту не удалось обновить.'); expect(destroy).toHaveBeenCalledTimes(1); expect(screen.getByRole('button', { name: 'Удалить объект из NetMap' })).toBeDisabled(); expect(screen.getByRole('button', { name: 'Убрать с карты' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: 'Повторить обновление' })); await screen.findByText('Карта «A» пока пуста'); expect(maps.loadMap).toHaveBeenCalledTimes(4); expect(destroy).toHaveBeenCalledTimes(1); });
  it('does not repeat a successful cable delete when its authoritative refresh fails', async () => { const destroy = vi.fn().mockResolvedValue(undefined); const cableMap = { ...map }; const maps: any = { listMaps: vi.fn().mockResolvedValue([cableMap]), loadMap: vi.fn().mockResolvedValueOnce(cableMap).mockResolvedValueOnce(cableMap).mockRejectedValueOnce(new Error('refresh failed')).mockResolvedValueOnce({ ...cableMap, placements: [] }), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() }; vi.spyOn(window, 'confirm').mockReturnValue(true); renderPage(maps, destroy, collapsedCableDocument); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByText('Дополнительные действия')); fireEvent.click(screen.getByRole('button', { name: 'Удалить кабель и разорвать физическое соединение' })); await screen.findByText('Объект удалён, но карту не удалось обновить.'); expect(destroy).toHaveBeenCalledTimes(1); expect(screen.getByRole('button', { name: 'Удалить кабель и разорвать физическое соединение' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: 'Повторить обновление' })); await screen.findByText('Карта «A» пока пуста'); expect(maps.loadMap).toHaveBeenCalledTimes(4); expect(destroy).toHaveBeenCalledTimes(1); });
  it('acknowledges a successful placement lock locally without reloading map or projection', async () => { const setPositionLock = vi.fn().mockResolvedValue(undefined); const loadProjection = vi.fn().mockResolvedValue(doc); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), setPositionLock, createMap: vi.fn() }; renderMapPage({ dataSource: { loadProjection }, deviceDetailsDataSource: { loadDeviceDetails: vi.fn() }, savedMapDataSource: maps }, `/map?map=${A}&view=physical`); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); const mapLoads = maps.loadMap.mock.calls.length; const projectionLoads = loadProjection.mock.calls.length; fireEvent.click(await screen.findByRole('button', { name: 'Зафиксировать положение' })); await waitFor(() => expect(setPositionLock).toHaveBeenCalledWith(A, O, 'physical', true)); expect(maps.loadMap).toHaveBeenCalledTimes(mapLoads); expect(loadProjection).toHaveBeenCalledTimes(projectionLoads); expect(screen.getByRole('button', { name: 'Разблокировать положение' })).toBeInTheDocument(); });
  it('keeps the last confirmed placement lock state after a failed write', async () => { const setPositionLock = vi.fn().mockRejectedValue(new Error('lock failed')); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), setPositionLock, createMap: vi.fn() }; renderPage(maps); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(await screen.findByRole('button', { name: 'Зафиксировать положение' })); expect(await screen.findByRole('alert')).toHaveTextContent('lock failed'); expect(screen.getByRole('button', { name: 'Зафиксировать положение' })).toBeInTheDocument(); });
  it('applies size to every placement with the same Blueprint identity, not only the same immutable version', async () => {
    const presentation = (blueprintId: string, versionId: string) => ({ blueprint_presentation: { blueprint_ref: { ref_type: 'LIBRARY_RECORD', entity_type: 'ObjectBlueprint', entity_id: blueprintId }, version_ref: { ref_type: 'LIBRARY_RECORD', entity_type: 'ObjectBlueprintVersion', entity_id: versionId }, body: { kind: 'RECTANGLE', width: 100, height: 100 }, slots: [] } });
    const sibling = { ...node, id: 'sibling', label: 'SW2', attributes: { ...node.attributes, ...presentation('bp-1', 'version-2') }, source_refs: [{ ...node.source_refs[0], entity_id: 'sibling' }] };
    const different = { ...node, id: 'different', label: 'SW3', attributes: { ...node.attributes, ...presentation('bp-2', 'version-1') }, source_refs: [{ ...node.source_refs[0], entity_id: 'different' }] };
    const blueprintNode = { ...node, attributes: { ...node.attributes, ...presentation('bp-1', 'version-1') } };
    const blueprintDocument = { ...doc, nodes: [blueprintNode, sibling, different] };
    const blueprintMap = { ...map, placements: [
      { physical_object_ref: blueprintNode.source_refs[0], positions: { 'L1/PHYSICAL_OBJECT': { x: 1, y: 2, display_width: 180 } } },
      { physical_object_ref: sibling.source_refs[0], positions: { 'L1/PHYSICAL_OBJECT': { x: 3, y: 4, display_width: 220 } } },
      { physical_object_ref: different.source_refs[0], positions: { 'L1/PHYSICAL_OBJECT': { x: 5, y: 6, display_width: 260 } } },
    ] };
    const movePosition = vi.fn().mockResolvedValue(undefined);
    const maps: any = { listMaps: vi.fn().mockResolvedValue([blueprintMap]), loadMap: vi.fn().mockResolvedValue(blueprintMap), createMap: vi.fn(), movePosition, removePlacement: vi.fn(), addPlacement: vi.fn() };
    renderPage(maps, vi.fn(), blueprintDocument);
    await screen.findByText('select');
    fireEvent.click(screen.getByText('select'));
    expect(await screen.findByRole('spinbutton', { name: 'Ширина' })).toHaveValue(180);
    fireEvent.click(screen.getByRole('button', { name: 'Применить к тому же шаблону' }));
    await waitFor(() => expect(movePosition).toHaveBeenCalledTimes(2));
    expect(movePosition).toHaveBeenNthCalledWith(1, A, O, 'physical', 1, 2, 180);
    expect(movePosition).toHaveBeenNthCalledWith(2, A, 'sibling', 'physical', 3, 4, 180);
  });

  it('reloads authoritative Saved Map after a bulk size write fails without repeating acknowledged writes', async () => {
    const presentation = (versionId: string) => ({ blueprint_presentation: { blueprint_ref: { ref_type: 'LIBRARY_RECORD', entity_type: 'ObjectBlueprint', entity_id: 'bp-1' }, version_ref: { ref_type: 'LIBRARY_RECORD', entity_type: 'ObjectBlueprintVersion', entity_id: versionId }, body: { kind: 'RECTANGLE', width: 100, height: 100 }, slots: [] } });
    const sibling = { ...node, id: 'sibling', label: 'SW2', attributes: { ...node.attributes, ...presentation('version-2') }, source_refs: [{ ...node.source_refs[0], entity_id: 'sibling' }] };
    const blueprintNode = { ...node, attributes: { ...node.attributes, ...presentation('version-1') } };
    const blueprintMap = { ...map, placements: [
      { physical_object_ref: blueprintNode.source_refs[0], positions: { 'L1/PHYSICAL_OBJECT': { x: 1, y: 2, display_width: 180 } } },
      { physical_object_ref: sibling.source_refs[0], positions: { 'L1/PHYSICAL_OBJECT': { x: 3, y: 4, display_width: 220 } } },
    ] };
    const movePosition = vi.fn().mockResolvedValueOnce(undefined).mockRejectedValueOnce(new Error('size failed'));
    const loadMap = vi.fn().mockResolvedValue(blueprintMap);
    const maps: any = { listMaps: vi.fn().mockResolvedValue([blueprintMap]), loadMap, createMap: vi.fn(), movePosition, removePlacement: vi.fn(), addPlacement: vi.fn() };
    renderPage(maps, vi.fn(), { ...doc, nodes: [blueprintNode, sibling] });
    await screen.findByText('select');
    fireEvent.click(screen.getByText('select'));
    fireEvent.click(await screen.findByRole('button', { name: 'Применить к тому же шаблону' }));
    expect(await screen.findByRole('alert')).toHaveTextContent('size failed');
    expect(movePosition).toHaveBeenCalledTimes(2);
    expect(loadMap.mock.calls.length).toBeGreaterThanOrEqual(2);
  });
});
