import { describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { MapPage } from './MapPage';

vi.mock('../components/TopologyCanvas', () => ({ TopologyCanvas: (p: any) => <><button onClick={() => { p.onViewportCenterReady?.(() => ({ x: 12, y: 34 })); p.onSelectionChange({ type: 'node', item: p.document.nodes[0] }); }}>select</button><button onClick={() => { p.onViewportCenterReady?.(() => ({ x: 12, y: 34 })); p.onSelectionChange({ type: 'continuation', item: p.document.l1_off_map_continuations?.[0] }); }}>continuation</button><button onClick={() => p.onNodeCollisionRejected?.()}>collision</button></> }));
const A = 'map-a'; const O = 'object';
const node = { id: 'node', kind: 'PHYSICAL_OBJECT', label: 'SW1', attributes: { class: 'switch' }, source_refs: [{ ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: O }] };
const cableNode = { ...node, id: 'cable-node', label: 'C1', attributes: { class: 'cable' }, source_refs: [{ ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: 'cable' }] };
const continuation = { id: 'c', local_node_id: 'node', local_physical_object_ref: node.source_refs[0], local_connection_point_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'ConnectionPoint', entity_id: 'p' }, local_connection_point_display_name: 'A01', cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: 'cable' }, cable_display_name: 'C1', remote_physical_object_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: 'remote' }, remote_display_name: 'PP1', remote_connection_point_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'ConnectionPoint', entity_id: 'rp' }, remote_connection_point_display_name: 'B01', source_refs: [] };
const doc: any = { schema_version: '1.0', layer: 'L1', detail_level: 'PHYSICAL_OBJECT', nodes: [node], edges: [], gaps: [], warnings: [], l1_off_map_continuations: [continuation] };
const map = { map_ref: { entity_type: 'SavedMap', entity_id: A }, name: 'A', placements: [{ physical_object_ref: node.source_refs[0], positions: { 'L1/PHYSICAL_OBJECT': { x: 1, y: 2 } } }] };
const renderPage = (maps: any, remove = vi.fn(), document = doc) => render(<MemoryRouter initialEntries={[`/map?map=${A}&view=physical`]}><MapPage dataSource={{ loadProjection: vi.fn((request) => Promise.resolve(request.scope.include_entities[0]?.entity_id === 'remote' ? { ...document, nodes: [{ ...node, id: 'remote-node', label: 'PP1', source_refs: [{ ...node.source_refs[0], entity_id: 'remote' }] }] } : document)) }} deviceDetailsDataSource={{ loadDeviceDetails: vi.fn() }} savedMapDataSource={maps} physicalObjectDeleteDataSource={{ deletePhysicalObject: remove }} /></MemoryRouter>);

describe('MapPage mutation lifecycles', () => {
  it('shows local collision feedback without starting a position write', async () => { const movePosition = vi.fn(); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition, setPositionLock: vi.fn(), createMap: vi.fn() }; renderPage(maps); await screen.findByText('collision'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByText('collision')); expect(await screen.findByRole('alert')).toHaveTextContent('Объекты нельзя размещать друг на друге.'); expect(movePosition).not.toHaveBeenCalled(); expect(screen.getByRole('heading', { name: 'SW1' })).toBeInTheDocument(); });
  it('keeps selection and reports remove write failure', async () => { const removePlacement = vi.fn().mockRejectedValue(new Error('remove failed')); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement, addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() }; renderPage(maps); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByRole('button', { name: 'Убрать с карты' })); expect(await screen.findByRole('alert')).toHaveTextContent('remove failed'); expect(screen.getByRole('heading', { name: 'SW1' })).toBeInTheDocument(); });
  it('allows a continuation write retry after an add failure', async () => { const addPlacement = vi.fn().mockRejectedValue(new Error('add failed')); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement: vi.fn(), addPlacement, movePosition: vi.fn(), createMap: vi.fn() }; renderPage(maps); await screen.findByText('continuation'); fireEvent.click(screen.getByText('continuation')); const add = screen.getByRole('button', { name: 'Добавить на карту' }); fireEvent.click(add); expect(await screen.findByRole('alert')).toHaveTextContent('add failed'); expect(add).not.toBeDisabled(); fireEvent.click(add); await waitFor(() => expect(addPlacement).toHaveBeenCalledTimes(2)); });
  it('keeps inspector on delete write failure', async () => { const remove = vi.fn().mockRejectedValue(new Error('delete failed')); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() }; vi.spyOn(window, 'confirm').mockReturnValue(true); render(<MemoryRouter initialEntries={[`/map?map=${A}&view=physical`]}><MapPage dataSource={{ loadProjection: vi.fn().mockResolvedValue(doc) }} deviceDetailsDataSource={{ loadDeviceDetails: vi.fn() }} savedMapDataSource={maps} physicalObjectDeleteDataSource={{ deletePhysicalObject: remove }} /></MemoryRouter>); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByRole('button', { name: 'Удалить объект из NetMap' })); expect(await screen.findByRole('alert')).toHaveTextContent('delete failed'); });
  it('does not repeat a successful remove when its authoritative refresh fails', async () => { const removePlacement = vi.fn().mockResolvedValue(undefined); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValueOnce(map).mockResolvedValueOnce(map).mockRejectedValueOnce(new Error('refresh failed')).mockResolvedValueOnce({ ...map, placements: [] }), removePlacement, addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() }; renderPage(maps); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByRole('button', { name: 'Убрать с карты' })); await screen.findByText('Объект убран с карты, но карту не удалось обновить.'); expect(removePlacement).toHaveBeenCalledTimes(1); expect(screen.getByRole('heading', { name: 'SW1' })).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Убрать с карты' })).toBeDisabled(); fireEvent.click(screen.getByText('Дополнительные действия')); expect(screen.getByRole('button', { name: 'Удалить объект из NetMap' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: 'Повторить обновление' })); await screen.findByText('Карта «A» пока пуста'); expect(maps.loadMap).toHaveBeenCalledTimes(4); expect(removePlacement).toHaveBeenCalledTimes(1); });
  it('does not repeat a successful continuation add when its authoritative refresh fails', async () => { const addPlacement = vi.fn().mockResolvedValue(undefined); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValueOnce(map).mockResolvedValueOnce(map).mockRejectedValueOnce(new Error('refresh failed')).mockResolvedValueOnce(map), removePlacement: vi.fn(), addPlacement, movePosition: vi.fn(), createMap: vi.fn() }; renderPage(maps); await screen.findByText('continuation'); fireEvent.click(screen.getByText('continuation')); fireEvent.click(screen.getByRole('button', { name: 'Добавить на карту' })); await screen.findByText('Объект добавлен, но карту не удалось обновить.'); expect(addPlacement).toHaveBeenCalledTimes(1); expect(screen.getByRole('button', { name: 'Добавить на карту' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: 'Повторить обновление' })); await waitFor(() => expect(screen.queryByLabelText('Быстрый инспектор')).not.toBeInTheDocument()); expect(maps.loadMap).toHaveBeenCalledTimes(4); expect(addPlacement).toHaveBeenCalledTimes(1); });
  it('does not repeat a successful equipment delete when its authoritative refresh fails', async () => { const destroy = vi.fn().mockResolvedValue(undefined); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValueOnce(map).mockResolvedValueOnce(map).mockRejectedValueOnce(new Error('refresh failed')).mockResolvedValueOnce({ ...map, placements: [] }), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() }; vi.spyOn(window, 'confirm').mockReturnValue(true); renderPage(maps, destroy); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByText('Дополнительные действия')); fireEvent.click(screen.getByRole('button', { name: 'Удалить объект из NetMap' })); await screen.findByText('Объект удалён, но карту не удалось обновить.'); expect(destroy).toHaveBeenCalledTimes(1); expect(screen.getByRole('button', { name: 'Удалить объект из NetMap' })).toBeDisabled(); expect(screen.getByRole('button', { name: 'Убрать с карты' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: 'Повторить обновление' })); await screen.findByText('Карта «A» пока пуста'); expect(maps.loadMap).toHaveBeenCalledTimes(4); expect(destroy).toHaveBeenCalledTimes(1); });
  it('does not repeat a successful cable delete when its authoritative refresh fails', async () => { const destroy = vi.fn().mockResolvedValue(undefined); const cableMap = { ...map, placements: [{ ...map.placements[0], physical_object_ref: cableNode.source_refs[0] }] }; const cableDoc = { ...doc, nodes: [cableNode] }; const maps: any = { listMaps: vi.fn().mockResolvedValue([cableMap]), loadMap: vi.fn().mockResolvedValueOnce(cableMap).mockResolvedValueOnce(cableMap).mockRejectedValueOnce(new Error('refresh failed')).mockResolvedValueOnce({ ...cableMap, placements: [] }), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() }; vi.spyOn(window, 'confirm').mockReturnValue(true); renderPage(maps, destroy, cableDoc); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByText('Дополнительные действия')); fireEvent.click(screen.getByRole('button', { name: 'Удалить кабель и разорвать физическое соединение' })); await screen.findByText('Объект удалён, но карту не удалось обновить.'); expect(destroy).toHaveBeenCalledTimes(1); expect(screen.getByRole('button', { name: 'Удалить кабель и разорвать физическое соединение' })).toBeDisabled(); expect(screen.getByRole('button', { name: 'Убрать с карты' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: 'Повторить обновление' })); await screen.findByText('Карта «A» пока пуста'); expect(maps.loadMap).toHaveBeenCalledTimes(4); expect(destroy).toHaveBeenCalledTimes(1); });
  it('acknowledges a successful placement lock locally without reloading map or projection', async () => { const setPositionLock = vi.fn().mockResolvedValue(undefined); const loadProjection = vi.fn().mockResolvedValue(doc); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), setPositionLock, createMap: vi.fn() }; render(<MemoryRouter initialEntries={[`/map?map=${A}&view=physical`]}><MapPage dataSource={{ loadProjection }} deviceDetailsDataSource={{ loadDeviceDetails: vi.fn() }} savedMapDataSource={maps} /></MemoryRouter>); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); const mapLoads = maps.loadMap.mock.calls.length; const projectionLoads = loadProjection.mock.calls.length; fireEvent.click(await screen.findByRole('button', { name: 'Зафиксировать положение' })); await waitFor(() => expect(setPositionLock).toHaveBeenCalledWith(A, O, 'physical', true)); expect(maps.loadMap).toHaveBeenCalledTimes(mapLoads); expect(loadProjection).toHaveBeenCalledTimes(projectionLoads); expect(screen.getByRole('button', { name: 'Разблокировать положение' })).toBeInTheDocument(); });
  it('keeps the last confirmed placement lock state after a failed write', async () => { const setPositionLock = vi.fn().mockRejectedValue(new Error('lock failed')); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), setPositionLock, createMap: vi.fn() }; renderPage(maps); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(await screen.findByRole('button', { name: 'Зафиксировать положение' })); expect(await screen.findByRole('alert')).toHaveTextContent('lock failed'); expect(screen.getByRole('button', { name: 'Зафиксировать положение' })).toBeInTheDocument(); });
});
