import { ReactFlowProvider } from '@xyflow/react';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { QuickInspector } from '../components/QuickInspector';
import { TraceCommandBar } from '../components/TraceCommandBar';
import { TopologyCanvas } from '../components/TopologyCanvas';
import { ViewState } from '../components/ViewState';
import { displayNodeLabel } from '../topology/presentation';
import { nodeForPhysicalObject, physicalObjectIdForNode, physicalObjectIdForSelection, projectionRequestFor, type TopologyViewMode } from '../topology/projection';
import type { SavedMap, SavedMapDataSource, SavedMapSummary, SavedMapView, SavedMapViewKey } from '../topology/savedMapTypes';
import type { DeviceDetailsDataSource } from '../topology/deviceDetailsTypes';
import type { InterfacePhysicalTraceDataSource } from '../topology/interfacePhysicalTraceTypes';
import type { InterfacePhysicalTraceArtifact } from '../topology/interfacePhysicalTraceTypes';
import { physicalTraceOverlayFor } from '../topology/interfacePhysicalTraceOverlay';
import type { TopologyLayoutStore } from '../topology/layoutStore';
import type { PhysicalObjectDeleteDataSource } from '../topology/physicalObjectDeleteTypes';
import type { TopologyDataSource, TopologyProjectionDocument, TopologyProjectionNode, TopologySelection } from '../topology/types';

interface MapPageProps { dataSource: TopologyDataSource; deviceDetailsDataSource: DeviceDetailsDataSource; savedMapDataSource?: SavedMapDataSource; physicalObjectDeleteDataSource?: PhysicalObjectDeleteDataSource; traceDataSource?: InterfacePhysicalTraceDataSource; topologyLayoutStore?: TopologyLayoutStore }
interface SceneDocument { sceneKey: string; document: TopologyProjectionDocument }
const view = (value: string | null): TopologyViewMode => value === 'physical' ? 'physical' : 'logical';
const savedMapViewKey = (value: SavedMapView): SavedMapViewKey => value === 'physical' ? 'L1/PHYSICAL_OBJECT' : 'L2/DEVICE';
const natural = (a: string, b: string) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' });
export const mapCandidateChoices = (nodes: TopologyProjectionNode[], placedIds: string[]) => nodes.map((node) => ({ id: physicalObjectIdForNode(node), label: displayNodeLabel(node), className: node.attributes.class })).filter((item): item is { id: string; label: string; className: unknown } => item.id !== null && item.className !== 'cable' && !placedIds.includes(item.id)).sort((a, b) => natural(a.label, b.label));

export function MapPage({ dataSource, deviceDetailsDataSource, savedMapDataSource, physicalObjectDeleteDataSource, traceDataSource }: MapPageProps) {
  const [params, setParams] = useSearchParams(); const mapId = params.get('map'); const viewMode = view(params.get('view'));
  const [maps, setMaps] = useState<SavedMapSummary[] | null>(null); const [map, setMap] = useState<SavedMap | null>(null); const [sceneDocument, setSceneDocument] = useState<SceneDocument | null>(null); const [logicalDocument, setLogicalDocument] = useState<TopologyProjectionDocument | null>(null); const [traceArtifact, setTraceArtifact] = useState<InterfacePhysicalTraceArtifact | null>(null); const [selection, setSelection] = useState<TopologySelection>(null); const [error, setError] = useState<string | null>(null); const [creating, setCreating] = useState(false); const [name, setName] = useState(''); const [candidates, setCandidates] = useState<TopologyProjectionDocument | null>(null);
  const selectedMapId = useRef<string | null>(mapId); selectedMapId.current = mapId;
  const legacy = !savedMapDataSource;
  const presentationSceneKey = !legacy && mapId ? `${mapId}/${viewMode}` : `legacy/${viewMode}`;
  const activeMap = !legacy && map?.map_ref.entity_id === mapId ? map : null;
  const document = sceneDocument?.sceneKey === presentationSceneKey ? sceneDocument.document : null;
  const selectMap = useCallback((id: string) => { setSelection(null); setSceneDocument(null); setParams((current) => { const next = new URLSearchParams(current); next.set('map', id); next.set('view', next.get('view') ?? 'physical'); next.delete('focus'); return next; }); }, [setParams]);
  const reloadMap = useCallback(async () => { if (!savedMapDataSource || !mapId) return; const detail = await savedMapDataSource.loadMap(mapId); if (selectedMapId.current === mapId) setMap(detail); return detail; }, [mapId, savedMapDataSource]);
  useEffect(() => { if (!savedMapDataSource) return; let active = true; void savedMapDataSource.listMaps().then((items) => { if (!active) return; const sorted = [...items].sort((a, b) => natural(a.name, b.name)); setMaps(sorted); if (!mapId && sorted[0]) selectMap(sorted[0].map_ref.entity_id); }, (reason) => active && setError(reason instanceof Error ? reason.message : 'Не удалось загрузить карты')); return () => { active = false; }; }, [mapId, savedMapDataSource, selectMap]);
  useEffect(() => { if (!savedMapDataSource || !mapId) { setMap(null); setSceneDocument(null); return; } if (maps && !maps.some((item) => item.map_ref.entity_id === mapId)) { setMap(null); setSceneDocument(null); setSelection(null); setError('Выбранная карта не найдена.'); return; } let active = true; setError(null); void savedMapDataSource.loadMap(mapId).then((detail) => { if (active) setMap(detail); }, (reason) => active && setError(reason instanceof Error ? reason.message : 'Не удалось загрузить карту')); return () => { active = false; }; }, [mapId, maps, savedMapDataSource]);
  const ids = activeMap?.placements.map((item) => item.physical_object_ref.entity_id) ?? [];
  // Coordinates are deliberately excluded: topology projection membership is only the placed object set.
  const placementMembershipKey = ids.join(',');
  const hasLoadedMap = legacy || Boolean(activeMap);
  const [authoritativePositionRevision, setAuthoritativePositionRevision] = useState(0);
  useEffect(() => { if (savedMapDataSource && (!hasLoadedMap || ids.length === 0)) { setSceneDocument(null); return; } let active = true; void dataSource.loadProjection(projectionRequestFor(viewMode, savedMapDataSource ? ids : undefined, Boolean(savedMapDataSource && viewMode === 'physical'))).then((next) => { if (active) setSceneDocument({ sceneKey: presentationSceneKey, document: next }); }, (reason) => active && setError(reason instanceof Error ? reason.message : 'Не удалось загрузить projection')); return () => { active = false; }; }, [dataSource, hasLoadedMap, placementMembershipKey, presentationSceneKey, savedMapDataSource, viewMode]);
  useEffect(() => { if (savedMapDataSource ? !hasLoadedMap : viewMode === 'logical') return; void dataSource.loadProjection(projectionRequestFor('logical')).then(setLogicalDocument, () => setLogicalDocument(null)); }, [dataSource, hasLoadedMap, mapId, savedMapDataSource, viewMode]);
  useEffect(() => { const focus = params.get('focus'); if (!document || !focus) return; const node = nodeForPhysicalObject(document.nodes, focus); setSelection(node ? { type: 'node', item: node } : null); }, [document, params]);
  useEffect(() => { if (!document) return; setSelection((current) => { if (!current) return null; if (current.type === 'edge') return document.edges.some((edge) => edge.id === current.item.id) ? current : null; if (current.type === 'continuation') return document.l1_off_map_continuations?.some((item) => item.id === current.item.id) ? current : null; const id = physicalObjectIdForSelection(current); const node = id ? nodeForPhysicalObject(document.nodes, id) : null; return node ? { type: 'node', item: node } : null; }); }, [document]);
  const create = async () => { if (!savedMapDataSource || !name.trim()) return; try { const created = await savedMapDataSource.createMap(name.trim()); setMaps([...await savedMapDataSource.listMaps()].sort((a, b) => natural(a.name, b.name))); setName(''); setCreating(false); selectMap(created.map_ref.entity_id); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось создать карту'); } };
  const loadCandidates = async () => { try { setCandidates(await dataSource.loadProjection(projectionRequestFor('physical'))); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось загрузить объекты'); } };
  const add = async (id: string) => { if (!savedMapDataSource || !mapId) return; const n = ids.length; await savedMapDataSource.addPlacement(mapId, id, 80 + n % 5 * 180, 80 + Math.floor(n / 5) * 120); await reloadMap(); setCandidates(null); };
  const move = async (id: string, p: { x: number; y: number }) => { if (!savedMapDataSource || !mapId) return; const positionKey = savedMapViewKey(viewMode); try { await savedMapDataSource.movePosition(mapId, id, viewMode, p.x, p.y); if (selectedMapId.current === mapId) setMap((current) => current?.map_ref.entity_id === mapId ? { ...current, placements: current.placements.map((placement) => placement.physical_object_ref.entity_id === id ? { ...placement, positions: { ...placement.positions, [positionKey]: { x: p.x, y: p.y } } } : placement) } : current); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось сохранить позицию'); await reloadMap(); if (selectedMapId.current === mapId) setAuthoritativePositionRevision((revision) => revision + 1); } };
  const remove = async (id: string) => { if (!savedMapDataSource || !mapId) return; await savedMapDataSource.removePlacement(mapId, id); setSelection(null); await reloadMap(); };
  const positions = useMemo(() => { const positionKey = savedMapViewKey(viewMode); return Object.fromEntries((activeMap?.placements ?? []).map((item) => { const node = nodeForPhysicalObject(document?.nodes ?? [], item.physical_object_ref.entity_id); const position = item.positions[positionKey]; return node && position ? [node.id, position] : null; }).filter((item): item is [string, { x: number; y: number }] => item !== null)); }, [activeMap, document, viewMode]);
  const draggableNodeIds = useMemo(() => new Set((activeMap?.placements ?? []).map((item) => nodeForPhysicalObject(document?.nodes ?? [], item.physical_object_ref.entity_id)?.id).filter((id): id is string => Boolean(id))), [activeMap, document]);
  const choices = mapCandidateChoices(candidates?.nodes ?? [], ids);
  return <main className="map-page"><div className="map-page__toolbar topology-mode-switch"><label>Карты: {legacy ? '—' : <select aria-label="Карты" value={mapId ?? ''} onChange={(e) => selectMap(e.target.value)}><option value="" disabled>Выберите карту</option>{(maps ?? []).map((item) => <option key={item.map_ref.entity_id} value={item.map_ref.entity_id}>{item.name}</option>)}</select>}</label>{!legacy && <><button type="button" onClick={() => setCreating(true)}>+ Новая карта</button><button type="button" onClick={() => void loadCandidates()} disabled={!activeMap}>+ Добавить объект</button></>}<button type="button" aria-pressed={viewMode === 'logical'} onClick={() => setParams((p) => { const n = new URLSearchParams(p); n.set('view', 'logical'); return n; })}>Логическая</button><button type="button" aria-pressed={viewMode === 'physical'} onClick={() => setParams((p) => { const n = new URLSearchParams(p); n.set('view', 'physical'); return n; })}>Физическая</button></div>
    {creating && <section className="map-dialog" role="dialog" aria-modal="true" aria-label="Новая карта"><div className="map-dialog__surface"><label>Название<input autoFocus value={name} onChange={(e) => setName(e.target.value)} /></label><button type="button" onClick={() => setCreating(false)}>Отмена</button><button type="button" onClick={() => void create()}>Создать</button></div></section>}
    {candidates && <section className="map-dialog" role="dialog" aria-modal="true" aria-label="Добавить объект"><div className="map-dialog__surface"><h2>Добавить объект</h2>{choices.map((item) => <button key={item.id} type="button" onClick={() => void add(item.id)}>{item.label}</button>)}{choices.length === 0 && <p>Все доступные объекты уже на карте.</p>}<button type="button" onClick={() => setCandidates(null)}>Закрыть</button></div></section>}
    {error && <p role="alert">{error}</p>}{document && params.get('focus') && !nodeForPhysicalObject(document.nodes, params.get('focus')!) && <p>Объект с указанной canonical-ссылкой отсутствует в этой проекции.</p>}{!legacy && maps?.length === 0 && <section><h2>Создайте первую карту</h2><button onClick={() => setCreating(true)}>Создать карту</button></section>}{!legacy && activeMap && ids.length === 0 && <section><h2>Карта «{activeMap.name}» пока пуста</h2><button onClick={() => void loadCandidates()}>Добавить объект</button></section>}
    {(legacy || (activeMap && ids.length > 0)) && <><TraceCommandBar logicalDocument={logicalDocument} deviceDetailsDataSource={deviceDetailsDataSource} traceDataSource={traceDataSource} traceArtifact={traceArtifact} onTraceArtifact={(artifact) => { setTraceArtifact(artifact); if (artifact?.verdict === 'REACHABLE') setParams((current) => { const next = new URLSearchParams(current); next.set('view', 'physical'); return next; }); }} /><section className="map-page__canvas">{!document && <ViewState kind="loading" />}{document?.nodes.length === 0 && <ViewState kind="empty" />}{document && document.nodes.length > 0 && <ReactFlowProvider><TopologyCanvas document={document} selection={selection} onSelectionChange={setSelection} sceneKey={presentationSceneKey} positionOverrides={!legacy ? positions : undefined} draggableNodeIds={!legacy ? draggableNodeIds : undefined} authoritativePositionRevision={authoritativePositionRevision} onPhysicalNodeDragStop={!legacy ? move : undefined} disableAutoLayout={!legacy} traceOverlay={physicalTraceOverlayFor(traceArtifact, document)} /></ReactFlowProvider>}</section></>}
    <QuickInspector document={document} selection={selection} onSelectNode={(node) => setSelection({ type: 'node', item: node })} onClose={() => setSelection(null)} onAddContinuationToMap={!legacy && viewMode === 'physical' ? async (id) => add(id) : undefined} onRemoveFromMap={!legacy && viewMode === 'physical' && ids.includes(physicalObjectIdForSelection(selection) ?? '') ? remove : undefined} onDeletePhysicalObject={physicalObjectDeleteDataSource ? async (id) => { await physicalObjectDeleteDataSource.deletePhysicalObject(id); setSelection(null); await reloadMap(); } : undefined} />
  </main>;
}
