import { describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { MapPage } from './MapPage';

vi.mock('../components/TopologyCanvas', () => ({ TopologyCanvas: (p: any) => <><button onClick={() => { p.onViewportCenterReady?.(() => ({ x: 12, y: 34 })); p.onSelectionChange({ type: 'node', item: p.document.nodes[0] }); }}>select</button><button onClick={() => { p.onViewportCenterReady?.(() => ({ x: 12, y: 34 })); p.onSelectionChange({ type: 'continuation', item: p.document.l1_off_map_continuations?.[0] }); }}>continuation</button></> }));
const A = 'map-a'; const O = 'object';
const node = { id: 'node', kind: 'PHYSICAL_OBJECT', label: 'SW1', attributes: { class: 'switch' }, source_refs: [{ ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: O }] };
const continuation = { id: 'c', local_node_id: 'node', local_physical_object_ref: node.source_refs[0], local_connection_point_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'ConnectionPoint', entity_id: 'p' }, local_connection_point_display_name: 'A01', cable_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: 'cable' }, cable_display_name: 'C1', remote_physical_object_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'PhysicalObject', entity_id: 'remote' }, remote_display_name: 'PP1', remote_connection_point_ref: { ref_type: 'CANONICAL_FACT', entity_type: 'ConnectionPoint', entity_id: 'rp' }, remote_connection_point_display_name: 'B01', source_refs: [] };
const doc: any = { schema_version: '1.0', layer: 'L1', detail_level: 'PHYSICAL_OBJECT', nodes: [node], edges: [], gaps: [], warnings: [], l1_off_map_continuations: [continuation] };
const map = { map_ref: { entity_type: 'SavedMap', entity_id: A }, name: 'A', placements: [{ physical_object_ref: node.source_refs[0], positions: { 'L1/PHYSICAL_OBJECT': { x: 1, y: 2 } } }] };
const renderPage = (maps: any) => render(<MemoryRouter initialEntries={[`/map?map=${A}&view=physical`]}><MapPage dataSource={{ loadProjection: vi.fn().mockResolvedValue(doc) }} deviceDetailsDataSource={{ loadDeviceDetails: vi.fn() }} savedMapDataSource={maps} physicalObjectDeleteDataSource={{ deletePhysicalObject: vi.fn() }} /></MemoryRouter>);

describe('MapPage mutation lifecycles', () => {
  it('keeps selection and reports remove write failure', async () => { const removePlacement = vi.fn().mockRejectedValue(new Error('remove failed')); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement, addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() }; renderPage(maps); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByRole('button', { name: 'Убрать с карты' })); expect(await screen.findByRole('alert')).toHaveTextContent('remove failed'); expect(screen.getByRole('heading', { name: 'SW1' })).toBeInTheDocument(); });
  it('allows a continuation write retry after an add failure', async () => { const addPlacement = vi.fn().mockRejectedValue(new Error('add failed')); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement: vi.fn(), addPlacement, movePosition: vi.fn(), createMap: vi.fn() }; renderPage(maps); await screen.findByText('continuation'); fireEvent.click(screen.getByText('continuation')); const add = screen.getByRole('button', { name: 'Добавить на карту' }); fireEvent.click(add); expect(await screen.findByRole('alert')).toHaveTextContent('add failed'); expect(add).not.toBeDisabled(); fireEvent.click(add); expect(addPlacement).toHaveBeenCalledTimes(2); });
  it('keeps inspector on delete write failure', async () => { const remove = vi.fn().mockRejectedValue(new Error('delete failed')); const maps: any = { listMaps: vi.fn().mockResolvedValue([map]), loadMap: vi.fn().mockResolvedValue(map), removePlacement: vi.fn(), addPlacement: vi.fn(), movePosition: vi.fn(), createMap: vi.fn() }; vi.spyOn(window, 'confirm').mockReturnValue(true); render(<MemoryRouter initialEntries={[`/map?map=${A}&view=physical`]}><MapPage dataSource={{ loadProjection: vi.fn().mockResolvedValue(doc) }} deviceDetailsDataSource={{ loadDeviceDetails: vi.fn() }} savedMapDataSource={maps} physicalObjectDeleteDataSource={{ deletePhysicalObject: remove }} /></MemoryRouter>); await screen.findByText('select'); fireEvent.click(screen.getByText('select')); fireEvent.click(screen.getByRole('button', { name: 'Удалить объект из NetMap' })); expect(await screen.findByRole('alert')).toHaveTextContent('delete failed'); });
});
