import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export const locales = ['ru', 'en'] as const;
export type Locale = typeof locales[number];
export const localeStorageKey = 'netmap.locale';

const messages = {
  ru: {
    'language.label': 'Язык', 'language.ru': 'Русский', 'language.en': 'English',
    'nav.primary': 'Основная навигация', 'nav.map': 'Карта', 'nav.infrastructure': 'Инфраструктура', 'nav.objects': 'Объекты', 'nav.library': 'Библиотека', 'nav.blueprints': 'Шаблоны объектов',
    'health.checking': 'Проверка backend', 'health.healthy': 'Backend доступен', 'health.unavailable': 'Backend недоступен',
    'view.loading.title': 'Загружаем topology projection', 'view.loading.body': 'Подготавливаем логическую схему…', 'view.empty.title': 'В этом scope пока пусто', 'view.empty.body': 'Projection не содержит устройств или связей.', 'view.error.title': 'Не удалось загрузить схему', 'view.error.body': 'Источник topology projection вернул ошибку.', 'action.retry': 'Повторить',
    'catalog.untype': 'Без типа', 'catalog.loading.title': 'Загружаем каталог', 'catalog.loading.body': 'Получаем инвентарный список оборудования и кабелей…', 'catalog.error.title': 'Не удалось загрузить каталог', 'map.geometryUnavailable': 'Не удалось определить размеры объекта для размещения.',
    'map.maps': 'Карты', 'map.choose': 'Выберите карту', 'map.new': 'Новая карта', 'map.delete': 'Удалить карту', 'map.add': 'Добавить на карту', 'map.connectPorts': 'Соединить порты', 'map.logical': 'Логическая', 'map.physical': 'Физическая', 'map.createTitle': 'Новая карта', 'map.name': 'Название', 'map.create': 'Создать', 'map.cancel': 'Отмена', 'map.empty.title': 'Создайте первую карту', 'map.empty.active': 'Карта «{name}» пока пуста', 'map.delete.confirm': 'Удалить карту «{name}»?', 'map.delete.description': 'Будут удалены только размещения, позиции и трассы этой карты. Физические объекты и каноническая топология останутся без изменений.', 'map.deleting': 'Удаляем карту…', 'map.refreshing': 'Обновляем список карт…', 'map.retryRefresh': 'Повторить обновление', 'map.wiring.source': 'Выберите исходный свободный порт', 'map.wiring.target': 'Выберите конечный свободный порт', 'map.wiring.clickRoute': 'Клик по свободному полю добавляет точку трассы.', 'map.wiring.sourceLabel': 'Источник: {object} / {port}', 'map.wiring.destinationLabel': 'Назначение: {object} / {port}', 'map.wiring.points': 'Точек трассы: {count}', 'map.wiring.deletePoint': 'Удалить точку трассы', 'map.wiring.cableName': 'Название кабеля', 'map.back': 'Назад', 'map.creating': 'Создаём…', 'map.createCable': 'Создать кабель', 'map.savingRoute': 'Сохраняем трассу…', 'map.routeFailed': 'Кабель создан, но трассу не удалось сохранить.', 'map.retrySaveRoute': 'Повторить сохранение трассы', 'map.wiringRefreshFailed': 'Кабель и трасса сохранены, но карту не удалось обновить.',
    'insert.loading': 'Загружаем оборудование…', 'insert.resolving': 'Определяем место на карте…', 'insert.unavailable': 'Объект недоступен для размещения.', 'insert.search': 'Поиск', 'insert.searchEquipment': 'Поиск оборудования', 'insert.noneCreated': 'Оборудование пока не создано.', 'insert.allPlaced': 'Всё оборудование уже размещено на этой карте.', 'insert.noResults': 'По заданному запросу ничего не найдено.', 'insert.saving': 'Добавляем на карту…', 'action.add': 'Добавить', 'action.close': 'Закрыть',
    'trace.label': 'L1 трассировка PhysicalObject', 'trace.source': 'Откуда', 'trace.destination': 'Куда', 'trace.sourcePort': 'Порт источника', 'trace.destinationPort': 'Порт назначения', 'trace.anyPort': 'Любой порт', 'trace.selectObject': 'Выберите PhysicalObject', 'trace.level': 'Уровень: Physical / L1', 'trace.run': 'Трассировать', 'trace.result': 'Результат L1 trace', 'trace.reachable': 'Физический L1-путь доказан', 'trace.unknown': 'UNKNOWN: физический L1-путь не доказан', 'trace.alternatives': 'Доказанных альтернатив: {count}', 'trace.showAlternative': 'Показать альтернативу', 'trace.alternative': 'Альтернатива {index}', 'trace.cycles': 'Обнаружены циклы: {cycles}', 'trace.gaps': 'Gaps: {gaps}', 'trace.warnings': 'Warnings: {warnings}', 'trace.clear': 'Сбросить трассировку', 'trace.portLoadFailed': 'Не удалось загрузить порты: {error}. Можно трассировать с «Любой порт».', 'trace.inventoryLoadFailed': 'Не удалось загрузить инвентарь оборудования.', 'trace.datasourceUnavailable': 'L1 trace datasource пока недоступен.', 'trace.selectEndpoints': 'Выберите PhysicalObject для «Откуда» и «Куда».', 'trace.failed': 'Не удалось выполнить L1 trace.',
    'canvas.layoutFailed': 'Не удалось расположить топологию', 'canvas.layouting': 'Располагаем топологию…', 'canvas.physical': 'Физическая схема сети', 'canvas.logical': 'Логическая схема сети', 'canvas.autoLayout': 'Авторазмещение', 'canvas.minimap': 'Мини-карта',
    'action.cancel': 'Отменить', 'map.collision': 'Объекты нельзя размещать друг на друге.', 'map.removeRefreshFailed': 'Объект убран с карты, но карту не удалось обновить.', 'map.addRefreshFailed': 'Объект добавлен, но карту не удалось обновить.', 'map.deleteRefreshFailed': 'Объект удалён, но карту не удалось обновить.', 'inspector.label': 'Быстрый инспектор', 'inspector.close': 'Закрыть инспектор', 'inspector.technical': 'Технические детали', 'inspector.offMap': 'ВНЕ КАРТЫ', 'inspector.connected': 'Подключено:', 'inspector.cable': 'КАБЕЛЬ', 'inspector.networkObject': 'СЕТЕВОЙ ОБЪЕКТ', 'inspector.connection': 'Связь', 'inspector.open': 'Открыть объект', 'inspector.remove': 'Убрать с карты', 'inspector.actions': 'Дополнительные действия', 'inspector.deleteObject': 'Удалить объект из NetMap', 'inspector.deleteCable': 'Удалить кабель и разорвать физическое соединение', 'inspector.lock': 'Зафиксировать положение', 'inspector.unlock': 'Разблокировать положение', 'inspector.loadingCable': 'Загружаем проверенные концы кабеля…', 'inspector.cableUnresolved': 'Концы кабеля не удалось однозначно определить.', 'inspector.cableUnavailable': 'Проверенные данные кабеля недоступны.', 'inspector.route': 'Трасса на карте', 'inspector.routePoints': 'Точек: {count}', 'inspector.noRoute': 'Пользовательская трасса не задана', 'inspector.editRoute': 'Редактировать трассу', 'inspector.resetRoute': 'Сбросить трассу', 'inspector.routeResetFailed': 'Трасса сброшена, но карту не удалось обновить.', 'inspector.routeEditHelp': 'Перетащите точку или нажмите на участок трассы, чтобы вставить новую.', 'inspector.deleteSelectedPoint': 'Удалить выбранную точку', 'inspector.saveRoute': 'Сохранить трассу', 'inspector.loadingConnections': 'Загружаем физические подключения…', 'inspector.noPorts': 'Портов нет', 'inspector.portSummary': '{ports} портов · {attached} подключено · {free} свободно', 'inspector.portOccupancyUnknown': '{ports} порта · Занятость не определена', 'inspector.interfaces': 'Сетевых интерфейсов: {count}', 'inspector.noConnections': 'Физических подключений нет.', 'inspector.unresolvedConnection': 'Физическая связь не разрешена', 'inspector.remoteObject': 'Удалённый объект', 'inspector.port': 'порт', 'inspector.viaCable': ' через {cable}', 'inspector.moreConnections': 'Ещё {count} подключений', 'inspector.noCanonicalRef': 'У объекта нет однозначной canonical-ссылки.', 'inspector.unknownObject': 'Неизвестный объект',
  },
  en: {
    'language.label': 'Language', 'language.ru': 'Русский', 'language.en': 'English',
    'nav.primary': 'Primary navigation', 'nav.map': 'Map', 'nav.infrastructure': 'Infrastructure', 'nav.objects': 'Objects', 'nav.library': 'Library', 'nav.blueprints': 'Object blueprints',
    'health.checking': 'Checking backend', 'health.healthy': 'Backend available', 'health.unavailable': 'Backend unavailable',
    'view.loading.title': 'Loading topology projection', 'view.loading.body': 'Preparing the logical topology…', 'view.empty.title': 'Nothing in this scope yet', 'view.empty.body': 'The projection contains no devices or connections.', 'view.error.title': 'Could not load topology', 'view.error.body': 'The topology projection source returned an error.', 'action.retry': 'Retry',
    'catalog.untype': 'No type', 'catalog.loading.title': 'Loading catalog', 'catalog.loading.body': 'Loading the equipment and cable inventory…', 'catalog.error.title': 'Could not load catalog', 'map.geometryUnavailable': 'Could not determine the object dimensions for placement.',
    'map.maps': 'Maps', 'map.choose': 'Choose a map', 'map.new': 'New map', 'map.delete': 'Delete map', 'map.add': 'Add to map', 'map.connectPorts': 'Connect ports', 'map.logical': 'Logical', 'map.physical': 'Physical', 'map.createTitle': 'New map', 'map.name': 'Name', 'map.create': 'Create', 'map.cancel': 'Cancel', 'map.empty.title': 'Create your first map', 'map.empty.active': 'Map “{name}” is empty', 'map.delete.confirm': 'Delete map “{name}”?', 'map.delete.description': 'Only this map’s placements, positions, and routes will be deleted. Physical objects and canonical topology will remain unchanged.', 'map.deleting': 'Deleting map…', 'map.refreshing': 'Refreshing map list…', 'map.retryRefresh': 'Retry refresh', 'map.wiring.source': 'Select a free source port', 'map.wiring.target': 'Select a free destination port', 'map.wiring.clickRoute': 'Click an empty area to add a route point.', 'map.wiring.sourceLabel': 'Source: {object} / {port}', 'map.wiring.destinationLabel': 'Destination: {object} / {port}', 'map.wiring.points': 'Route points: {count}', 'map.wiring.deletePoint': 'Delete route point', 'map.wiring.cableName': 'Cable name', 'map.back': 'Back', 'map.creating': 'Creating…', 'map.createCable': 'Create cable', 'map.savingRoute': 'Saving route…', 'map.routeFailed': 'Cable created, but its route could not be saved.', 'map.retrySaveRoute': 'Retry saving route', 'map.wiringRefreshFailed': 'Cable and route were saved, but the map could not be refreshed.',
    'insert.loading': 'Loading equipment…', 'insert.resolving': 'Finding a place on the map…', 'insert.unavailable': 'The object is unavailable for placement.', 'insert.search': 'Search', 'insert.searchEquipment': 'Search equipment', 'insert.noneCreated': 'No equipment has been created yet.', 'insert.allPlaced': 'All equipment is already placed on this map.', 'insert.noResults': 'No matches for this query.', 'insert.saving': 'Adding to map…', 'action.add': 'Add', 'action.close': 'Close',
    'trace.label': 'L1 PhysicalObject trace', 'trace.source': 'From', 'trace.destination': 'To', 'trace.sourcePort': 'Source port', 'trace.destinationPort': 'Destination port', 'trace.anyPort': 'Any port', 'trace.selectObject': 'Select PhysicalObject', 'trace.level': 'Level: Physical / L1', 'trace.run': 'Trace', 'trace.result': 'L1 trace result', 'trace.reachable': 'Physical L1 path proven', 'trace.unknown': 'UNKNOWN: physical L1 path not proven', 'trace.alternatives': 'Proven alternatives: {count}', 'trace.showAlternative': 'Show alternative', 'trace.alternative': 'Alternative {index}', 'trace.cycles': 'Cycles detected: {cycles}', 'trace.gaps': 'Gaps: {gaps}', 'trace.warnings': 'Warnings: {warnings}', 'trace.clear': 'Clear trace', 'trace.portLoadFailed': 'Could not load ports: {error}. You can trace with “Any port”.', 'trace.inventoryLoadFailed': 'Could not load equipment inventory.', 'trace.datasourceUnavailable': 'L1 trace datasource is not available yet.', 'trace.selectEndpoints': 'Select PhysicalObject values for “From” and “To”.', 'trace.failed': 'Could not perform L1 trace.',
    'canvas.layoutFailed': 'Could not lay out the topology', 'canvas.layouting': 'Laying out topology…', 'canvas.physical': 'Physical network topology', 'canvas.logical': 'Logical network topology', 'canvas.autoLayout': 'Auto-layout', 'canvas.minimap': 'Mini-map',
    'action.cancel': 'Cancel', 'map.collision': 'Objects cannot be placed on top of each other.', 'map.removeRefreshFailed': 'Object was removed from the map, but the map could not be refreshed.', 'map.addRefreshFailed': 'Object was added to the map, but the map could not be refreshed.', 'map.deleteRefreshFailed': 'Object was deleted, but the map could not be refreshed.', 'inspector.label': 'Quick inspector', 'inspector.close': 'Close inspector', 'inspector.technical': 'Technical details', 'inspector.offMap': 'OFF MAP', 'inspector.connected': 'Connected:', 'inspector.cable': 'CABLE', 'inspector.networkObject': 'NETWORK OBJECT', 'inspector.connection': 'Connection', 'inspector.open': 'Open object', 'inspector.remove': 'Remove from map', 'inspector.actions': 'Additional actions', 'inspector.deleteObject': 'Delete object from NetMap', 'inspector.deleteCable': 'Delete cable and disconnect the physical connection', 'inspector.lock': 'Lock position', 'inspector.unlock': 'Unlock position', 'inspector.loadingCable': 'Loading verified cable endpoints…', 'inspector.cableUnresolved': 'Cable endpoints could not be determined unambiguously.', 'inspector.cableUnavailable': 'Verified cable data is unavailable.', 'inspector.route': 'Route on map', 'inspector.routePoints': 'Points: {count}', 'inspector.noRoute': 'No custom route is set', 'inspector.editRoute': 'Edit route', 'inspector.resetRoute': 'Reset route', 'inspector.routeResetFailed': 'Route was reset, but the map could not be refreshed.', 'inspector.routeEditHelp': 'Drag a point or click a route segment to insert a new one.', 'inspector.deleteSelectedPoint': 'Delete selected point', 'inspector.saveRoute': 'Save route', 'inspector.loadingConnections': 'Loading physical connections…', 'inspector.noPorts': 'No ports', 'inspector.portSummary': 'Ports: {ports} · connected: {attached} · free: {free}', 'inspector.portOccupancyUnknown': 'Ports: {ports} · occupancy unavailable', 'inspector.interfaces': 'Network interfaces: {count}', 'inspector.noConnections': 'No physical connections.', 'inspector.unresolvedConnection': 'Physical connection is unresolved', 'inspector.remoteObject': 'Remote object', 'inspector.port': 'port', 'inspector.viaCable': ' via {cable}', 'inspector.moreConnections': '{count} more connections', 'inspector.noCanonicalRef': 'The object has no unambiguous canonical reference.', 'inspector.unknownObject': 'Unknown object',
  },
} as const;


export type MessageKey = keyof typeof messages.ru;
export const readStoredLocale = (storage: Pick<Storage, 'getItem'> | undefined = typeof window === 'undefined' ? undefined : window.localStorage): Locale => {
  const value = storage?.getItem(localeStorageKey);
  return locales.includes(value as Locale) ? value as Locale : 'ru';
};

type I18n = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: MessageKey, values?: Record<string, string | number>) => string; collator: Intl.Collator };
const format = (message: string, values?: Record<string, string | number>) => message.replace(/\{(\w+)\}/g, (_, name) => String(values?.[name] ?? `{${name}}`));
const defaultI18n: I18n = { locale: 'ru', setLocale: () => undefined, t: (key, values) => format(messages.ru[key], values), collator: new Intl.Collator('ru', { numeric: true, sensitivity: 'base' }) };
const I18nContext = createContext<I18n>(defaultI18n);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => readStoredLocale());
  useEffect(() => { document.documentElement.lang = locale; window.localStorage.setItem(localeStorageKey, locale); }, [locale]);
  const value = useMemo<I18n>(() => ({ locale, setLocale, t: (key, values) => format(messages[locale][key], values), collator: new Intl.Collator(locale, { numeric: true, sensitivity: 'base' }) }), [locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n(): I18n { return useContext(I18nContext); }
