import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export const locales = ['ru', 'en'] as const;
export type Locale = typeof locales[number];
export const localeStorageKey = 'netmap.locale';

const messages = {
  ru: {
    'language.label': 'Язык', 'language.ru': 'Русский', 'language.en': 'English',
    'nav.primary': 'Основная навигация', 'nav.map': 'Карта', 'nav.infrastructure': 'Инфраструктура', 'nav.objects': 'Объекты', 'nav.library': 'Библиотека', 'nav.blueprints': 'Шаблоны объектов',
    'health.checking': 'Проверка backend', 'health.healthy': 'Backend доступен', 'health.unavailable': 'Backend недоступен',
    'view.loading.title': 'Загружаем topology projection', 'view.loading.body': 'Подготавливаем логическую схему…', 'view.empty.title': 'В этом scope пока пусто', 'view.empty.body': 'Projection не содержит устройств или связей.', 'view.error.title': 'Не удалось загрузить схему', 'view.error.body': 'Источник topology projection вернул ошибку.', 'action.retry': 'Повторить',
    'catalog.untype': 'Без типа', 'catalog.loading.title': 'Загружаем каталог', 'catalog.loading.body': 'Получаем инвентарный список оборудования и кабелей…', 'catalog.error.title': 'Не удалось загрузить каталог', 'map.geometryUnavailable': 'Не удалось определить размеры объекта для размещения.',
    'catalog.infrastructure': 'Инфраструктура', 'catalog.title': 'Каталог', 'catalog.description': 'Оборудование, кабели, физические порты и размещение на картах.', 'catalog.createObject': 'Создать объект', 'catalog.sections': 'Разделы каталога', 'catalog.equipment': 'Оборудование ({count})', 'catalog.cables': 'Кабели ({count})', 'catalog.searchFilters': 'Поиск и фильтры', 'catalog.search': 'Поиск', 'catalog.type': 'Тип', 'catalog.map': 'Карта', 'catalog.ports': 'Порты', 'catalog.cableState': 'Состояние кабеля', 'catalog.all': 'Все', 'catalog.allMaps': 'Все карты', 'catalog.noMap': 'Без карты', 'catalog.connectedPorts': 'Есть подключения', 'catalog.freePorts': 'Есть свободные порты', 'catalog.busyPorts': 'Все порты заняты', 'catalog.occupancyUnknown': 'Состояние неизвестно', 'catalog.resolved': 'Разрешённые', 'catalog.unresolved': 'Неоднозначные', 'catalog.list': 'Список каталога', 'catalog.empty': 'Каталог пока пуст.', 'catalog.noEquipment': 'Оборудование пока не создано.', 'catalog.cablesHint': 'Кабели создаются через существующее физическое соединение.', 'catalog.noResults': 'По заданным условиям ничего не найдено.', 'catalog.refreshError': 'Не удалось обновить каталог: {error}', 'catalog.renameObject': 'Переименовать объект', 'catalog.renameCable': 'Переименовать кабель', 'catalog.name': 'Название', 'catalog.save': 'Сохранить', 'catalog.retryRefresh': 'Повторить обновление', 'catalog.deleteObjectConfirm': 'Удалить объект «{name}»?', 'catalog.deleteCableConfirm': 'Удалить кабель «{name}» и разорвать соединение?', 'catalog.freeCount': '{count} свободно', 'catalog.notAvailable': 'Нет', 'catalog.undefined': 'Состояние не определено', 'catalog.actions': 'Действия', 'catalog.endpointA': 'Конец A', 'catalog.endpointB': 'Конец B', 'catalog.status': 'Состояние', 'catalog.renameRefreshError': 'Имя сохранено, но каталог не удалось обновить. Повторите обновление.', 'catalog.unknownError': 'Неизвестная ошибка',
    'object.breadcrumbs': 'Хлебные крошки', 'object.loading': 'Загрузка…', 'object.loadingTitle': 'Загружаем объект…', 'object.missingId': 'Не указан canonical ID объекта.', 'object.main': 'Основное', 'object.class': 'Класс', 'object.notSpecified': 'Не указан', 'object.maps': 'Карты', 'object.cableMapsHint': 'Кабель отображается на физических картах через свои подключения и отдельно на карту не размещается.', 'object.mapLoadError': 'Не удалось загрузить данные о размещении на картах: {error}', 'object.mapLoading': 'Загружаем данные о размещении на картах…', 'object.mapUnavailable': 'Данные о размещении на картах недоступны.', 'object.noMaps': 'На картах: нет', 'object.onMaps': 'На картах:', 'object.addToMap': 'Добавить на карту', 'object.mapsEmpty': 'Карты пока не созданы.', 'object.alreadyOnMaps': 'Объект уже размещён на всех доступных картах.',
    'physical.classEditor': 'Тип объекта', 'physical.classification': 'Классификация', 'physical.other': 'Другое', 'physical.value': 'Значение', 'physical.valueExample': 'Например: ups', 'physical.saveClass': 'Сохранить тип', 'physical.saving': 'Сохраняем…', 'physical.unresolvedConnection': 'Физическая связь не разрешена', 'physical.remoteEndpoint': 'Удалённый endpoint', 'physical.connection': 'Физическое подключение', 'physical.connected': 'Подключён', 'physical.free': 'Свободен', 'physical.connections': 'Связей: {count}; внешних: {external}', 'physical.technical': 'Технические данные', 'physical.noCanonicalRef': 'Детали недоступны: нет однозначной ссылки на PhysicalObject.', 'physical.loading': 'Загружаем точки подключения…', 'physical.loadError': 'Не удалось загрузить физический объект. {error}', 'physical.portCount': 'Портов: {count}', 'physical.connectedCount': 'Подключено: {count}', 'physical.freeCount': 'Свободно: {count}', 'physical.interfaceCount': 'Интерфейсов: {count}', 'physical.fromBlueprint': 'Объект создан из шаблона · версия {version}. Структурные изменения выполняются через версию шаблона.', 'physical.openBlueprint': 'Открыть шаблон', 'physical.ports': 'Порты', 'physical.manualStructure': 'Ручная структура', 'physical.channels': 'Каналы', 'physical.channel': 'Канал', 'physical.port': 'Порт', 'physical.connectionA': 'Подключение A', 'physical.connectionB': 'Подключение B', 'physical.actionsA': 'Действия A', 'physical.actionsB': 'Действия B', 'physical.connectedTo': 'Подключение', 'physical.interface': 'Интерфейс', 'physical.noPoints': 'Точки подключения не заданы.', 'physical.objectTechnical': 'Технические данные объекта', 'physical.point': 'Точка {id}',
    'create.newObject': 'Новый объект', 'create.networkDevice': 'Сетевое устройство', 'create.physicalObject': 'Физический объект', 'create.closeForm': 'Закрыть форму', 'create.deviceName': 'Название устройства', 'create.firstInterface': 'Первый интерфейс', 'create.firstPoint': 'Первая точка подключения', 'create.category': 'Категория', 'create.otherUnspecified': 'Другое / не указано', 'create.otherValue': 'Другое значение', 'create.classValue': 'Значение типа', 'create.failedDevice': 'Не удалось создать устройство. {error}', 'create.failedObject': 'Не удалось создать физический объект. {error}', 'create.creating': 'Создаём…', 'create.create': 'Создать', 'create.add': 'Добавить', 'create.name': 'Название', 'create.failedPoint': 'Не удалось создать точку подключения. {error}',
    'connect.alreadyConnected': 'Точка уже подключена', 'connect.connect': 'Подключить', 'connect.portCable': 'Подключить порт кабелем', 'connect.freeInterface': 'Подключить к свободному интерфейсу', 'connect.searchObject': 'Поиск объекта', 'connect.targetObject': 'Целевой физический объект', 'connect.selectObject': 'Выберите объект', 'connect.freePort': 'Свободный физический порт', 'connect.selectPort': 'Выберите порт', 'connect.noFreePoints': 'Нет свободных точек подключения.', 'connect.advanced': 'Дополнительно: подключить к свободному интерфейсу', 'connect.interface': 'Свободный интерфейс', 'connect.selectInterface': 'Выберите интерфейс', 'connect.backPorts': 'Назад к физическим портам', 'connect.loading': 'Загружаем endpoints…', 'connect.loadError': 'Не удалось загрузить endpoints. {error}', 'connect.retryLoad': 'Повторить загрузку', 'connect.cableName': 'Название кабеля (необязательно)', 'connect.failed': 'Не удалось создать соединение. {error}', 'connect.connecting': 'Подключаем…',
    'map.maps': 'Карты', 'map.choose': 'Выберите карту', 'map.new': 'Новая карта', 'map.delete': 'Удалить карту', 'map.add': 'Добавить на карту', 'map.connectPorts': 'Соединить порты', 'map.logical': 'Логическая', 'map.physical': 'Физическая', 'map.createTitle': 'Новая карта', 'map.name': 'Название', 'map.create': 'Создать', 'map.cancel': 'Отмена', 'map.empty.title': 'Создайте первую карту', 'map.empty.active': 'Карта «{name}» пока пуста', 'map.delete.confirm': 'Удалить карту «{name}»?', 'map.delete.description': 'Будут удалены только размещения, позиции и трассы этой карты. Физические объекты и каноническая топология останутся без изменений.', 'map.deleting': 'Удаляем карту…', 'map.refreshing': 'Обновляем список карт…', 'map.retryRefresh': 'Повторить обновление', 'map.wiring.source': 'Выберите исходный свободный порт', 'map.wiring.target': 'Выберите конечный свободный порт', 'map.wiring.clickRoute': 'Клик по свободному полю добавляет точку трассы.', 'map.wiring.sourceLabel': 'Источник: {object} / {port}', 'map.wiring.destinationLabel': 'Назначение: {object} / {port}', 'map.wiring.points': 'Точек трассы: {count}', 'map.wiring.deletePoint': 'Удалить точку трассы', 'map.wiring.cableName': 'Название кабеля', 'map.back': 'Назад', 'map.creating': 'Создаём…', 'map.createCable': 'Создать кабель', 'map.savingRoute': 'Сохраняем трассу…', 'map.routeFailed': 'Кабель создан, но трассу не удалось сохранить.', 'map.retrySaveRoute': 'Повторить сохранение трассы', 'map.wiringRefreshFailed': 'Кабель и трасса сохранены, но карту не удалось обновить.',
    'insert.loading': 'Загружаем оборудование…', 'insert.resolving': 'Определяем место на карте…', 'insert.unavailable': 'Объект недоступен для размещения.', 'insert.search': 'Поиск', 'insert.searchEquipment': 'Поиск оборудования', 'insert.noneCreated': 'Оборудование пока не создано.', 'insert.allPlaced': 'Всё оборудование уже размещено на этой карте.', 'insert.noResults': 'По заданному запросу ничего не найдено.', 'insert.saving': 'Добавляем на карту…', 'action.add': 'Добавить', 'action.close': 'Закрыть',
    'trace.label': 'L1 трассировка PhysicalObject', 'trace.source': 'Откуда', 'trace.destination': 'Куда', 'trace.sourcePort': 'Порт источника', 'trace.destinationPort': 'Порт назначения', 'trace.anyPort': 'Любой порт', 'trace.selectObject': 'Выберите PhysicalObject', 'trace.level': 'Уровень: Physical / L1', 'trace.run': 'Трассировать', 'trace.result': 'Результат L1 trace', 'trace.reachable': 'Физический L1-путь доказан', 'trace.unknown': 'UNKNOWN: физический L1-путь не доказан', 'trace.alternatives': 'Доказанных альтернатив: {count}', 'trace.showAlternative': 'Показать альтернативу', 'trace.alternative': 'Альтернатива {index}', 'trace.cycles': 'Обнаружены циклы: {cycles}', 'trace.gaps': 'Gaps: {gaps}', 'trace.warnings': 'Warnings: {warnings}', 'trace.clear': 'Сбросить трассировку', 'trace.portLoadFailed': 'Не удалось загрузить порты: {error}. Можно трассировать с «Любой порт».', 'trace.inventoryLoadFailed': 'Не удалось загрузить инвентарь оборудования.', 'trace.datasourceUnavailable': 'L1 trace datasource пока недоступен.', 'trace.selectEndpoints': 'Выберите PhysicalObject для «Откуда» и «Куда».', 'trace.failed': 'Не удалось выполнить L1 trace.',
    'canvas.layoutFailed': 'Не удалось расположить топологию', 'canvas.layouting': 'Располагаем топологию…', 'canvas.physical': 'Физическая схема сети', 'canvas.logical': 'Логическая схема сети', 'canvas.autoLayout': 'Авторазмещение', 'canvas.minimap': 'Мини-карта',
    'action.cancel': 'Отменить', 'map.collision': 'Объекты нельзя размещать друг на друге.', 'map.removeRefreshFailed': 'Объект убран с карты, но карту не удалось обновить.', 'map.addRefreshFailed': 'Объект добавлен, но карту не удалось обновить.', 'map.deleteRefreshFailed': 'Объект удалён, но карту не удалось обновить.', 'inspector.label': 'Быстрый инспектор', 'inspector.close': 'Закрыть инспектор', 'inspector.technical': 'Технические детали', 'inspector.offMap': 'ВНЕ КАРТЫ', 'inspector.connected': 'Подключено:', 'inspector.cable': 'КАБЕЛЬ', 'inspector.networkObject': 'СЕТЕВОЙ ОБЪЕКТ', 'inspector.connection': 'Связь', 'inspector.open': 'Открыть объект', 'inspector.remove': 'Убрать с карты', 'inspector.actions': 'Дополнительные действия', 'inspector.deleteObject': 'Удалить объект из NetMap', 'inspector.deleteCable': 'Удалить кабель и разорвать физическое соединение', 'inspector.lock': 'Зафиксировать положение', 'inspector.unlock': 'Разблокировать положение', 'inspector.loadingCable': 'Загружаем проверенные концы кабеля…', 'inspector.cableUnresolved': 'Концы кабеля не удалось однозначно определить.', 'inspector.cableUnavailable': 'Проверенные данные кабеля недоступны.', 'inspector.route': 'Трасса на карте', 'inspector.routePoints': 'Точек: {count}', 'inspector.noRoute': 'Пользовательская трасса не задана', 'inspector.editRoute': 'Редактировать трассу', 'inspector.resetRoute': 'Сбросить трассу', 'inspector.routeResetFailed': 'Трасса сброшена, но карту не удалось обновить.', 'inspector.routeEditHelp': 'Перетащите точку или нажмите на участок трассы, чтобы вставить новую.', 'inspector.deleteSelectedPoint': 'Удалить выбранную точку', 'inspector.saveRoute': 'Сохранить трассу', 'inspector.loadingConnections': 'Загружаем физические подключения…', 'inspector.noPorts': 'Портов нет', 'inspector.portSummary': '{ports} портов · {attached} подключено · {free} свободно', 'inspector.portOccupancyUnknown': '{ports} порта · Занятость не определена', 'inspector.interfaces': 'Сетевых интерфейсов: {count}', 'inspector.noConnections': 'Физических подключений нет.', 'inspector.unresolvedConnection': 'Физическая связь не разрешена', 'inspector.remoteObject': 'Удалённый объект', 'inspector.port': 'порт', 'inspector.viaCable': ' через {cable}', 'inspector.moreConnections': 'Ещё {count} подключений', 'inspector.noCanonicalRef': 'У объекта нет однозначной canonical-ссылки.', 'inspector.unknownObject': 'Неизвестный объект',
  },
  en: {
    'language.label': 'Language', 'language.ru': 'Русский', 'language.en': 'English',
    'nav.primary': 'Primary navigation', 'nav.map': 'Map', 'nav.infrastructure': 'Infrastructure', 'nav.objects': 'Objects', 'nav.library': 'Library', 'nav.blueprints': 'Object blueprints',
    'health.checking': 'Checking backend', 'health.healthy': 'Backend available', 'health.unavailable': 'Backend unavailable',
    'view.loading.title': 'Loading topology projection', 'view.loading.body': 'Preparing the logical topology…', 'view.empty.title': 'Nothing in this scope yet', 'view.empty.body': 'The projection contains no devices or connections.', 'view.error.title': 'Could not load topology', 'view.error.body': 'The topology projection source returned an error.', 'action.retry': 'Retry',
    'catalog.untype': 'No type', 'catalog.loading.title': 'Loading catalog', 'catalog.loading.body': 'Loading the equipment and cable inventory…', 'catalog.error.title': 'Could not load catalog', 'map.geometryUnavailable': 'Could not determine the object dimensions for placement.',
    'catalog.infrastructure': 'Infrastructure', 'catalog.title': 'Catalog', 'catalog.description': 'Equipment, cables, physical ports, and map placement.', 'catalog.createObject': 'Create object', 'catalog.sections': 'Catalog sections', 'catalog.equipment': 'Equipment ({count})', 'catalog.cables': 'Cables ({count})', 'catalog.searchFilters': 'Search and filters', 'catalog.search': 'Search', 'catalog.type': 'Type', 'catalog.map': 'Map', 'catalog.ports': 'Ports', 'catalog.cableState': 'Cable state', 'catalog.all': 'All', 'catalog.allMaps': 'All maps', 'catalog.noMap': 'No map', 'catalog.connectedPorts': 'Has connections', 'catalog.freePorts': 'Has free ports', 'catalog.busyPorts': 'All ports busy', 'catalog.occupancyUnknown': 'Occupancy unknown', 'catalog.resolved': 'Resolved', 'catalog.unresolved': 'Ambiguous', 'catalog.list': 'Catalog list', 'catalog.empty': 'The catalog is empty.', 'catalog.noEquipment': 'No equipment has been created yet.', 'catalog.cablesHint': 'Cables are created through an existing physical connection.', 'catalog.noResults': 'No results match these conditions.', 'catalog.refreshError': 'Could not refresh catalog: {error}', 'catalog.renameObject': 'Rename object', 'catalog.renameCable': 'Rename cable', 'catalog.name': 'Name', 'catalog.save': 'Save', 'catalog.retryRefresh': 'Retry refresh', 'catalog.deleteObjectConfirm': 'Delete object “{name}”?', 'catalog.deleteCableConfirm': 'Delete cable “{name}” and disconnect it?', 'catalog.freeCount': '{count} free', 'catalog.notAvailable': 'No', 'catalog.undefined': 'Status unavailable', 'catalog.actions': 'Actions', 'catalog.endpointA': 'Endpoint A', 'catalog.endpointB': 'Endpoint B', 'catalog.status': 'Status', 'catalog.renameRefreshError': 'Name saved, but the catalog could not be refreshed. Retry refresh.', 'catalog.unknownError': 'Unknown error',
    'object.breadcrumbs': 'Breadcrumbs', 'object.loading': 'Loading…', 'object.loadingTitle': 'Loading object…', 'object.missingId': 'The object canonical ID is missing.', 'object.main': 'Overview', 'object.class': 'Class', 'object.notSpecified': 'Not specified', 'object.maps': 'Maps', 'object.cableMapsHint': 'A cable appears on physical maps through its connections and cannot be placed on a map separately.', 'object.mapLoadError': 'Could not load map placement data: {error}', 'object.mapLoading': 'Loading map placement data…', 'object.mapUnavailable': 'Map placement data is unavailable.', 'object.noMaps': 'On maps: no', 'object.onMaps': 'On maps:', 'object.addToMap': 'Add to map', 'object.mapsEmpty': 'No maps have been created yet.', 'object.alreadyOnMaps': 'The object is already placed on every available map.',
    'physical.classEditor': 'Object type', 'physical.classification': 'Classification', 'physical.other': 'Other', 'physical.value': 'Value', 'physical.valueExample': 'For example: ups', 'physical.saveClass': 'Save type', 'physical.saving': 'Saving…', 'physical.unresolvedConnection': 'Physical connection is unresolved', 'physical.remoteEndpoint': 'Remote endpoint', 'physical.connection': 'Physical connection', 'physical.connected': 'Connected', 'physical.free': 'Free', 'physical.connections': 'Connections: {count}; external: {external}', 'physical.technical': 'Technical details', 'physical.noCanonicalRef': 'Details are unavailable: there is no unambiguous PhysicalObject reference.', 'physical.loading': 'Loading connection points…', 'physical.loadError': 'Could not load the physical object. {error}', 'physical.portCount': 'Ports: {count}', 'physical.connectedCount': 'Connected: {count}', 'physical.freeCount': 'Free: {count}', 'physical.interfaceCount': 'Interfaces: {count}', 'physical.fromBlueprint': 'Object created from a blueprint · version {version}. Structural changes are made through the blueprint version.', 'physical.openBlueprint': 'Open blueprint', 'physical.ports': 'Ports', 'physical.manualStructure': 'Manual structure', 'physical.channels': 'Channels', 'physical.channel': 'Channel', 'physical.port': 'Port', 'physical.connectionA': 'Connection A', 'physical.connectionB': 'Connection B', 'physical.actionsA': 'Actions A', 'physical.actionsB': 'Actions B', 'physical.connectedTo': 'Connected to', 'physical.interface': 'Interface', 'physical.noPoints': 'No connection points are defined.', 'physical.objectTechnical': 'Object technical details', 'physical.point': 'Point {id}',
    'create.newObject': 'New object', 'create.networkDevice': 'Network device', 'create.physicalObject': 'Physical object', 'create.closeForm': 'Close form', 'create.deviceName': 'Device name', 'create.firstInterface': 'First interface', 'create.firstPoint': 'First connection point', 'create.category': 'Category', 'create.otherUnspecified': 'Other / unspecified', 'create.otherValue': 'Other value', 'create.classValue': 'Class value', 'create.failedDevice': 'Could not create device. {error}', 'create.failedObject': 'Could not create physical object. {error}', 'create.creating': 'Creating…', 'create.create': 'Create', 'create.add': 'Add', 'create.name': 'Name', 'create.failedPoint': 'Could not create connection point. {error}',
    'connect.alreadyConnected': 'Point is already connected', 'connect.connect': 'Connect', 'connect.portCable': 'Connect port with cable', 'connect.freeInterface': 'Connect to a free interface', 'connect.searchObject': 'Search object', 'connect.targetObject': 'Target physical object', 'connect.selectObject': 'Select object', 'connect.freePort': 'Free physical port', 'connect.selectPort': 'Select port', 'connect.noFreePoints': 'No free connection points.', 'connect.advanced': 'Advanced: connect to a free interface', 'connect.interface': 'Free interface', 'connect.selectInterface': 'Select interface', 'connect.backPorts': 'Back to physical ports', 'connect.loading': 'Loading endpoints…', 'connect.loadError': 'Could not load endpoints. {error}', 'connect.retryLoad': 'Retry loading', 'connect.cableName': 'Cable name (optional)', 'connect.failed': 'Could not create connection. {error}', 'connect.connecting': 'Connecting…',
    'map.maps': 'Maps', 'map.choose': 'Choose a map', 'map.new': 'New map', 'map.delete': 'Delete map', 'map.add': 'Add to map', 'map.connectPorts': 'Connect ports', 'map.logical': 'Logical', 'map.physical': 'Physical', 'map.createTitle': 'New map', 'map.name': 'Name', 'map.create': 'Create', 'map.cancel': 'Cancel', 'map.empty.title': 'Create your first map', 'map.empty.active': 'Map “{name}” is empty', 'map.delete.confirm': 'Delete map “{name}”?', 'map.delete.description': 'Only this map’s placements, positions, and routes will be deleted. Physical objects and canonical topology will remain unchanged.', 'map.deleting': 'Deleting map…', 'map.refreshing': 'Refreshing map list…', 'map.retryRefresh': 'Retry refresh', 'map.wiring.source': 'Select a free source port', 'map.wiring.target': 'Select a free destination port', 'map.wiring.clickRoute': 'Click an empty area to add a route point.', 'map.wiring.sourceLabel': 'Source: {object} / {port}', 'map.wiring.destinationLabel': 'Destination: {object} / {port}', 'map.wiring.points': 'Route points: {count}', 'map.wiring.deletePoint': 'Delete route point', 'map.wiring.cableName': 'Cable name', 'map.back': 'Back', 'map.creating': 'Creating…', 'map.createCable': 'Create cable', 'map.savingRoute': 'Saving route…', 'map.routeFailed': 'Cable created, but its route could not be saved.', 'map.retrySaveRoute': 'Retry saving route', 'map.wiringRefreshFailed': 'Cable and route were saved, but the map could not be refreshed.',
    'insert.loading': 'Loading equipment…', 'insert.resolving': 'Finding a place on the map…', 'insert.unavailable': 'The object is unavailable for placement.', 'insert.search': 'Search', 'insert.searchEquipment': 'Search equipment', 'insert.noneCreated': 'No equipment has been created yet.', 'insert.allPlaced': 'All equipment is already placed on this map.', 'insert.noResults': 'No matches for this query.', 'insert.saving': 'Adding to map…', 'action.add': 'Add', 'action.close': 'Close',
    'trace.label': 'L1 PhysicalObject trace', 'trace.source': 'From', 'trace.destination': 'To', 'trace.sourcePort': 'Source port', 'trace.destinationPort': 'Destination port', 'trace.anyPort': 'Any port', 'trace.selectObject': 'Select PhysicalObject', 'trace.level': 'Level: Physical / L1', 'trace.run': 'Trace', 'trace.result': 'L1 trace result', 'trace.reachable': 'Physical L1 path proven', 'trace.unknown': 'UNKNOWN: physical L1 path not proven', 'trace.alternatives': 'Proven alternatives: {count}', 'trace.showAlternative': 'Show alternative', 'trace.alternative': 'Alternative {index}', 'trace.cycles': 'Cycles detected: {cycles}', 'trace.gaps': 'Gaps: {gaps}', 'trace.warnings': 'Warnings: {warnings}', 'trace.clear': 'Clear trace', 'trace.portLoadFailed': 'Could not load ports: {error}. You can trace with “Any port”.', 'trace.inventoryLoadFailed': 'Could not load equipment inventory.', 'trace.datasourceUnavailable': 'L1 trace datasource is not available yet.', 'trace.selectEndpoints': 'Select PhysicalObject values for “From” and “To”.', 'trace.failed': 'Could not perform L1 trace.',
    'canvas.layoutFailed': 'Could not lay out the topology', 'canvas.layouting': 'Laying out topology…', 'canvas.physical': 'Physical network topology', 'canvas.logical': 'Logical network topology', 'canvas.autoLayout': 'Auto-layout', 'canvas.minimap': 'Mini-map',
    'action.cancel': 'Cancel', 'map.collision': 'Objects cannot be placed on top of each other.', 'map.removeRefreshFailed': 'Object was removed from the map, but the map could not be refreshed.', 'map.addRefreshFailed': 'Object was added to the map, but the map could not be refreshed.', 'map.deleteRefreshFailed': 'Object was deleted, but the map could not be refreshed.', 'inspector.label': 'Quick inspector', 'inspector.close': 'Close inspector', 'inspector.technical': 'Technical details', 'inspector.offMap': 'OFF MAP', 'inspector.connected': 'Connected:', 'inspector.cable': 'CABLE', 'inspector.networkObject': 'NETWORK OBJECT', 'inspector.connection': 'Connection', 'inspector.open': 'Open object', 'inspector.remove': 'Remove from map', 'inspector.actions': 'Additional actions', 'inspector.deleteObject': 'Delete object from NetMap', 'inspector.deleteCable': 'Delete cable and disconnect the physical connection', 'inspector.lock': 'Lock position', 'inspector.unlock': 'Unlock position', 'inspector.loadingCable': 'Loading verified cable endpoints…', 'inspector.cableUnresolved': 'Cable endpoints could not be determined unambiguously.', 'inspector.cableUnavailable': 'Verified cable data is unavailable.', 'inspector.route': 'Route on map', 'inspector.routePoints': 'Points: {count}', 'inspector.noRoute': 'No custom route is set', 'inspector.editRoute': 'Edit route', 'inspector.resetRoute': 'Reset route', 'inspector.routeResetFailed': 'Route was reset, but the map could not be refreshed.', 'inspector.routeEditHelp': 'Drag a point or click a route segment to insert a new one.', 'inspector.deleteSelectedPoint': 'Delete selected point', 'inspector.saveRoute': 'Save route', 'inspector.loadingConnections': 'Loading physical connections…', 'inspector.noPorts': 'No ports', 'inspector.portSummary': 'Ports: {ports} · connected: {attached} · free: {free}', 'inspector.portOccupancyUnknown': 'Ports: {ports} · occupancy unavailable', 'inspector.interfaces': 'Network interfaces: {count}', 'inspector.noConnections': 'No physical connections.', 'inspector.unresolvedConnection': 'Physical connection is unresolved', 'inspector.remoteObject': 'Remote object', 'inspector.port': 'port', 'inspector.viaCable': ' via {cable}', 'inspector.moreConnections': '{count} more connections', 'inspector.noCanonicalRef': 'The object has no unambiguous canonical reference.', 'inspector.unknownObject': 'Unknown object',
  },
} as const;


export type MessageKey = keyof typeof messages.ru;
export const readStoredLocale = (storage: Pick<Storage, 'getItem'> | undefined = typeof window === 'undefined' ? undefined : window.localStorage): Locale => {
  const value = storage?.getItem(localeStorageKey);
  return locales.includes(value as Locale) ? value as Locale : 'ru';
};

type I18n = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: MessageKey, values?: Record<string, string | number>) => string; collator: Intl.Collator };
const format = (message: string, values?: Record<string, string | number>) => message.replace(/\{(\w+)\}/g, (_, name) => String(values?.[name] ?? `{${name}}`));
const defaultI18n: I18n = { locale: 'ru', setLocale: () => undefined, t: (key, values) => format(messages.ru[key], values), collator: new Intl.Collator('ru', { numeric: true, sensitivity: 'base' }) };
const I18nContext = createContext<I18n>(defaultI18n);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => readStoredLocale());
  useEffect(() => { document.documentElement.lang = locale; window.localStorage.setItem(localeStorageKey, locale); }, [locale]);
  const value = useMemo<I18n>(() => ({ locale, setLocale, t: (key, values) => format(messages[locale][key], values), collator: new Intl.Collator(locale, { numeric: true, sensitivity: 'base' }) }), [locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n(): I18n { return useContext(I18nContext); }
